<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  Client
 *
 * @copyright   Copyright (C) 2005 - 2013 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM . '/joomla/client/helper.php';

/**
 * Test class for JClientHelper.
 * Generated by PHPUnit on 2009-10-08 at 21:48:23.
 *
 * @package  Joomla.UnitTest
 *
 * @since    11.1
 */
class JClientHelperTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var    JClientHelper
	 * @access protected
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 *
	 * @return void
	 */
	protected function setUp()
	{
		parent::setUp();

		$this->object = new JClientHelper;
	}

	/**
	 * Test...
	 *
	 * @todo Implement testGetCredentials().
	 *
	 * @return void
	 */
	public function testGetCredentials()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * Test...
	 *
	 * @todo Implement testSetCredentials().
	 *
	 * @return void
	 */
	public function testSetCredentials()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * Test...
	 *
	 * @todo Implement testHasCredentials().
	 *
	 * @return void
	 */
	public function testHasCredentials()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}

	/**
	 * Test...
	 *
	 * @todo Implement testSetCredentialsFromRequest().
	 *
	 * @return void
	 */
	public function testSetCredentialsFromRequest()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
