<refentry id="{@id}">
 <refnamediv>
  <refname>JModel</refname>
  <refpurpose>Learn how to use the JModel class</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <authorgroup>
   <author>
    Andrew Eddie
    <authorblurb>
     {@link mailto:developer@osm.org}
    </authorblurb>
   </author>
  </authorgroup>
 </refsynopsisdiv>
 <refsect1 id="">
  <title>Working with JModel</title>
  <para>The JModel is your workhorse class that allows you to easily map php objects to a database table.</para>
 </refsect1>
 <refsect1 id="">
  <title>Another docbook refsect</title>
  <para>
   Here's some text
  </para>
 </refsect1>
</refentry>
