<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  HTML
 *
 * @copyright   Copyright (C) 2005 - 2012 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

/**
 * Test class for JHtmlJquerybehavior.
 * Generated by PHPUnit on 2012-08-16 at 17:40:47.
 */
class JHtmlJquerybehaviorTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JHtmlJquerybehavior
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		//$this->object = new JHtmlJquerybehavior;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers JHtmlJquerybehavior::tooltip
	 * @todo   Implement testTooltip().
	 */
	public function testTooltip()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JHtmlJquerybehavior::popover
	 * @todo   Implement testPopover().
	 */
	public function testPopover()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.'
		);
	}
}
