CodeMirror.defineMode("markdown",function(t,u){var m=CodeMirror.modes.hasOwnProperty("xml");var i=CodeMirror.getMode(t,m?{name:"xml",htmlMode:true}:"text/plain");
var x={html:"htmlmixed",js:"javascript",json:"application/json",c:"text/x-csrc","c++":"text/x-c++src",java:"text/x-java",csharp:"text/x-csharp","c#":"text/x-csharp",scala:"text/x-scala"};
var B=(function(){var U,Y={},S={},X;var W=[];for(var R in CodeMirror.modes){if(CodeMirror.modes.propertyIsEnumerable(R)){W.push(R);}}for(U=0;U<W.length;
U++){Y[W[U]]=W[U];}var V=[];for(var R in CodeMirror.mimeModes){if(CodeMirror.mimeModes.propertyIsEnumerable(R)){V.push({mime:R,mode:CodeMirror.mimeModes[R]});
}}for(U=0;U<V.length;U++){X=V[U].mime;S[X]=V[U].mime;}for(var T in x){if(x[T] in Y||x[T] in S){Y[T]=x[T];}}return function(Z){return Y[Z]?CodeMirror.getMode(t,Y[Z]):null;
};}());if(u.underscoresBreakWords===undefined){u.underscoresBreakWords=true;}if(u.fencedCodeBlocks===undefined){u.fencedCodeBlocks=false;}if(u.taskLists===undefined){u.taskLists=false;
}var j=0;var h="header",f="comment",Q="atom",N="number",K="variable-2",H="variable-3",G="keyword",I="hr",g="tag",n="link",k="link",C="link",A="string",L="em",v="strong";
var a=/^([*\-=_])(?:\s*\1){2,}\s*$/,d=/^[*\-+]\s+/,y=/^[0-9]+\.\s+/,p=/^\[(x| )\](?=\s)/,J=/^(?:\={1,}|-{1,})$/,w=/^[^!\[\]*_\\<>` "'(]+/;function O(T,S,R){S.f=S.inline=R;
return R(T,S);}function z(T,S,R){S.f=S.block=R;return R(T,S);}function b(R){R.linkTitle=false;R.em=false;R.strong=false;R.quote=0;if(!m&&R.f==o){R.f=M;
R.block=F;}R.trailingSpace=0;R.trailingSpaceNewLine=false;R.thisLineHasContent=false;return null;}function F(T,S){var R=(S.list!==false);if(S.list!==false&&S.indentationDiff>=0){if(S.indentationDiff<4){S.indentation-=S.indentationDiff;
}S.list=null;}else{if(S.list!==false&&S.indentation>0){S.list=null;S.listDepth=Math.floor(S.indentation/4);}else{if(S.list!==false){S.list=false;S.listDepth=0;
}}}if(S.indentationDiff>=4){S.indentation-=4;T.skipToEnd();return f;}else{if(T.eatSpace()){return null;}else{if(T.peek()==="#"||(S.prevLineHasContent&&T.match(J))){S.header=true;
}else{if(T.eat(">")){S.indentation++;S.quote=1;T.eatSpace();while(T.eat(">")){T.eatSpace();S.quote++;}}else{if(T.peek()==="["){return O(T,S,c);}else{if(T.match(a,true)){return I;
}else{if((!S.prevLineHasContent||R)&&(T.match(d,true)||T.match(y,true))){S.indentation+=4;S.list=true;S.listDepth++;if(u.taskLists&&T.match(p,false)){S.taskList=true;
}}else{if(u.fencedCodeBlocks&&T.match(/^```([\w+#]*)/,true)){S.localMode=B(RegExp.$1);if(S.localMode){S.localState=S.localMode.startState();}z(T,S,D);return f;
}}}}}}}}return O(T,S,S.inline);}function o(T,S){var R=i.token(T,S.htmlState);if(m&&R==="tag"&&S.htmlState.type!=="openTag"&&!S.htmlState.context){S.f=M;
S.block=F;}if(S.md_inside&&T.current().indexOf(">")!=-1){S.f=M;S.block=F;S.htmlState.context=undefined;}return R;}function D(S,R){if(S.sol()&&S.match(/^```/,true)){R.localMode=R.localState=null;
R.f=M;R.block=F;return f;}else{if(R.localMode){return R.localMode.token(S,R.localState);}else{S.skipToEnd();return f;}}}function r(T){var S=[];if(T.taskOpen){return"meta";
}if(T.taskClosed){return"property";}if(T.strong){S.push(v);}if(T.em){S.push(L);}if(T.linkText){S.push(C);}if(T.code){S.push(f);}if(T.header){S.push(h);
}if(T.quote){S.push(T.quote%2?Q:N);}if(T.list!==false){var R=(T.listDepth-1)%3;if(!R){S.push(K);}else{if(R===1){S.push(H);}else{S.push(G);}}}if(T.trailingSpaceNewLine){S.push("trailing-space-new-line");
}else{if(T.trailingSpace){S.push("trailing-space-"+(T.trailingSpace%2?"a":"b"));}}return S.length?S.join(" "):null;}function l(S,R){if(S.match(w,true)){return r(R);
}return undefined;}function M(ae,S){var T=S.text(ae,S);if(typeof T!=="undefined"){return T;}if(S.list){S.list=null;return r(S);}if(S.taskList){var W=ae.match(p,true)[1]!=="x";
if(W){S.taskOpen=true;}else{S.taskClosed=true;}S.taskList=false;return r(S);}S.taskOpen=false;S.taskClosed=false;var R=ae.next();if(R==="\\"){ae.next();
return r(S);}if(S.linkTitle){S.linkTitle=false;var ab=R;if(R==="("){ab=")";}ab=(ab+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1");var aa="^\\s*(?:[^"+ab+"\\\\]+|\\\\\\\\|\\\\.)"+ab;
if(ae.match(new RegExp(aa),true)){return A;}}if(R==="`"){var af=r(S);var Z=ae.pos;ae.eatWhile("`");var U=1+ae.pos-Z;if(!S.code){j=U;S.code=true;return r(S);
}else{if(U===j){S.code=false;return af;}return r(S);}}else{if(S.code){return r(S);}}if(R==="!"&&ae.match(/\[[^\]]*\] ?(?:\(|\[)/,false)){ae.match(/\[[^\]]*\]/);
S.inline=S.f=s;return g;}if(R==="["&&ae.match(/.*\](\(| ?\[)/,false)){S.linkText=true;return r(S);}if(R==="]"&&S.linkText){var Y=r(S);S.linkText=false;
S.inline=S.f=s;return Y;}if(R==="<"&&ae.match(/^(https?|ftps?):\/\/(?:[^\\>]|\\.)+>/,false)){return O(ae,S,E(n,">"));}if(R==="<"&&ae.match(/^[^> \\]+@(?:[^\\>]|\\.)+>/,false)){return O(ae,S,E(k,">"));
}if(R==="<"&&ae.match(/^\w/,false)){if(ae.string.indexOf(">")!=-1){var X=ae.string.substring(1,ae.string.indexOf(">"));if(/markdown\s*=\s*('|"){0,1}1('|"){0,1}/.test(X)){S.md_inside=true;
}}ae.backUp(1);return z(ae,S,o);}if(R==="<"&&ae.match(/^\/\w*?>/)){S.md_inside=false;return"tag";}var V=false;if(!u.underscoresBreakWords){if(R==="_"&&ae.peek()!=="_"&&ae.match(/(\w)/,false)){var ac=ae.pos-2;
if(ac>=0){var ad=ae.string.charAt(ac);if(ad!=="_"&&ad.match(/(\w)/,false)){V=true;}}}}var af=r(S);if(R==="*"||(R==="_"&&!V)){if(S.strong===R&&ae.eat(R)){S.strong=false;
return af;}else{if(!S.strong&&ae.eat(R)){S.strong=R;return r(S);}else{if(S.em===R){S.em=false;return af;}else{if(!S.em){S.em=R;return r(S);}}}}}else{if(R===" "){if(ae.eat("*")||ae.eat("_")){if(ae.peek()===" "){return r(S);
}else{ae.backUp(1);}}}}if(R===" "){if(ae.match(/ +$/,false)){S.trailingSpace++;}else{if(S.trailingSpace){S.trailingSpaceNewLine=true;}}}return r(S);}function s(T,S){if(T.eatSpace()){return null;
}var R=T.next();if(R==="("||R==="["){return O(T,S,E(A,R==="("?")":"]"));}return"error";}function c(S,R){if(S.match(/^[^\]]*\]:/,true)){R.f=e;return C;}return O(S,R,M);
}function e(S,R){if(S.eatSpace()){return null;}S.match(/^[^\s]+/,true);if(S.peek()===undefined){R.linkTitle=true;}else{S.match(/^(?:\s+(?:"(?:[^"\\]|\\\\|\\.)+"|'(?:[^'\\]|\\\\|\\.)+'|\((?:[^)\\]|\\\\|\\.)+\)))?/,true);
}R.f=R.inline=M;return A;}var P=[];function q(R){if(!P[R]){R=(R+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1");P[R]=new RegExp("^(?:[^\\\\]|\\\\.)*?("+R+")");
}return P[R];}function E(S,T,R){R=R||M;return function(V,U){V.match(q(T));U.inline=U.f=R;return S;};}return{startState:function(){return{f:F,prevLineHasContent:false,thisLineHasContent:false,block:F,htmlState:CodeMirror.startState(i),indentation:0,inline:M,text:l,linkText:false,linkTitle:false,em:false,strong:false,header:false,taskList:false,list:false,listDepth:0,quote:0,trailingSpace:0,trailingSpaceNewLine:false};
},copyState:function(R){return{f:R.f,prevLineHasContent:R.prevLineHasContent,thisLineHasContent:R.thisLineHasContent,block:R.block,htmlState:CodeMirror.copyState(i,R.htmlState),indentation:R.indentation,localMode:R.localMode,localState:R.localMode?CodeMirror.copyState(R.localMode,R.localState):null,inline:R.inline,text:R.text,linkTitle:R.linkTitle,em:R.em,strong:R.strong,header:R.header,taskList:R.taskList,list:R.list,listDepth:R.listDepth,quote:R.quote,trailingSpace:R.trailingSpace,trailingSpaceNewLine:R.trailingSpaceNewLine,md_inside:R.md_inside};
},token:function(U,T){if(U.sol()){if(U.match(/^\s*$/,true)){T.prevLineHasContent=false;return b(T);}else{T.prevLineHasContent=T.thisLineHasContent;T.thisLineHasContent=true;
}T.header=false;T.taskList=false;T.code=false;T.trailingSpace=0;T.trailingSpaceNewLine=false;T.f=T.block;var R=U.match(/^\s*/,true)[0].replace(/\t/g,"    ").length;
var V=Math.floor((R-T.indentation)/4)*4;if(V>4){V=4;}var S=T.indentation+V;T.indentationDiff=S-T.indentation;T.indentation=S;if(R>0){return null;}}return T.f(U,T);
},blankLine:b,getType:r};},"xml");CodeMirror.defineMIME("text/x-markdown","markdown");