---
kind: pipeline
name: default

clone:

steps:
  - name: phpcs
    image: joomlaprojects/docker-images:phpcs1.5
    commands:
      - echo $(date)
      - /usr/local/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./tests/javascript/node_modules
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: javascript
    image: joomlaprojects/docker-images:systemtests
    commands:
      - echo $(date)
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
       rebuild: true
       mount:
        - ./tests/javascript/node_modules
       cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: analysis3x
    image: rips/rips-cli:3.2.2
    when:
      branch: staging
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - if [ $DRONE_REPO_NAME = "joomla-cms" ] || [ $DRONE_REPO_NAME = "cms-security" ]; then echo "The rips analysis check only runs on the joomla/joomla-cms and joomla/cms-security repo"; exit 0; fi
      - rips-cli rips:list --table=scans -n -p filter='{"__and":[{"__lessThan":{"percent":100}}]}'
      - rips-cli rips:scan:start -G -a 1 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_NAMESPACE-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }
    environment:
      RIPS_EMAIL:
        from_secret: RIPS_EMAIL
      RIPS_PASSWORD:
        from_secret: RIPS_PASSWORD

volumes:
- name: cache
  host:
    path: /tmp/cache

branches:
  exclude: [ l10n_* ]

---
kind: pipeline
name: package

steps:
  - name: packager
    image: joomlaprojects/docker-images:packager
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      HTTP_ROOT: "https://ci.joomla.org/artifacts"
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
      DRONE_COMMIT: DRONE_COMMIT
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - if [ $DRONE_REPO_NAME != 'joomla-cms' ]; then echo "The packager only runs on the joomla/joomla-cms repo"; exit 0; fi
      - /bin/drone_build.sh


---
kind: signature
hmac: b2641af6114b0cf3b9ca084fe957ae66f47598b6a9c7cc88a2365f1aa8b9dde1

...
