---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.4
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: npm
    image: node:16-alpine
    depends_on: [ composer ]
    commands:
      - npm ci --unsafe-perm

  - name: new-phpmin-system-mysql
    depends_on:
      - npm
    image: joomlaprojects/docker-images:cypress
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
      cypress_db_host: mysql
      cypress_db_password: joomla_ut

    commands:
      - npm run cypress:run

  - name: artifacts-system-tests
    image: cschlosser/drone-ftps
    depends_on:
      - new-phpmin-system-mysql
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      PLUGIN_HOSTNAME: ci.joomla.org:21
      PLUGIN_SRC_DIR: /tests/Codeception/_output/
      PLUGIN_DEST_DIR: /artifacts
      PLUGIN_SECURE: false
      PLUGIN_EXCLUDE: ^\.git/$
    commands:
      - export PLUGIN_DEST_DIR=$PLUGIN_DEST_DIR/$DRONE_REPO/$DRONE_BRANCH/$DRONE_PULL_REQUEST/system-tests/$DRONE_BUILD_NUMBER
      - echo https://ci.joomla.org$PLUGIN_DEST_DIR
      - /bin/upload.sh
    when:
      status:
        - failure

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: mysql8
    image: mysql:8
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla

  - name: postgres
    image: postgres:11-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: joomla_ut
      POSTGRES_DB: test_joomla

---
kind: pipeline
name: package

steps:
  - name: packager
    image: joomlaprojects/docker-images:packager
    environment:
      FTP_USERNAME:
        from_secret: ftpusername
      FTP_PASSWORD:
        from_secret: ftppassword
      FTP_HOSTNAME: ci.joomla.org
      FTP_PORT: "21"
      FTP_DEST_DIR: /artifacts
      FTP_VERIFY: "false"
      FTP_SECURE: "true"
      HTTP_ROOT: "https://ci.joomla.org/artifacts"
      DRONE_PULL_REQUEST: DRONE_PULL_REQUEST
      DRONE_COMMIT: DRONE_COMMIT
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - if [ $DRONE_REPO_NAME != 'joomla-cms' ]; then echo "The packager only runs on the joomla/joomla-cms repo"; exit 0; fi
      - /bin/drone_build.sh
    volumes:
      - name: reference
        path: /reference
    when:
      branch:
        - 4.2-dev

---
kind: pipeline
name: nightly_build

steps:
  - name: prepare
    image: joomlaprojects/docker-images:packager
    commands:
      - export MINORVERSION=${DRONE_BRANCH%-*}
      - composer --version
      - mkdir -p transfer
      - date +%s > transfer/$MINORVERSION-time.txt
      - git rev-parse origin/$MINORVERSION-dev > transfer/$MINORVERSION.txt
      - php build/build.php --remote=origin/$MINORVERSION-dev --exclude-gzip --exclude-bzip2
      - mv build/tmp/packages/* transfer/

  - name: upload
    image: joomlaprojects/docker-images:packager
    environment:
      nightly_key:
        from_secret: nightly_key
      nightly_user:
        from_secret: nightly_user
      nightly_host:
        from_secret: nightly_host
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - export MINORVERSION=${DRONE_BRANCH%-*}
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$nightly_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create nightly sftp host $nightly_host user $nightly_user port 22
      - rclone delete nightly:/home/devj/public_html/nightlies/ --include "Joomla_$MINORVERSION.*"
      - rclone delete nightly:/home/devj/public_html/cache/com_content/
      - rclone copy ./transfer/ nightly:/home/devj/public_html/nightlies/
      - /bin/notify

  - name: buildfailure
    image: joomlaprojects/docker-images:packager
    environment:
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - /bin/notify
    when:
      status:
        - failure


trigger:
  event:
    - cron
    - custom
  repo:
    - joomla/joomla-cms

---
kind: signature
hmac: 25bd5062f3b766484e565974854f629d9727bc4bebb581ddf0f950c5386c75c1

...
