export_languages:
  - en-GB
files:
  - source: /administrator/language/en-GB/*.ini
    translation: /administrator/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /administrator/language/en-GB/*.xml
    translation: /administrator/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /administrator/language/en-GB/localise.php
    dest: /administrator/language/en-GB/localise.txt
    translation: /administrator/language/%locale%/localise.php
    update_option: update_as_unapproved
  - source: /api/language/en-GB/*.ini
    translation: /api/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /api/language/en-GB/*.xml
    translation: /api/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /language/en-GB/*.ini
    translation: /language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /language/en-GB/*.xml
    translation: /language/%locale%/%original_file_name%
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /language/en-GB/localise.php
    dest: /language/en-GB/localise.txt
    translation: /language/%locale%/localise.php
    update_option: update_as_unapproved
  - source: /installation/language/en-GB/joomla.ini
    translation: /installation/language/%locale%/joomla.ini
    update_option: update_as_unapproved
  - source: /installation/language/en-GB/langmetadata.xml
    translation: /installation/language/%locale%/langmetadata.xml
    content_segmentation: 0
    update_option: update_as_unapproved
  - source: /build/media_source/system/js/fields/calendar-locales/en.es5.js
    translation: /build/media_source/system/js/fields/calendar-locales/%locale%.es5.js
    update_option: update_as_unapproved
  - source: /administrator/manifests/packages/pkg_en-GB.xml
    dest: /pkg_en-GB.xml
    translation: /pkg_%locale%.xml
    update_option: update_as_unapproved
    content_segmentation: 0
