export_languages: ["en-GB"]
files:
  - source: /administrator/language/en-GB/*.ini
    translation: /administrator/language/%locale%/%locale%.%original_file_name%
    type: ini
    translation_replace:
      en-GB.:
    update_option: update_as_unapproved
  - source: /administrator/language/en-GB/en-GB.localise.php
    dest: /administrator/language/en-GB/en-GB.localise.txt
    type: txt
    translation: /administrator/language/%locale%/%locale%.localise.php
    update_option: update_as_unapproved
  - source: /administrator/language/en-GB/en-GB.xml
    translation: /administrator/language/%locale%/%locale%.xml
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /administrator/language/en-GB/install.xml
    translation: /administrator/language/%locale%/install.xml
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /language/en-GB/*.ini
    translation: /language/%locale%/%locale%.%original_file_name%
    type: ini
    translation_replace:
      en-GB.:
    update_option: update_as_unapproved
  - source: /language/en-GB/en-GB.localise.php
    dest: /language/en-GB/en-GB.localise.txt
    type: txt
    translation: /language/%locale%/%locale%.localise.php
    update_option: update_as_unapproved
  - source: /language/en-GB/en-GB.xml
    translation: /language/%locale%/%locale%.xml
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /language/en-GB/install.xml
    translation: /language/%locale%/install.xml
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /installation/language/en-GB/en-GB.ini
    translation: /installation/language/%locale%/%locale%.ini
    update_option: update_as_unapproved
  - source: /installation/language/en-GB/en-GB.xml
    translation: /installation/language/%locale%/%locale%.xml
    update_option: update_as_unapproved
    content_segmentation: 0
  - source: /build/media_source/system/js/fields/calendar-locales/en.es5.js
    translation: /build/media_source/system/js/fields/calendar-locales/%locale%.es5.js
    update_option: update_as_unapproved
  - source: /administrator/manifests/packages/pkg_en-GB.xml
    dest: /pkg_en-GB.xml
    translation: /pkg_%locale%.xml
    update_option: update_as_unapproved
    content_segmentation: 0
