export const SELECT_DIRECTORY = 'SELECT_DIRECTORY';
export const SELECT_BROWSER_ITEM = 'SELECT_BROWSER_ITEM';
export const UNSELECT_BROWSER_ITEM = 'UNSELECT_BROWSER_ITEM';
export const UNSELECT_ALL_BROWSER_ITEMS = 'UNSELECT_ALL_BROWSER_ITEMS';

// Api handlers
export const LOAD_CONTENTS_SUCCESS = 'LOAD_CONTENTS_SUCCESS';
export const CREATE_DIRECTORY_SUCCESS = 'CREATE_DIRECTORY_SUCCESS';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';

// Create folder modal
export const SHOW_CREATE_FOLDER_MODAL = 'SHOW_CREATE_FOLDER_MODAL';
export const HIDE_CREATE_FOLDER_MODAL = 'HIDE_CREATE_FOLDER_MODAL';

// Delete items
export const DELETE_SUCCESS = 'DELETE_SUCCESS';