tinymce.addI18n('id',{
"Cut": "Penggal",
"Header 2": "Header 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browser anda tidak mendukung akses langsung ke clipboard. Silahkan gunakan Ctrl+X\/C\/V dari keyboard.",
"Div": "Div",
"Paste": "Tempel",
"Close": "Tutup",
"Font Family": "Font Family",
"Pre": "Pre",
"Align right": "Rata kanan",
"New document": "Dokumen baru",
"Blockquote": "Kutipan",
"Numbered list": "list nomor",
"Increase indent": "Tambah inden",
"Formats": "Format",
"Headers": "Header",
"Select all": "Pilih semua",
"Header 3": "Header 3",
"Blocks": "Blok",
"Undo": "Batal",
"Strikethrough": "Coret",
"Bullet list": "list simbol",
"Header 1": "Header 1",
"Superscript": "Superskrip",
"Clear formatting": "Hapus format",
"Font Sizes": "Ukuran Font",
"Subscript": "Subskrip",
"Header 6": "Header 6",
"Redo": "Ulang",
"Paragraph": "Paragraf",
"Ok": "Ok",
"Bold": "Tebal",
"Code": "Code",
"Italic": "Miring",
"Align center": "Rate tengah",
"Header 5": "Header 5",
"Decrease indent": "Turunkan inden",
"Header 4": "Header 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Penempelan sekarang ini dalam modus teks polos. Konten akan ditempelkan sebagai teks polos sampai anda mematikan opsi ini.",
"Underline": "Garis bawah",
"Cancel": "Batal",
"Justify": "Justifi",
"Inline": "Inline",
"Copy": "Salin",
"Align left": "Rate kiri",
"Visual aids": "Alat bantu visual",
"Lower Greek": "Lower Yunani",
"Square": "Kotak",
"Default": "Bawaan",
"Lower Alpha": "Lower Alpha",
"Circle": "Lingkaran",
"Disc": "Cakram",
"Upper Alpha": "Upper Alpha",
"Upper Roman": "Upper Roman",
"Lower Roman": "Lower Roman",
"Name": "Nama",
"Anchor": "Anjar",
"You have unsaved changes are you sure you want to navigate away?": "Anda memiliki perubahan yang belum disimpan, yakin ingin beralih ?",
"Restore last draft": "Muat kembali draft sebelumnya",
"Special character": "Spesial karakter",
"Source code": "Kode sumber",
"Right to left": "Kanan ke kiri",
"Left to right": "Kiri ke kanan",
"Emoticons": "Emotikon",
"Robots": "Robot",
"Document properties": "Properti dokumen",
"Title": "Judul",
"Keywords": "Kata kunci",
"Encoding": "Enkoding",
"Description": "Deskripsi",
"Author": "Penulis",
"Fullscreen": "Layar penuh",
"Horizontal line": "Garis Horizontal",
"Horizontal space": "Spasi Horizontal",
"Insert\/edit image": "Sisip\/edit gambar",
"General": "Umum",
"Advanced": "Tingkat Lanjut",
"Source": "Sumber",
"Border": "Garis Batas",
"Constrain proportions": "Pembatasan Proporsi",
"Vertical space": "Spasi Vertikal",
"Image description": "Deskripsi Gambar",
"Style": "Gaya",
"Dimensions": "Dimensi",
"Insert image": "Sisipkan Gambar",
"Insert date\/time": "Sisip tanggal\/waktu",
"Remove link": "Hapus Tautan",
"Url": "Url",
"Text to display": "Teks untuk ditampilkan",
"Anchors": "Anchor",
"Insert link": "Sisipkan Tautan",
"New window": "Window Baru",
"None": "Tidak Ada",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Tautan yang Anda masukkan sepertinya adalah sebuah tautan eksternal. Apakah anda ingin menambahkan prefiks http:\/\/ yang diperlukan?",
"Target": "Target",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Tautan yang Anda masukkan sepertinya adalah sebuah alamat email. Apakah anda ingin menambahkan prefiks mailto: yang diperlukan?",
"Insert\/edit link": "Sisipkan\/edit tautan",
"Insert\/edit video": "Sisipkan\/edit video",
"Poster": "Penulis",
"Alternative source": "Sumber Alternatif",
"Paste your embed code below:": "Tempel kode embed anda berikut:",
"Insert video": "Sisipkan video",
"Embed": "Embed",
"Nonbreaking space": "Spasi Nonbreaking",
"Page break": "Page break",
"Paste as text": "Tempel sebagai teks",
"Preview": "Pratinjau",
"Print": "Cetak",
"Save": "Simpan",
"Could not find the specified string.": "Tidak bisa menemukan string yang dispesifikasikan.",
"Replace": "Ganti",
"Next": "Berikut",
"Whole words": "Semua Kata",
"Find and replace": "Cari dan ganti",
"Replace with": "Ganti dengan",
"Find": "Temukan",
"Replace all": "Ganti semua",
"Match case": "Match case",
"Prev": "Sebelumnya",
"Spellcheck": "Periksa Ejaan",
"Finish": "Selesai",
"Ignore all": "Abaikan Semua",
"Ignore": "Abaikan",
"Insert row before": "Sisip baris disebelumnya",
"Rows": "Baris",
"Height": "Tinggi",
"Paste row after": "Tempel baris disetelahnya",
"Alignment": "Penjajaran",
"Column group": "Kelompok kolom",
"Row": "Baris",
"Insert column before": "Sisip kolom disebelumnya",
"Split cell": "Bagi sel",
"Cell padding": "Lapisan sel",
"Cell spacing": "Spasi sel",
"Row type": "Tipe baris",
"Insert table": "Sisip tabel",
"Body": "Body",
"Caption": "Ket.",
"Footer": "Footer",
"Delete row": "Hapus baris",
"Paste row before": "Tempel baris disebelumnya",
"Scope": "Cakupan",
"Delete table": "Hapus tabel",
"Header cell": "Header sel",
"Column": "Kolom",
"Cell": "Sel",
"Header": "Header",
"Cell type": "Tipe Sel",
"Copy row": "Salin baris",
"Row properties": "Properti Baris",
"Table properties": "Properti Tabel",
"Row group": "Grup Baris",
"Right": "Kanan",
"Insert column after": "Sisip kolom disetelahnya",
"Cols": "Cols",
"Insert row after": "Sisip baris disetelahnya",
"Width": "Lebar",
"Cell properties": "Properti Sel",
"Left": "Kiri",
"Cut row": "Potong paris",
"Delete column": "Hapus kolom",
"Center": "Tengah",
"Merge cells": "Gabung sel",
"Insert template": "Sisip templat",
"Templates": "Templat",
"Background color": "Warna latar",
"Text color": "Warna teks",
"Show blocks": "Tampilkan blok",
"Show invisible characters": "Tampilkan karakter tak terlihat",
"Words: {0}": "Kata: {0}",
"Insert": "Sisip",
"File": "Berkas",
"Edit": "Edit",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Area Teks Kaya. Tekan ALT-F9 untuk menu. Tekan ALT-F10 untuk toolbar. Tekan ALT-0 unuk bantuan",
"Tools": "Alat",
"View": "Pandangan",
"Table": "Tabel",
"Format": "Format"
});