tinymce.addI18n('nl',{
"Address": "Adres",
"Add to Dictionary": "Toevoegen aan woordenboek",
"Advanced": "Geavanceerd",
"Align center": "Centreren",
"Align left": "Links uitlijnen",
"Alignment": "Uitlijning",
"Align right": "Rechts uitlijnen",
"Alternative source": "Alternatieve bron",
"Anchor": "Anker",
"Apply": "Toepassen",
"Anchors": "Ankers",
"Author": "Auteur",
"B": "B",
"Back": "Terug",
"Background color": "Achtergrondkleur",
"Blocks": "Blokken",
"Blockquote": "Citaat",
"Body": "Inhoud",
"Bold": "Vet",
"Border": "Rand",
"Border color": "Randkleur",
"Bottom": "Onder",
"Brightness": "Helderheid",
"Bullet list": "Opsommingstekens",
"Cancel": "Annuleren",
"Caption": "Onderschrift",
"Cell": "Cel",
"Cell padding": "Celpadding",
"Cell properties": "Celeigenschappen",
"Cell spacing": "Celruimte",
"Cell type": "Celtype",
"Center": "Centreren",
"Circle": "Cirkel",
"Clear formatting": "Opmaak wissen",
"Close": "Sluiten",
"Code": "Codering",
"Color": "Kleur",
"Color levels": "Kleurniveau's",
"Cols": "Kolommen",
"Column": "Kolom",
"Column group": "Kolomgroep",
"Constrain proportions": "Verhoudingen behouden",
"Contrast": "Contrast",
"Copy": "Kopi\u00ebren",
"Copy row": "Kopieer rij",
"Could not find the specified string.": "Geen resultaten gevonden.",
"Crop": "Uitsnijden",
"Custom...": "Aangepast...",
"Custom color": "Aangepaste kleur",
"Cut": "Knippen",
"Cut row": "Rij knippen",
"Decrease indent": "Inspringen verkleinen",
"Default": "Standaard",
"Delete column": "Kolom verwijderen",
"Delete row": "Rij verwijderen",
"Delete table": "Tabel verwijderen",
"Description": "Beschrijving",
"Dimensions": "Afmetingen",
"Disc": "Disc",
"Div": "Div",
"Document properties": "Documenteigenschappen",
"Edit": "Bewerken",
"Edit image": "Afbeelding bewerken",
"Embed": "Insluiten",
"Emoticons": "Emoticons",
"Encoding": "Codering",
"File": "Bestand",
"Find": "Zoeken",
"Find and replace": "Zoek en vervang",
"Finish": "Einde",
"Flip vertically": "Verticaal omdraaien",
"Flip horizontally": "Horizontaal omdraaien",
"Font Family": "Lettertype",
"Font Sizes": "Lettergrootte",
"Footer": "Voettekst",
"Format": "Opmaak",
"Formats": "Opmaak",
"Fullscreen": "Volledig scherm",
"G": "G",
"Gamma": "Gamma",
"General": "Algemeen",
"H Align": "H uitlijning",
"Header": "Kop",
"Header 1": "Kop 1",
"Header 2": "Kop 2",
"Header 3": "Kop 3",
"Header 4": "Kop 4",
"Header 5": "Kop 5",
"Header 6": "Kop 6",
"Header cell": "Kopcel",
"Headers": "Koppen",
"Heading 1": "Kop 1",
"Heading 2": "Kop 2",
"Heading 3": "Kop 3",
"Heading 4": "Kop 4",
"Heading 5": "Kop 5",
"Heading 6": "Kop 6",
"Headings": "Koppen",
"Height": "hoogte",
"Horizontal line": "Horizontale lijn",
"Horizontal space": "Horizontale ruimte",
"Image description": "Beschrijving afbeelding",
"Image options": "Afbeeldingsopties",
"Ignore": "Negeren",
"Ignore all": "Alles negeren",
"Inline": "Inlijn",
"Increase indent": "Inspringen vergroten",
"Insert": "Invoegen",
"Insert column after": "Kolom erna invoegen",
"Insert column before": "Kolom ervoor invoegen",
"Insert date\/time": "Datum\/tijd invoegen",
"Insert\/Edit code sample": "Invoegen\/bewerken codevoorbeeld",
"Insert\/edit image": "Invoegen\/bewerken afbeelding",
"Insert\/edit link": "Invoegen\/bewerken link",
"Insert\/edit video": "Invoegen\/bewerken video",
"Insert image": "Afbeelding invoegen",
"Insert link": "Link invoegen",
"Insert nonbreaking space": "Vaste spatie invoegen",
"Insert row after": "Rij erna invoegen",
"Insert row before": "Rij ervoor invoegen",
"Insert table": "Tabel invoegen",
"Insert template": "Sjabloon invoegen",
"Insert Time": "Tijd invoegen",
"Insert video": "Video invoegen",
"Invert": "Omkeren",
"Italic": "Schuin",
"Justify": "Uitvullen",
"Keywords": "Trefwoorden",
"Language": "Language",
"Left": "Links",
"Left to right": "Links naar rechts",
"Lower Alpha": "Alfa (klein)",
"Lower Greek": "Griekse letters (klein)",
"Lower Roman": "Romeinse letters (klein)",
"Match case": "Overeenkomen ",
"Merge cells": "Cellen samenvoegen",
"Middle": "Midden",
"Name": "Naam",
"New document": "Nieuw document",
"New window": "Nieuw venster",
"Next": "Volgende",
"No color": "No color",
"Nonbreaking space": "Vaste spatie invoegen",
"None": "Geen",
"Numbered list": "Nummering",
"Ok": "Ok",
"Orientation": "Ori\u00ebntatie",
"Page break": "Nieuwe pagina",
"Paragraph": "Paragraaf",
"Paste": "Plakken",
"Paste as text": "Plakken als tekst",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Plakken als platte tekst is ingesteld. Tekst wordt ingevoegd zonder opmaak tot deze optie uitgeschakeld wordt.",
"Paste row after": "Rij erna invoegen",
"Paste row before": "Rij ervoor invoegen",
"Paste your embed code below:": "Plak de insluitcode hieronder:",
"Poster": "Poster",
"Pre": "Pre",
"Preformatted": "Voorgeformateerd",
"Prev": "Vorige",
"Preview": "Voorbeeld",
"Print": "Printen",
"R": "R",
"Redo": "Opnieuw",
"Remove link": "Link verwijderen",
"Replace": "Vervangen",
"Replace all": "Alles vervangen",
"Replace with": "Vervangen door",
"Resize": "Verkleinen",
"Restore last draft": "Herstellen naar vorige concept.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Opgemaakte tekstgebied. Druk op ALT-F9 voor het menu. Druk op ALT-F10 voor de werkbalk. Druk op ALT-0 voor de help.",
"Right": "Rechts",
"Right to left": "Rechts naar links",
"Robots": "Robots",
"Rotate clockwise": "Rechtsom draaien",
"Rotate counterclockwise": "Linksom draaien",
"Row": "Rij",
"Row group": "Rijgroep",
"Row properties": "Rij-eigenschappen",
"Rows": "Rijen",
"Row type": "Rijtype",
"Save": "Opslaan",
"Scope": "Reikwijdte",
"Select all": "Alles selecteren",
"Sharpen": "Scherper",
"Show blocks": "Toon blokken",
"Show invisible characters": "Toon onzichtbare tekens",
"Square": "Vierkant",
"Strikethrough": "Doorhalen",
"Special character": "Speciale tekens",
"Spellcheck": "Spellingscontrole",
"Split cell": "Cel splitsen",
"Source": "URL",
"Source code": "Broncode",
"Style": "Stijl",
"Subscript": "Subscript",
"Superscript": "Superscript",
"Table": "Tabel",
"Table properties": "Tabeleigenschappen",
"Target": "Doel",
"Templates": "Sjabloon",
"Text color": "Tekstkleur",
"Text to display": "Tekst om weer te geven",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "De URL die u heeft ingevuld lijkt een e-mailadres te zijn. Wilt u de benodigde mailto: als voorvoegsel toevoegen?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "De URL die u heeft ingevuld lijkt een externe link te zijn. Wilt u de benodigde http:\/\/ als voorvoegsel toevoegen?",
"Title": "Titel",
"Toggle blockquote": "Schakelen citaat",
"Tools": "Gereedschap",
"Top": "Boven",
"Underline": "Onderstrepen",
"Undo": "Ongedaan maken",
"Upper Alpha": "Alfa (groot)",
"Upper Roman": "Romeinse letters (groot)",
"Url": "URL",
"V Align": "V uitlijning",
"Vertical space": "Verticale ruimte",
"View": "Weergave",
"Visual aids": "Hulpmiddelen",
"Width": "Breedte",
"Whole words": "Hele woorden",
"Words: {0}": "Woorden: {0}",
"You have unsaved changes are you sure you want to navigate away?": "Niet alle wijzigingen zijn opgeslagen, weet u zeker dat u de pagina wilt verlaten?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Uw browser ondersteunt de toegang tot het klembord niet. Gebruik de sneltoetsen ctrl+X\/C\/V.",
"Zoom in": "Inzoomen",
"Zoom out": "Uitzomen"
});