tinymce.addI18n('sk',{
"Cut": "Vystrihnúť",
"Heading 5": "Nadpis 5",
"Header 2": "Nadpis 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Váš prehliadač nepodporuje priamy prístup do schránky. Použite, prosím, klávesové skratky Ctrl+X\/C\/V.",
"Heading 4": "Nadpis 4",
"Div": "Div (blok)",
"Heading 2": "Nadpis 2",
"Paste": "Vložiť",
"Close": "Zatvoriť",
"Font Family": "Druh písma",
"Pre": "Pre (predvormátovanie)",
"Align right": "Zarovnať vpravo",
"New document": "Nový dokument",
"Blockquote": "Citát",
"Numbered list": "Číslovaný zoznam",
"Heading 1": "Nadpis 1",
"Headings": "Nadpisy",
"Increase indent": "Zväčšiť odsadenie",
"Formats": "Formáty",
"Headers": "Nadpisy",
"Select all": "Vybrať všetko",
"Header 3": "Nadpis 3",
"Blocks": "Blokové zobrazenie (block)",
"Undo": "Späť",
"Strikethrough": "Prečiarknuté",
"Bullet list": "Odrážky",
"Header 1": "Nadpis 1",
"Superscript": "Horný index",
"Clear formatting": "Vymazať formátovanie",
"Font Sizes": "Veľkosť písma",
"Subscript": "Dolný index",
"Header 6": "Nadpis 6",
"Redo": "Znova",
"Paragraph": "Odstavec",
"Ok": "OK",
"Bold": "Tučné",
"Code": "Kód (code)",
"Italic": "Kurzíva",
"Align center": "Zarovnať na stred",
"Header 5": "Nadpis 5",
"Heading 6": "Nadpis 6",
"Heading 3": "Nadpis 3",
"Decrease indent": "Zmenšiť odsadenie",
"Header 4": "Nadpis 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Vkladanie je teraz zapnuté v režime čistého textu. Pokiľa nebude táto voľba vypnutá, bude všetok obsah vkladaný ako čistý text.",
"Underline": "Podčiarknuté",
"Cancel": "Zrušiť",
"Justify": "Zarovnať do bloku",
"Inline": "Riadkové zobrazenie (inline)",
"Copy": "Kopírovať",
"Align left": "Zarovnať vľavo",
"Visual aids": "Vizuálne pomôcky",
"Lower Greek": "Malé písmená",
"Square": "Štvorec",
"Default": "Východzie",
"Lower Alpha": "Normálne číslovanie",
"Circle": "Kruh",
"Disc": "Bod",
"Upper Alpha": "Veľké písmená",
"Upper Roman": "Veľké rímske číslice",
"Lower Roman": "Malé rímske číslice",
"Name": "Názov",
"Anchor": "Kotva",
"You have unsaved changes are you sure you want to navigate away?": "Máte neuložené zmeny. Skutočne chcete stránku opustiť?",
"Restore last draft": "Obnoviť ostatný koncept",
"Special character": "Špeciálny znak",
"Source code": "Zdrojový kód",
"Right to left": "Zprava doľava",
"Left to right": "Zľava doprava",
"Emoticons": "Emotikony",
"Robots": "Roboti",
"Document properties": "Vlastnosti dokumentu",
"Title": "Názov",
"Keywords": "Kľúčové slová",
"Encoding": "Kódovanie",
"Description": "Popis",
"Author": "Autor",
"Fullscreen": "Na celú obrazovku",
"Horizontal line": "Vodorovná čiara",
"Horizontal space": "Horizontálna medzera",
"Insert\/edit image": "Vložiť \/ upraviť obrázok",
"General": "Všeobecné",
"Advanced": "Rozšírené",
"Source": "Zdroj",
"Border": "Rámček",
"Constrain proportions": "Zachovať proporcie",
"Vertical space": "Vertikálna medzera",
"Image description": "Popis obrázku",
"Style": "Štýl",
"Dimensions": "Rozmery",
"Insert image": "Vložiť obrázok",
"Insert date\/time": "Vložiť dátum \/ čas",
"Remove link": "Odstrániť odkaz",
"Url": "URL",
"Text to display": "Zobrazený text",
"Anchors": "Kotvy",
"Insert link": "Vložiť odkaz",
"New window": "Nové okno",
"None": "Žiadne",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Zadaná URL adresa vyzerá ako odkaz na inú webovú stránku. Chcete doplniť povinný prefix http:\/\/?",
"Target": "Cieľ",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Zadaná URL vyzeraá ako e-mailová adresa. Chcete doplniť povinný prefix mailto:?",
"Insert\/edit link": "Vložiť \/ upraviť odkaz",
"Insert\/edit video": "Vložiť \/ upraviť video",
"Poster": "Ukážka",
"Alternative source": "Alternatívny zdroj",
"Paste your embed code below:": "Nižšie vložte zdrojový kód:",
"Insert video": "Vložiť video",
"Embed": "Vložiť",
"Nonbreaking space": "Pevná medzera",
"Page break": "Koniec stránky",
"Paste as text": "Vložiť ako čistý text",
"Preview": "Ukážka",
"Print": "Tlačiť",
"Save": "Uložiť",
"Could not find the specified string.": "Zadaný reťazec nebol nájdený.",
"Replace": "Nahradiť",
"Next": "Ďalší",
"Whole words": "Len celé slová",
"Find and replace": "Nájsť a nahradiť",
"Replace with": "Nahradiť za",
"Find": "Nájsť",
"Replace all": "Nahradiť všetko",
"Match case": "Rozlišovať malé a veľké písmená",
"Prev": "Predchádzajúci",
"Spellcheck": "Kontrola pravopisu",
"Finish": "Ukončiť",
"Ignore all": "Ignorovať všetko",
"Ignore": "Ignorovať",
"Add to Dictionary": "Pridať do slovníka",
"Insert row before": "Vložiť riadok nad",
"Rows": "Riadky",
"Height": "Výška",
"Paste row after": "Vložiť riadok pod",
"Alignment": "Zarovnanie",
"Column group": "Skupina stĺpcov",
"Row": "Riadok",
"Insert column before": "Vložiť stĺpec vľavo",
"Split cell": "Rozdeliť bunky",
"Cell padding": "Vnútorný okraj buniek",
"Cell spacing": "Vonkajší okraj buniek",
"Row type": "Typ riadku",
"Insert table": "Vložiť tabuľku",
"Body": "Telo",
"Caption": "Nadpis",
"Footer": "Pätička",
"Delete row": "Vymazať riadok",
"Paste row before": "Vložiť riadok nad",
"Scope": "Rozsah",
"Delete table": "Vymazať tabuľku",
"H Align": "Horizontálne zarovananie",
"Top": "Hore",
"Header cell": "Záhlavie bunky",
"Column": "Stĺpec",
"Row group": "Skupina riadkov",
"Cell": "Bunka",
"Middle": "V strede",
"Cell type": "Typ bunky",
"Copy row": "Kopírovať riadok",
"Row properties": "Vlastnosti riadku",
"Table properties": "Vlastnosti tabuľky",
"Bottom": "Dole",
"V Align": "Vertikálne zarovnanie",
"Header": "Hlavička",
"Right": "Vpravo",
"Insert column after": "Vložiť stĺpec vpravo",
"Cols": "Stĺpcov",
"Insert row after": "Vložiť riadok pod",
"Width": "Šírka",
"Cell properties": "Vlastnosti bunky",
"Left": "Vľavo",
"Cut row": "Vystrihnúť riadok",
"Delete column": "Vymazať stĺpec",
"Center": "Na stred",
"Merge cells": "Zlúčiť bunky",
"Insert template": "Vloži?ť šablónu",
"Templates": "Šablóny",
"Background color": "Farba pozadia",
"Text color": "Farba písma",
"Show blocks": "Ukázať bloky",
"Show invisible characters": "Zobraziť špeciálne znaky",
"Words: {0}": "Počet slov: {0}",
"Insert": "Vložiť",
"File": "Súbor",
"Edit": "Úpravy",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Editor. Stlačte ALT-F9 pre menu, ALT-F10 pre nástrojovú lištu a ALT-0 pre nápovedu.",
"Tools": "Nástroje",
"View": "Zobraziť",
"Table": "Tabuľka",
"Format": "Formát",
"Border color": "Farba okrajov",
"Color": "Farba",
"Custom...": "Vlastná...",
"Custom color": "Vlastná farba",
"No color": "Bez farby"
});