tinymce.addI18n('sw',{
"Cut": "Kata",
"Heading 5": "Kichwa 5",
"Header 2": "Kijajuu 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Kisakuzi chako hakiungwi mkono kwa kupata moja kwa moja clipboard. Tafadhali tumia njia fupi ya kinanda taipu, kama Ctrl+X\/C\/V.",
"Heading 4": "Kichwa 4",
"Div": "Div",
"Heading 2": "Kichwa 2",
"Paste": "Bandika",
"Close": "Funga",
"Font Family": "Jamii ya fonti",
"Pre": "Iliofomatiwa",
"Align right": "Panga kulia",
"New document": "Hati mpya",
"Blockquote": "Nukuu",
"Numbered list": "Orodha ya idadi",
"Heading 1": "Kichwa 1",
"Headings": "Vichwa",
"Increase indent": "Ongeza jongezo",
"Formats": "Formati",
"Headers": "Vijajuu",
"Select all": "Chagua zote",
"Header 3": "Kijajuu 3",
"Blocks": "Matofali",
"Undo": "Tengua",
"Strikethrough": "Mkato",
"Bullet list": "Orodha ya vidato",
"Header 1": "Kijajuu 1",
"Superscript": "Weka juu",
"Clear formatting": "Safisha fomati",
"Font Sizes": "Ukubwa wa fonti",
"Subscript": "Weka chini",
"Header 6": "Kijajuu 6",
"Redo": "Fanya tena",
"Paragraph": "Aya",
"Ok": "Ok",
"Bold": "Nene",
"Code": "Kodi",
"Italic": "Italiki",
"Align center": "Panga katikati",
"Heading 6": "Kichwa 6",
"Heading 3": "Kichwa 3",
"Header 5": "Kijajuu 5",
"Decrease indent": "Punguza jongezo",
"Header 4": "Kijajuu 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Bandika sasa modi ya maandishi rahisi. Yaliyomo yatabandikwa kama maandishi rahisi mpaka utakapo zima chaguo hili.",
"Underline": "Pigia mstari wa chini",
"Cancel": "Ghairi",
"Justify": "Panga pande zote",
"Inline": "Inline",
"Copy": "Nakili",
"Align left": "Panga kushoto",
"Visual aids": "Misaada ya kuona",
"Lower Greek": "Herufi ndogo za kigiriki",
"Square": "Mraba",
"Default": "Difoti",
"Lower Alpha": "Herufi ndogo",
"Circle": "Duara",
"Disc": "Nukta",
"Upper Alpha": "Herufi kubwa",
"Upper Roman": "Herufi kubwa za kirumi",
"Lower Roman": "Herufi ndogo za kirumi",
"Name": "Jina",
"Anchor": "Nanga",
"You have unsaved changes are you sure you want to navigate away?": "Uko na mabadilisho ambayo hujayahifadhi. Una hakika unataka kuwacha?",
"Restore last draft": "Regesha rasimu ya mwisho",
"Special character": "Herufi maalum",
"Source code": "Kodi ya chanzo",
"B": "B",
"R": "R",
"G": "G",
"Color": "Rangi",
"Right to left": "Kulia-kushoto",
"Left to right": "Kushoto-kulia",
"Emoticons": "Emoticons",
"Robots": "Roboti",
"Document properties": "Mali za hati",
"Title": "Kichwa",
"Keywords": "Maneno muhimu",
"Encoding": "Mwandiko",
"Description": "Fafanuo",
"Author": "Mwandishi",
"Fullscreen": "Skrini kamili",
"Horizontal line": "Mstari wa usawa",
"Horizontal space": "Nafasi ya usawa",
"Insert\/edit image": "Ingiza\/hariri picha",
"General": "Ujumla",
"Advanced": "Hali ya juu",
"Source": "Chanzo",
"Border": "Mipaka",
"Constrain proportions": "Lazimisha uwiano",
"Vertical space": "Nafasi ya wima",
"Image description": "Fafanuo la picha",
"Style": "Mtindo",
"Dimensions": "Kipimo",
"Insert image": "Ingiza picha",
"Zoom in": "Au kuvuta ndani",
"Contrast": "Tofauti ya kirangi",
"Back": "Nyuma",
"Gamma": "Gamma",
"Flip horizontally": "Geuza usawa",
"Resize": "Rekebisha ukubwa",
"Sharpen": "Kunoa sawa",
"Zoom out": "Au kuvuta nje",
"Image options": "Machaguo ya picha",
"Apply": "Omba",
"Brightness": "Mwangaza",
"Rotate clockwise": "Zungusha kulia",
"Rotate counterclockwise": "Zungusha kushoto",
"Edit image": "Hariri picha",
"Color levels": "Viwango vya rangi",
"Crop": "Kata",
"Orientation": "Rekebisho",
"Flip vertically": "Geuza wima",
"Invert": "Weka kinyume",
"Insert date\/time": "Ingiza tarehe\/saa",
"Remove link": "Ondoa kiungo",
"Url": "URL",
"Text to display": "Maandishi ya kuonyesha",
"Anchors": "Mananga",
"Insert link": "Ingiza kiungo",
"New window": "Dirisha jipya",
"None": "Hakuna",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "URL ulioingiza unaonekana ni kama kiungo cha nje. Unataka kuongeza prefix inayohitajika, ambayo ni http:\/\/ ?",
"Target": "Lengo",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "URL ulioingiza unaonekana ni kama anwani ya barua pepe. Unataka kuongeza prefix inayohitajika, ambayo ni mailto: ?",
"Insert\/edit link": "Ingiza\/hariri kiungo",
"Insert\/edit video": "Ingiza\/hariri video",
"Poster": "Bando",
"Alternative source": "Chanzo cha mbadala",
"Paste your embed code below:": "Bandika kodi yako ya embed hapo chini:",
"Insert video": "Ingiza video",
"Embed": "Embed",
"Nonbreaking space": "Nafasi isiyovunjika",
"Page break": "Mvunja wa ukurasa",
"Paste as text": "Bandika kama maandishi",
"Preview": "Hakikisho",
"Print": "Chapa",
"Save": "Hifadhi",
"Could not find the specified string.": "Haikuweza kupata sharti lililoelezwa.",
"Replace": "Chukua",
"Next": "Ifuatayo",
"Whole words": "Maneno kamili",
"Find and replace": "Pata na chukua",
"Replace with": "Chukua na",
"Find": "Pata",
"Replace all": "Chukua zote",
"Match case": "Tahadhari herufi ndogo/kubwa",
"Prev": "Iliopita",
"Spellcheck": "Ukaguzi wa maendelezo",
"Finish": "Maliza",
"Ignore all": "Puuza zote",
"Ignore": "Puuza",
"Add to Dictionary": "Ongeza kwa kamusi",
"Insert row before": "Ingiza mstari kabla",
"Rows": "Mistari",
"Height": "Urefu",
"Paste row after": "Ingiza mstari baada",
"Alignment": "Mpangilio",
"Border color": "Rangi ya mpaka",
"Column group": "Kikundi cha safu",
"Row": "Mstari",
"Insert column before": "Ingiza safu kabla",
"Split cell": "Gawanya kiini",
"Cell padding": "Pedi ya kiini",
"Cell spacing": "Nafasi ya kiini",
"Row type": "Aina ya mstari",
"Insert table": "Ingiza jedwali",
"Body": "Mwili",
"Caption": "Maelezo mafupi",
"Footer": "Kijachini",
"Delete row": "Futa mstari",
"Paste row before": "Bandika mstari kabla",
"Scope": "Wigo",
"Delete table": "Futa jedwali",
"H Align": "Panga H",
"Top": "Juu",
"Header cell": "Kiini cha kijajuu",
"Column": "Safu",
"Row group": "Mstari wa kikundi",
"Cell": "Mstari",
"Middle": "Katikati",
"Cell type": "Aina ya kiini",
"Copy row": "Nakili mstari",
"Row properties": "Mali ya mstari",
"Table properties": "Mali ya jedwali",
"Bottom": "Chini",
"V Align": "Panga V",
"Header": "Kijajuu",
"Right": "Kulia",
"Insert column after": "Ingiza safu baada",
"Cols": "Masafu",
"Insert row after": "Ingiza mstari baada",
"Width": "Upana",
"Cell properties": "Malli ya kiini",
"Left": "Kushoto",
"Cut row": "Kata mstari",
"Delete column": "Futa safu",
"Center": "Katikati",
"Merge cells": "Unganisha viini",
"Insert template": "Ingiza templeti",
"Templates": "Templeti",
"Background color": "Rangi ya usuli",
"Custom...": "Desturi...",
"Custom color": "Rangi ya desturi",
"No color": "Hakuna rangi",
"Text color": "Rangi ya maandishi",
"Show blocks": "Onyesha matofali",
"Show invisible characters": "Onyesha herufi isiyoonekana",
"Words: {0}": "Maneno: {0}",
"Insert": "Ingiza",
"File": "Faili",
"Edit": "Hariri",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Eneo la maandishi tajiri. Bofya ALT-F9 kwa menyu. Bofya ALT-F10 kwa upauzana. Bofya ALT-0 kwa usaidizi.",
"Tools": "Zana",
"View": "Mtazamo",
"Table": "Jedwali",
"Format": "Formati"
});