<?php
/**
 * @package    Joomla.UnitTest
 *
 * @copyright  Copyright (C) 2005 - 2014 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

/**
 * Test class for JCacheStorageHelper.
 * Generated by PHPUnit on 2011-10-26 at 19:38:58.
 *
 * @package     Joomla.UnitTest
 * @subpackage  Cache
 * @since       11.1
 */
class JCacheStorageHelperTest extends PHPUnit_Framework_TestCase
{
	/**
	 * Test...
	 *
	 * @todo Implement testUpdateSize().
	 *
	 * @return void
	 */
	public function testUpdateSize()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
