<?php
/**
 * @package    Joomla.UnitTest
 *
 * @copyright  Copyright (C) 2005 - 2013 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/joomla/document/feed/feed.php';

/**
 * Test class for JFeedEnclosure.
 * Generated by PHPUnit on 2011-10-26 at 19:36:22.
 *
 * @package     Joomla.UnitTest
 * @subpackage  Document
 * @since       11.1
 */
class JFeedEnclosureTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var JFeedEnclosure
	 */
	protected $object;

	/**
	 * Test...
	 *
	 * @todo Decide how to Implement.
	 *
	 * @return void
	 */
	public function testDummy()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete('This test has not been implemented yet.');
	}
}
