(function(){CodeMirror.showHint=function(e,g,h){if(e.somethingSelected()){return;}if(g==null){g=e.getHelper(e.getCursor(),"hint");}if(g==null){return;}if(e.state.completionActive){e.state.completionActive.close();
}var f=e.state.completionActive=new d(e,g,h||{});CodeMirror.signal(e,"startCompletion",e);if(f.options.async){g(e,function(i){f.showHints(i);},f.options);
}else{return f.showHints(g(e,f.options));}};function d(e,f,g){this.cm=e;this.getHints=f;this.options=g;this.widget=this.onClose=null;}d.prototype={close:function(){if(!this.active()){return;
}this.cm.state.completionActive=null;if(this.widget){this.widget.close();}if(this.onClose){this.onClose();}CodeMirror.signal(this.cm,"endCompletion",this.cm);
},active:function(){return this.cm.state.completionActive==this;},pick:function(g,f){var e=g.list[f];if(e.hint){e.hint(this.cm,g,e);}else{this.cm.replaceRange(a(e),g.from,g.to);
}this.close();},showHints:function(e){if(!e||!e.list.length||!this.active()){return this.close();}if(this.options.completeSingle!=false&&e.list.length==1){this.pick(e,0);
}else{this.showWidget(e);}},showWidget:function(j){this.widget=new c(this,j);CodeMirror.signal(j,"shown");var n=null,g=this,f;var o=this.options.closeCharacters||/[\s()\[\]{};:>,]/;
var l=this.cm.getCursor(),k=this.cm.getLine(l.line).length;function i(){if(f){return;}f=true;g.close();g.cm.off("cursorActivity",e);if(j){CodeMirror.signal(j,"close");
}}function h(){if(f){return;}CodeMirror.signal(j,"update");if(g.options.async){g.getHints(g.cm,m,g.options);}else{m(g.getHints(g.cm,g.options));}}function m(p){j=p;
if(f){return;}if(!j||!j.list.length){return i();}g.widget=new c(g,j);}function e(){clearTimeout(n);var q=g.cm.getCursor(),p=g.cm.getLine(q.line);if(q.line!=l.line||p.length-q.ch!=k-l.ch||q.ch<l.ch||g.cm.somethingSelected()||(q.ch&&o.test(p.charAt(q.ch-1)))){g.close();
}else{n=setTimeout(h,170);if(g.widget){g.widget.close();}}}this.cm.on("cursorActivity",e);this.onClose=i;}};function a(e){if(typeof e=="string"){return e;
}else{return e.text;}}function b(h,j){var e={Up:function(){j.moveFocus(-1);},Down:function(){j.moveFocus(1);},PageUp:function(){j.moveFocus(-j.menuSize());
},PageDown:function(){j.moveFocus(j.menuSize());},Home:function(){j.setFocus(0);},End:function(){j.setFocus(j.length);},Enter:j.pick,Tab:j.pick,Esc:j.close};
var g=h.customKeys?{}:e;function f(k,m){var l;if(typeof m!="string"){l=function(n){return m(n,j);};}else{if(e.hasOwnProperty(m)){l=e[m];}else{l=m;}}g[k]=l;
}if(h.customKeys){for(var i in h.customKeys){if(h.customKeys.hasOwnProperty(i)){f(i,h.customKeys[i]);}}}if(h.extraKeys){for(var i in h.extraKeys){if(h.extraKeys.hasOwnProperty(i)){f(i,h.extraKeys[i]);
}}}return g;}function c(r,B){this.completion=r;this.data=B;var j=this,n=r.cm,h=r.options;var y=this.hints=document.createElement("ul");y.className="CodeMirror-hints";
this.selectedHint=0;var m=B.list;for(var A=0;A<m.length;++A){var g=y.appendChild(document.createElement("li")),f=m[A];var e="CodeMirror-hint"+(A?"":" CodeMirror-hint-active");
if(f.className!=null){e=f.className+" "+e;}g.className=e;if(f.render){f.render(g,B,f);}else{g.appendChild(document.createTextNode(f.displayText||a(f)));
}g.hintId=A;}var l=n.cursorCoords(h.alignWithWord!==false?B.from:null);var k=l.left,v=l.bottom,t=true;y.style.left=k+"px";y.style.top=v+"px";var o=window.innerWidth||Math.max(document.body.offsetWidth,document.documentElement.offsetWidth);
var z=window.innerHeight||Math.max(document.body.offsetHeight,document.documentElement.offsetHeight);var p=y.getBoundingClientRect();var s=p.right-o,q=p.bottom-z;
if(s>0){if(p.right-p.left>o){y.style.width=(o-5)+"px";s-=(p.right-p.left)-o;}y.style.left=(k=l.left-s)+"px";}if(q>0){var w=p.bottom-p.top;if(p.top-(l.bottom-l.top)-w>0){q=w+(l.bottom-l.top);
t=false;}else{if(w>z){y.style.height=(z-5)+"px";q-=w-z;}}y.style.top=(v=l.bottom-q)+"px";}(h.container||document.body).appendChild(y);n.addKeyMap(this.keyMap=b(h,{moveFocus:function(i){j.changeActive(j.selectedHint+i);
},setFocus:function(i){j.changeActive(i);},menuSize:function(){return j.screenAmount();},length:m.length,close:function(){r.close();},pick:function(){j.pick();
}}));if(h.closeOnUnfocus!==false){var x;n.on("blur",this.onBlur=function(){x=setTimeout(function(){r.close();},100);});n.on("focus",this.onFocus=function(){clearTimeout(x);
});}var u=n.getScrollInfo();n.on("scroll",this.onScroll=function(){var E=n.getScrollInfo(),D=n.getWrapperElement().getBoundingClientRect();var C=v+u.top-E.top;
var i=C-(window.pageYOffset||(document.documentElement||document.body).scrollTop);if(!t){i+=y.offsetHeight;}if(i<=D.top||i>=D.bottom){return r.close();
}y.style.top=C+"px";y.style.left=(k+u.left-E.left)+"px";});CodeMirror.on(y,"dblclick",function(C){var i=C.target||C.srcElement;if(i.hintId!=null){j.changeActive(i.hintId);
j.pick();}});CodeMirror.on(y,"click",function(C){var i=C.target||C.srcElement;if(i.hintId!=null){j.changeActive(i.hintId);}});CodeMirror.on(y,"mousedown",function(){setTimeout(function(){n.focus();
},20);});CodeMirror.signal(B,"select",m[0],y.firstChild);return true;}c.prototype={close:function(){if(this.completion.widget!=this){return;}this.completion.widget=null;
this.hints.parentNode.removeChild(this.hints);this.completion.cm.removeKeyMap(this.keyMap);var e=this.completion.cm;if(this.completion.options.closeOnUnfocus!==false){e.off("blur",this.onBlur);
e.off("focus",this.onFocus);}e.off("scroll",this.onScroll);},pick:function(){this.completion.pick(this.data,this.selectedHint);},changeActive:function(e){e=Math.max(0,Math.min(e,this.data.list.length-1));
if(this.selectedHint==e){return;}var f=this.hints.childNodes[this.selectedHint];f.className=f.className.replace(" CodeMirror-hint-active","");f=this.hints.childNodes[this.selectedHint=e];
f.className+=" CodeMirror-hint-active";if(f.offsetTop<this.hints.scrollTop){this.hints.scrollTop=f.offsetTop-3;}else{if(f.offsetTop+f.offsetHeight>this.hints.scrollTop+this.hints.clientHeight){this.hints.scrollTop=f.offsetTop+f.offsetHeight-this.hints.clientHeight+3;
}}CodeMirror.signal(this.data,"select",this.data.list[this.selectedHint],f);},screenAmount:function(){return Math.floor(this.hints.clientHeight/this.hints.firstChild.offsetHeight)||1;
}};})();