<?php
/**
 * @version		$Id$
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

require_once JPATH_BASE.'/libraries/joomla/form/fields/combo.php';
/**
 * Test class for JFormFieldCombo.
 * Generated by PHPUnit on 2009-11-08 at 21:16:27.
 */
class JFormFieldComboTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var JFormFieldCombo
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new JFormFieldCombo;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * Empty test to prevent warnings.
	 */
	public function testNothing() {
		// Remove the following lines when you implement this test.
		$this->markTestSkipped('This test does nothing at all.');
	}
}
?>
