// French lang variables by Laurent Dran
// Modifié par Normand Lamoureux le 2005-11-12

tinyMCE.addToLang('advlink',{
general_tab : 'Général',
popup_tab : 'Pop-up',
events_tab : 'Événements',
advanced_tab : 'Avancé',
general_props : 'Propriétés générales',
popup_props : 'Propriétés du pop-up',
event_props : 'Événements',
advanced_props : 'Propriétés avancées',
popup_opts : 'Options',
anchor_names : 'Ancres',
target_same : 'Ovrir dans la même fenêtre/cadre',
target_parent : 'Ouvrir dans la fenêtre/cadre parent',
target_top : 'Ouvrir dans la fenêtre principale',
target_blank : 'Ouvrir dans une nouvelle fenêtre',
popup : 'Pop-up Javascript',
popup_url : 'URL du pop-up',
popup_name : 'Nom de la fenêtre',
popup_return : 'Insérer \'return false;\'',
popup_scrollbars : 'Montrer les barres de défilement',
popup_statusbar : 'Montrer la barre de statut',
popup_toolbar : 'Montrer la barre d\'outils',
popup_menubar : 'Montrer la barre de menus',
popup_location : 'Montrer la barre de titre',
popup_resizable : 'Permettre le redimensionnement',
popup_dependent : 'Dépendent (Mozilla/Firefox seulement)',
popup_size : 'Taille',
popup_position : 'Position (X/Y)',
id : 'Id',
style: 'Style en ligne',
classes : 'Classe CSS',
target_name : 'Nom de la cible',
langdir : 'Sens d\'écriture',
target_langcode : 'Code de langue de la cible',
langcode : 'Code de langue du libellé',
encoding : 'Encodage de la cible',
mime : 'Type MIME de la cible',
rel : 'Relation de la page vers la cible',
rev : 'Relation de la cible vers la page',
tabindex : 'Attribut tabindex',
accesskey : 'Attribut accesskey',
ltr : 'Vers la droite',
rtl : 'Vers la gauche'
});
