<?php
require_once 'PHPUnit/Framework.php';

require_once JPATH_BASE.'/libraries/joomla/html/html/jgrid.php';

/**
 * Test class for JHtmlJGrid.
 * Generated by PHPUnit on 2009-10-27 at 16:09:49.
 */
class JHtmlJGridTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JHtmlJGrid
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
//		$this->object = new JHtmlJGrid;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testPublished().
	 */
	public function testPublished()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPublishedOptions().
	 */
	public function testPublishedOptions()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckedout().
	 */
	public function testCheckedout()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}