services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
      - "9003:9003" # Add Xdebug port
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: examplepass
      JOOMLA_DB_NAME: joomla_db
      JOOMLA_SITE_NAME: Joomla
      JOOMLA_ADMIN_USER: Joomla Hero
      JOOMLA_ADMIN_USERNAME: joomla
      JOOMLA_ADMIN_PASSWORD: joomla@secured
      JOOMLA_ADMIN_EMAIL: joomla@example.com
    volumes:
      - ../..:/workspaces:cached
    networks:
      - joomla_network

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword # Explicitly set the root password
    volumes:
      - db:/var/lib/mysql
    networks:
      - joomla_network

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db
    networks:
      - joomla_network

volumes:
  db:


networks:
  joomla_network:
    driver: bridge
