--
-- Step 1: Convert all tables to UTF8mb4 character set with UTF8mb4_unicode_ci collation
-- except of #__finder_xxx tables, those are handled with 4.0.0-2018-07-29.sql at update.
--

ALTER TABLE `#__action_logs` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_logs_extensions` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_logs_users` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_log_config` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__assets` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__associations` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banners` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banner_clients` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banner_tracks` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__categories` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__contact_details` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_frontpage` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_rating` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_types` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__contentitem_tag_map` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__extensions` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_categories` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_groups` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_values` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__history` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__languages` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__menu` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__menu_types` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__messages` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__messages_cfg` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__modules` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__modules_menu` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__newsfeeds` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__overrider` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__postinstall_messages` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__privacy_consents` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__privacy_requests` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__redirect_links` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__schemas` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__session` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__tags` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__template_overrides` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__template_styles` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__ucm_base` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__ucm_content` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__updates` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__update_sites` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__update_sites_extensions` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__usergroups` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__users` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_keys` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_notes` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_profiles` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_usergroup_map` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__UTF8_conversion` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__viewlevels` CONVERT TO CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;

--
-- Step 2: Set collation to UTF8mb4_bin for formerly UTF8_bin collated columns
-- and for the lang_code column of the languages table
--

ALTER TABLE `#__banners` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__categories` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__contact_details` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__content` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__languages` MODIFY `lang_code` char(7) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL;
ALTER TABLE `#__menu` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL COMMENT 'The SEF alias of the menu item.';
ALTER TABLE `#__newsfeeds` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tags` MODIFY `alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__ucm_content` MODIFY `core_alias` varchar(400) CHARACTER SET UTF8mb4 COLLATE UTF8mb4_bin NOT NULL DEFAULT '';

--
-- Step 3: Set default character set and collation for all tables
--

ALTER TABLE `#__action_logs` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_logs_extensions` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_logs_users` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__action_log_config` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__assets` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__associations` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banners` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banner_clients` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__banner_tracks` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__categories` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__contact_details` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_frontpage` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_rating` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__content_types` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__contentitem_tag_map` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__extensions` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_categories` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_groups` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__fields_values` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__history` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__languages` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__menu` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__menu_types` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__messages` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__messages_cfg` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__modules` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__modules_menu` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__newsfeeds` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__overrider` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__postinstall_messages` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__privacy_consents` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__privacy_requests` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__redirect_links` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__schemas` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__session` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__tags` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__template_overrides` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__template_styles` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__ucm_base` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__ucm_content` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__updates` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__update_sites` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__update_sites_extensions` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__usergroups` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__users` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_keys` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_notes` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_profiles` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__user_usergroup_map` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__UTF8_conversion` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
ALTER TABLE `#__viewlevels` DEFAULT CHARACTER SET UTF8mb4 COLLATE UTF8mb4_unicode_ci;
