<?php
require_once 'PHPUnit/Framework.php';

require_once JPATH_BASE . '/libraries/joomla/updater/updateadapter.php';
require_once JPATH_BASE . '/libraries/joomla/updater/adapters/collection.php';

/**
 * Test class for JUpdaterCollection.
 * Generated by PHPUnit on 2009-10-26 at 22:53:40.
 */
class JUpdaterCollectionTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JUpdaterCollection
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
//		$this->object = new JUpdaterCollection;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement test_startElement().
	 */
	public function test_startElement()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_endElement().
	 */
	public function test_endElement()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFindUpdate().
	 */
	public function testFindUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}
?>
