<?php
/**
 * @package	    Joomla.UnitTest
 * @subpackage  com_finder
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license	    GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_ADMINISTRATOR . '/components/com_finder/helpers/indexer/token.php';

/**
 * Test class for FinderIndexerToken.
 * Generated by PHPUnit on 2011-10-20 at 22:39:05.
 */
class FinderIndexerTokenTest extends JoomlaTestCase
{
	/**
	 * @var FinderIndexerToken
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}
}
