<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  Categories
 *
 * @copyright   Copyright (C) 2005 - 2014 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

/**
 * Test class for JCategoryNode.
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-14 at 12:59:03.
 *
 * @package     Joomla.UnitTest
 * @subpackage  Categories
 * @since       3.2
 */
class JCategoryNodeTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JCategoryNode
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new JCategoryNode;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers JCategoryNode::setParent
	 * @todo   Implement testSetParent().
	 */
	public function testSetParent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::addChild
	 * @todo   Implement testAddChild().
	 */
	public function testAddChild()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::removeChild
	 * @todo   Implement testRemoveChild().
	 */
	public function testRemoveChild()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getChildren
	 * @todo   Implement testGetChildren().
	 */
	public function testGetChildren()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getParent
	 * @todo   Implement testGetParent().
	 */
	public function testGetParent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::hasChildren
	 * @todo   Implement testHasChildren().
	 */
	public function testHasChildren()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::hasParent
	 * @todo   Implement testHasParent().
	 */
	public function testHasParent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::setSibling
	 * @todo   Implement testSetSibling().
	 */
	public function testSetSibling()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getSibling
	 * @todo   Implement testGetSibling().
	 */
	public function testGetSibling()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getParams
	 * @todo   Implement testGetParams().
	 */
	public function testGetParams()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getMetadata
	 * @todo   Implement testGetMetadata().
	 */
	public function testGetMetadata()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getPath
	 * @todo   Implement testGetPath().
	 */
	public function testGetPath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getAuthor
	 * @todo   Implement testGetAuthor().
	 */
	public function testGetAuthor()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::setAllLoaded
	 * @todo   Implement testSetAllLoaded().
	 */
	public function testSetAllLoaded()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JCategoryNode::getNumItems
	 * @todo   Implement testGetNumItems().
	 */
	public function testGetNumItems()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
