<?php

/**
 * @package     Joomla.Administrator
 * @subpackage  com_workflow
 *
 * @copyright   (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @since       __DEPLOY_VERSION__
 */

use Joomla\CMS\Language\Text;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

// Populate the language
$translationStrings = [
    'UNEXPECTED_ERROR',
    'COM_WORKFLOW_GRAPH',
    'COM_WORKFLOW_GRAPH_LOADING',
    'COM_WORKFLOW_GRAPH_STATUS',
    'COM_WORKFLOW_GRAPH_ENABLED',
    'COM_WORKFLOW_GRAPH_DISABLED',
    'COM_WORKFLOW_GRAPH_STAGE',
    'COM_WORKFLOW_GRAPH_STAGES',
    'COM_WORKFLOW_GRAPH_STAGE_COUNT',
    'COM_WORKFLOW_GRAPH_TRANSITION',
    'COM_WORKFLOW_GRAPH_TRANSITIONS',
    'COM_WORKFLOW_GRAPH_TRANSITION_COUNT',
    'COM_WORKFLOW_GRAPH_ADD_STAGE',
    'COM_WORKFLOW_GRAPH_ADD_TRANSITION',
    'COM_WORKFLOW_GRAPH_EDIT_STAGE',
    'COM_WORKFLOW_GRAPH_EDIT_TRANSITION',
    'COM_WORKFLOW_GRAPH_ENTER_TRANSITION_MODE',
    'COM_WORKFLOW_GRAPH_EXIT_TRANSITION_MODE',
    'COM_WORKFLOW_GRAPH_UP_TO_DATE',
    'COM_WORKFLOW_GRAPH_UNSAVED_CHANGES',
    'COM_WORKFLOW_GRAPH_DEFAULT',
    'COM_WORKFLOW_GRAPH_CANVAS_REGION',
    'COM_WORKFLOW_GRAPH_MINIMAP',
    'COM_WORKFLOW_GRAPH_ADD_STAGE_DIALOG_OPENED',
    'COM_WORKFLOW_GRAPH_ADD_TRANSITION_DIALOG_OPENED',
    'COM_WORKFLOW_GRAPH_TRANSITION_MODE_ON',
    'COM_WORKFLOW_GRAPH_TRANSITION_MODE_OFF',
    'COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_ID_NOT_SET',
    'COM_WORKFLOW_GRAPH_ERROR_EXTENSION_NOT_SET',
    'COM_WORKFLOW_GRAPH_API_BASEURL_NOT_SET',
    'COM_WORKFLOW_GRAPH_ERROR_CSRF_TOKEN_NOT_SET',
    'COM_WORKFLOW_GRAPH_ERROR_INVALID_ID',
    'COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_NOT_FOUND',
    'COM_WORKFLOW_ERROR_STAGE_DEFAULT_CANT_DELETED',
    'COM_WORKFLOW_ERROR_STAGE_HAS_TRANSITIONS',
    'COM_WORKFLOW_GRAPH_DELETE_TRANSITION_FAILED',
    'COM_WORKFLOW_GRAPH_UPDATE_STAGE_POSITION_FAILED',
    'COM_WORKFLOW_GRAPH_WORKFLOWS_EDIT',
    'COM_WORKFLOW_GRAPH_SHORTCUTS_TITLE',
    'COM_WORKFLOW_GRAPH_SHORTCUTS',
    'COM_WORKFLOW_GRAPH_DELETE_STAGE_TITLE',
    'COM_WORKFLOW_GRAPH_DELETE_STAGE_CONFIRM',
    'COM_WORKFLOW_GRAPH_DELETE_TRANSITION_TITLE',
    'COM_WORKFLOW_GRAPH_DELETE_TRANSITION_CONFIRM'
];

foreach ($translationStrings as $string) {
    Text::script($string);
}
