(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(b){function a(b,a){if("function"===typeof window.CustomEvent)return new CustomEvent(b,a);var c=document.createEvent("CustomEvent");c.initCustomEvent(b,!!a.bubbles,!!a.cancelable,a.detail);return c}function c(b){if(n)return b.ownerDocument!==document?b.ownerDocument:null;var a=b.__importDoc;if(!a&&b.parentNode){a=b.parentNode;if("function"===typeof a.closest)a=a.closest("link[rel=import]");else for(;!l(a)&&(a=a.parentNode););b.__importDoc=a}return a}function d(b){var a=document.querySelectorAll("link[rel=import]:not([import-dependency])"),
c=a.length;c?h(a,function(a){return k(a,function(){0===--c&&b()})}):b()}function e(b){function a(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",a),b())}document.addEventListener("readystatechange",a);a()}function f(b){e(function(){return d(function(){return b&&b()})})}function k(b,a){if(b.__loaded)a&&a();else if("script"===b.localName&&!b.src||"style"===b.localName&&!b.firstChild)b.__loaded=!0,a&&a();else{var c=function(e){b.removeEventListener(e.type,
c);b.__loaded=!0;a&&a()};b.addEventListener("load",c);H&&"style"===b.localName||b.addEventListener("error",c)}}function l(b){return b.nodeType===Node.ELEMENT_NODE&&"link"===b.localName&&"import"===b.rel}function g(){var b=this;this.a={};this.b=0;this.g=new MutationObserver(function(a){return b.L(a)});this.g.observe(document.head,{childList:!0,subtree:!0});this.c(document)}function h(b,a,c){var e=b?b.length:0,d=c?-1:1;for(c=c?e-1:0;c<e&&0<=c;c+=d)a(b[c],c)}var n="import"in document.createElement("link"),
I=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return I||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var ua=/(url\()([^)]*)(\))/g,va=/(@import[\s]+(?!url\())([^;]*)(;)/g,wa=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,r={J:function(b,a){b.href&&b.setAttribute("href",r.j(b.getAttribute("href"),a));b.src&&b.setAttribute("src",r.j(b.getAttribute("src"),a));if("style"===b.localName){var c=
r.D(b.textContent,a,ua);b.textContent=r.D(c,a,va)}},D:function(b,a,c){return b.replace(c,function(b,c,e,d){b=e.replace(/["']/g,"");a&&(b=r.j(b,a));return c+"'"+b+"'"+d})},j:function(b,a){if(void 0===r.l){r.l=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";r.l="http://a/c%20d"===c.href}catch(Qa){}}if(r.l)return(new URL(b,a)).href;c=r.G;c||(c=document.implementation.createHTMLDocument("temp"),r.G=c,c.w=c.createElement("base"),c.head.appendChild(c.w),c.v=c.createElement("a"));c.w.href=a;c.v.href=
b;return c.v.href||b}},U={async:!0,load:function(b,a,c){if(b)if(b.match(/^data:/)){b=b.split(",");var e=b[1];e=-1<b[0].indexOf(";base64")?atob(e):decodeURIComponent(e);a(e)}else{var d=new XMLHttpRequest;d.open("GET",b,U.async);d.onload=function(){var b=d.responseURL||d.getResponseHeader("Location");b&&0===b.indexOf("/")&&(b=(location.origin||location.protocol+"//"+location.host)+b);var e=d.response||d.responseText;304===d.status||0===d.status||200<=d.status&&300>d.status?a(e,b):c(e)};d.send()}else c("error: href must be specified")}},
H=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);g.prototype.c=function(b){var a=this;h(b.querySelectorAll("link[rel=import]"),function(b){return a.B(b)})};g.prototype.B=function(b){var a=this,c=b.href;if(void 0!==this.a[c]){var e=this.a[c];e&&e.__loaded&&(b.import=e,this.A(b))}else this.b++,this.a[c]="pending",U.load(c,function(b,e){b=a.M(b,e||c);a.a[c]=b;a.b--;a.c(b);a.C()},function(){a.a[c]=null;a.b--;a.C()})};g.prototype.M=function(b,a){if(!b)return document.createDocumentFragment();
H&&(b=b.replace(wa,function(b,a,c){return-1===b.indexOf("type=")?a+" type=import-disable "+c:b}));var c=document.createElement("template");c.innerHTML=b;if(c.content)b=c.content;else for(b=document.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);if(c=b.querySelector("base"))a=r.j(c.getAttribute("href"),a),c.removeAttribute("href");var e=0;h(b.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),
function(b){k(b);r.J(b,a);b.setAttribute("import-dependency","");"script"===b.localName&&!b.src&&b.textContent&&(b.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(b.textContent+("\n//# sourceURL="+a+(e?"-"+e:"")+".js\n"))),b.textContent="",e++)});return b};g.prototype.C=function(){var b=this;if(!this.b){this.g.disconnect();this.flatten(document);var a=!1,c=!1,e=function(){c&&a&&(b.c(document),b.b||(b.g.observe(document.head,{childList:!0,subtree:!0}),b.K()))};this.P(function(){c=
!0;e()});this.N(function(){a=!0;e()})}};g.prototype.flatten=function(b){var a=this;h(b.querySelectorAll("link[rel=import]"),function(b){var c=a.a[b.href];(b.import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(a.a[b.href]=b,b.readyState="loading",b.import=b,a.flatten(c),b.appendChild(c))})};g.prototype.N=function(b){function a(d){if(d<e){var f=c[d],g=document.createElement("script");f.removeAttribute("import-dependency");h(f.attributes,function(b){return g.setAttribute(b.name,b.value)});I=g;f.parentNode.replaceChild(g,
f);k(g,function(){I=null;a(d+1)})}else b()}var c=document.querySelectorAll("script[import-dependency]"),e=c.length;a(0)};g.prototype.P=function(b){var a=document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),e=a.length;if(e){var d=H&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");h(a,function(a){k(a,function(){a.removeAttribute("import-dependency");0===--e&&b()});if(d&&a.parentNode!==document.head){var f=document.createElement(a.localName);
f.__appliedElement=a;f.setAttribute("type","import-placeholder");a.parentNode.insertBefore(f,a.nextSibling);for(f=c(a);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(a,f);a.removeAttribute("type")}})}else b()};g.prototype.K=function(){var b=this;h(document.querySelectorAll("link[rel=import]"),function(a){return b.A(a)},!0)};g.prototype.A=function(b){b.__loaded||(b.__loaded=!0,b.import&&(b.import.readyState="complete"),b.dispatchEvent(a(b.import?"load":"error",{bubbles:!1,
cancelable:!1,detail:void 0})))};g.prototype.L=function(b){var a=this;h(b,function(b){return h(b.addedNodes,function(b){b&&b.nodeType===Node.ELEMENT_NODE&&(l(b)?a.B(b):a.c(b))})})};if(n){h(document.querySelectorAll("link[rel=import]"),function(b){b.import&&"loading"===b.import.readyState||(b.__loaded=!0)});var V=function(b){b=b.target;l(b)&&(b.__loaded=!0)};document.addEventListener("load",V,!0);document.addEventListener("error",V,!0)}else{var z=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");
Object.defineProperty((!z||z.configurable?Node:Element).prototype,"baseURI",{get:function(){var b=l(this)?this:c(this);return b?b.href:z&&z.get?z.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});e(function(){return new g})}f(function(){return document.dispatchEvent(a("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=n;b.whenReady=f;b.importForElement=c})(window.HTMLImports=window.HTMLImports||{});var aa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function m(b){var a=aa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function p(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}
function q(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}
function t(b,a,c){c=void 0===c?new Set:c;for(var d=b;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;a(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)t(d,a,c);d=q(b,e);continue}else if("template"===f){d=q(b,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)t(e,a,c)}d=d.firstChild?d.firstChild:q(b,d)}}function u(b,a,c){b[a]=c};function v(){this.a=new Map;this.g=new Map;this.c=[];this.b=!1}function ba(b,a,c){b.a.set(a,c);b.g.set(c.constructor,c)}function w(b,a){b.b=!0;b.c.push(a)}function x(b,a){b.b&&t(a,function(a){return y(b,a)})}function y(b,a){if(b.b&&!a.__CE_patched){a.__CE_patched=!0;for(var c=0;c<b.c.length;c++)b.c[c](a)}}function A(b,a){var c=[];t(a,function(b){return c.push(b)});for(a=0;a<c.length;a++){var d=c[a];1===d.__CE_state?b.connectedCallback(d):B(b,d)}}
function C(b,a){var c=[];t(a,function(b){return c.push(b)});for(a=0;a<c.length;a++){var d=c[a];1===d.__CE_state&&b.disconnectedCallback(d)}}
function D(b,a,c){c=void 0===c?{}:c;var d=c.R||new Set,e=c.F||function(a){return B(b,a)},f=[];t(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var c=a.import;c instanceof Node&&"complete"===c.readyState?(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0):a.addEventListener("load",function(){var c=a.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;c.__CE_isImportDocument=!0;c.__CE_hasRegistry=!0;var f=new Set(d);f.delete(c);D(b,c,{R:f,F:e})}})}else f.push(a)},
d);if(b.b)for(a=0;a<f.length;a++)y(b,f[a]);for(a=0;a<f.length;a++)e(f[a])}
function B(b,a){if(void 0===a.__CE_state){var c=b.a.get(a.localName);if(c){c.constructionStack.push(a);var d=c.constructor;try{try{if(new d!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(k){throw a.__CE_state=2,k;}a.__CE_state=1;a.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=c[d],f=a.getAttribute(e);null!==f&&b.attributeChangedCallback(a,e,null,f,null)}p(a)&&
b.connectedCallback(a)}}}v.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};v.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};v.prototype.attributeChangedCallback=function(b,a,c,d,e){var f=b.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(a)&&f.attributeChangedCallback.call(b,a,c,d,e)};function E(b,a){this.f=b;this.a=a;this.b=void 0;D(this.f,this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.c.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function F(b){b.b&&b.b.disconnect()}E.prototype.c=function(b){var a=this.a.readyState;"interactive"!==a&&"complete"!==a||F(this);for(a=0;a<b.length;a++)for(var c=b[a].addedNodes,d=0;d<c.length;d++)D(this.f,c[d])};function ca(){var b=this;this.b=this.a=void 0;this.c=new Promise(function(a){b.b=a;b.a&&a(b.a)})}function da(b){if(b.a)throw Error("Already resolved.");b.a=void 0;b.b&&b.b(void 0)};function G(b){this.m=!1;this.f=b;this.u=new Map;this.o=function(b){return b()};this.h=!1;this.s=[];this.H=new E(b,document)}
G.prototype.define=function(b,a){var c=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!m(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.f.a.get(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.m)throw Error("A custom element is already being defined.");this.m=!0;try{var d=function(b){var a=e[b];if(void 0!==a&&!(a instanceof Function))throw Error("The '"+b+"' callback must be a function.");
return a},e=a.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var k=d("disconnectedCallback");var l=d("adoptedCallback");var g=d("attributeChangedCallback");var h=a.observedAttributes||[]}catch(n){return}finally{this.m=!1}a={localName:b,constructor:a,connectedCallback:f,disconnectedCallback:k,adoptedCallback:l,attributeChangedCallback:g,observedAttributes:h,constructionStack:[]};ba(this.f,b,a);this.s.push(a);
this.h||(this.h=!0,this.o(function(){return ea(c)}))};function ea(b){if(!1!==b.h){b.h=!1;for(var a=b.s,c=[],d=new Map,e=0;e<a.length;e++)d.set(a[e].localName,[]);D(b.f,document,{F:function(a){if(void 0===a.__CE_state){var e=a.localName,f=d.get(e);f?f.push(a):b.f.a.get(e)&&c.push(a)}}});for(e=0;e<c.length;e++)B(b.f,c[e]);for(;0<a.length;){var f=a.shift();e=f.localName;f=d.get(f.localName);for(var k=0;k<f.length;k++)B(b.f,f[k]);(e=b.u.get(e))&&da(e)}}}G.prototype.get=function(b){if(b=this.f.a.get(b))return b.constructor};
G.prototype.whenDefined=function(b){if(!m(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.u.get(b);if(a)return a.c;a=new ca;this.u.set(b,a);this.f.a.get(b)&&!this.s.some(function(a){return a.localName===b})&&da(a);return a.c};G.prototype.O=function(b){F(this.H);var a=this.o;this.o=function(c){return b(function(){return a(c)})}};window.CustomElementRegistry=G;G.prototype.define=G.prototype.define;G.prototype.get=G.prototype.get;
G.prototype.whenDefined=G.prototype.whenDefined;G.prototype.polyfillWrapFlushCallback=G.prototype.O;var J=window.Document.prototype.createElement,fa=window.Document.prototype.createElementNS,ha=window.Document.prototype.importNode,ia=window.Document.prototype.prepend,ja=window.Document.prototype.append,ka=window.DocumentFragment.prototype.prepend,la=window.DocumentFragment.prototype.append,ma=window.Node.prototype.cloneNode,K=window.Node.prototype.appendChild,na=window.Node.prototype.insertBefore,L=window.Node.prototype.removeChild,oa=window.Node.prototype.replaceChild,M=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),pa=window.Element.prototype.attachShadow,N=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),O=window.Element.prototype.getAttribute,qa=window.Element.prototype.setAttribute,ra=window.Element.prototype.removeAttribute,P=window.Element.prototype.getAttributeNS,sa=window.Element.prototype.setAttributeNS,ta=window.Element.prototype.removeAttributeNS,xa=window.Element.prototype.insertAdjacentElement,ya=window.Element.prototype.prepend,za=window.Element.prototype.append,
Q=window.Element.prototype.before,Aa=window.Element.prototype.after,Ba=window.Element.prototype.replaceWith,Ca=window.Element.prototype.remove,Da=window.HTMLElement,R=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Ea=window.HTMLElement.prototype.insertAdjacentElement;var Fa=new function(){};function Ga(){var b=S;window.HTMLElement=function(){function a(){var a=this.constructor,d=b.g.get(a);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=J.call(document,d.localName),Object.setPrototypeOf(e,a.prototype),e.__CE_state=1,e.__CE_definition=d,y(b,e),e;d=e.length-1;var f=e[d];if(f===Fa)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=Fa;Object.setPrototypeOf(f,a.prototype);y(b,f);return f}a.prototype=Da.prototype;return a}()};function T(b,a,c){function d(a){return function(c){for(var e=[],d=0;d<arguments.length;++d)e[d-0]=arguments[d];d=[];for(var f=[],h=0;h<e.length;h++){var n=e[h];n instanceof Element&&p(n)&&f.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)d.push(n);else d.push(n)}a.apply(this,e);for(e=0;e<f.length;e++)C(b,f[e]);if(p(this))for(e=0;e<d.length;e++)f=d[e],f instanceof Element&&A(b,f)}}void 0!==c.i&&(a.prepend=d(c.i));void 0!==c.append&&(a.append=d(c.append))};function Ha(){var b=S;u(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var c=b.a.get(a);if(c)return new c.constructor}a=J.call(this,a);y(b,a);return a});u(Document.prototype,"importNode",function(a,c){a=ha.call(this,a,c);this.__CE_hasRegistry?D(b,a):x(b,a);return a});u(Document.prototype,"createElementNS",function(a,c){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var d=b.a.get(c);if(d)return new d.constructor}a=fa.call(this,a,c);y(b,a);return a});
T(b,Document.prototype,{i:ia,append:ja})};function Ia(){var b=S;function a(a,d){Object.defineProperty(a,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,a);else{var c=void 0;if(this.firstChild){var e=this.childNodes,l=e.length;if(0<l&&p(this)){c=Array(l);for(var g=0;g<l;g++)c[g]=e[g]}}d.set.call(this,a);if(c)for(a=0;a<c.length;a++)C(b,c[a])}}})}u(Node.prototype,"insertBefore",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);
a=na.call(this,a,d);if(p(this))for(d=0;d<c.length;d++)A(b,c[d]);return a}c=p(a);d=na.call(this,a,d);c&&C(b,a);p(this)&&A(b,a);return d});u(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=K.call(this,a);if(p(this))for(var e=0;e<c.length;e++)A(b,c[e]);return a}c=p(a);e=K.call(this,a);c&&C(b,a);p(this)&&A(b,a);return e});u(Node.prototype,"cloneNode",function(a){a=ma.call(this,a);this.ownerDocument.__CE_hasRegistry?D(b,a):x(b,
a);return a});u(Node.prototype,"removeChild",function(a){var c=p(a),e=L.call(this,a);c&&C(b,a);return e});u(Node.prototype,"replaceChild",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=oa.call(this,a,d);if(p(this))for(C(b,d),d=0;d<c.length;d++)A(b,c[d]);return a}c=p(a);var f=oa.call(this,a,d),k=p(this);k&&C(b,d);c&&C(b,a);k&&A(b,a);return f});M&&M.get?a(Node.prototype,M):w(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var b=
[],a=0;a<this.childNodes.length;a++)b.push(this.childNodes[a].textContent);return b.join("")},set:function(b){for(;this.firstChild;)L.call(this,this.firstChild);K.call(this,document.createTextNode(b))}})})};function Ja(b){var a=Element.prototype;function c(a){return function(c){for(var e=[],d=0;d<arguments.length;++d)e[d-0]=arguments[d];d=[];for(var l=[],g=0;g<e.length;g++){var h=e[g];h instanceof Element&&p(h)&&l.push(h);if(h instanceof DocumentFragment)for(h=h.firstChild;h;h=h.nextSibling)d.push(h);else d.push(h)}a.apply(this,e);for(e=0;e<l.length;e++)C(b,l[e]);if(p(this))for(e=0;e<d.length;e++)l=d[e],l instanceof Element&&A(b,l)}}void 0!==Q&&(a.before=c(Q));void 0!==Q&&(a.after=c(Aa));void 0!==Ba&&
u(a,"replaceWith",function(a){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];d=[];for(var k=[],l=0;l<c.length;l++){var g=c[l];g instanceof Element&&p(g)&&k.push(g);if(g instanceof DocumentFragment)for(g=g.firstChild;g;g=g.nextSibling)d.push(g);else d.push(g)}l=p(this);Ba.apply(this,c);for(c=0;c<k.length;c++)C(b,k[c]);if(l)for(C(b,this),c=0;c<d.length;c++)k=d[c],k instanceof Element&&A(b,k)});void 0!==Ca&&u(a,"remove",function(){var a=p(this);Ca.call(this);a&&C(b,this)})};function Ka(){var b=S;function a(a,c){Object.defineProperty(a,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){var e=this,d=void 0;p(this)&&(d=[],t(this,function(b){b!==e&&d.push(b)}));c.set.call(this,a);if(d)for(var f=0;f<d.length;f++){var k=d[f];1===k.__CE_state&&b.disconnectedCallback(k)}this.ownerDocument.__CE_hasRegistry?D(b,this):x(b,this);return a}})}function c(a,c){u(a,"insertAdjacentElement",function(a,e){var d=p(e);a=c.call(this,a,e);d&&C(b,e);p(a)&&A(b,e);
return a})}pa&&u(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=pa.call(this,b)});if(N&&N.get)a(Element.prototype,N);else if(R&&R.get)a(HTMLElement.prototype,R);else{var d=J.call(document,"div");w(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return ma.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?this.content:this;for(d.innerHTML=b;0<a.childNodes.length;)L.call(a,a.childNodes[0]);for(;0<d.childNodes.length;)K.call(a,d.childNodes[0])}})})}u(Element.prototype,
"setAttribute",function(a,c){if(1!==this.__CE_state)return qa.call(this,a,c);var d=O.call(this,a);qa.call(this,a,c);c=O.call(this,a);b.attributeChangedCallback(this,a,d,c,null)});u(Element.prototype,"setAttributeNS",function(a,c,d){if(1!==this.__CE_state)return sa.call(this,a,c,d);var e=P.call(this,a,c);sa.call(this,a,c,d);d=P.call(this,a,c);b.attributeChangedCallback(this,c,e,d,a)});u(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return ra.call(this,a);var c=O.call(this,
a);ra.call(this,a);null!==c&&b.attributeChangedCallback(this,a,c,null,null)});u(Element.prototype,"removeAttributeNS",function(a,c){if(1!==this.__CE_state)return ta.call(this,a,c);var d=P.call(this,a,c);ta.call(this,a,c);var e=P.call(this,a,c);d!==e&&b.attributeChangedCallback(this,c,d,e,a)});Ea?c(HTMLElement.prototype,Ea):xa?c(Element.prototype,xa):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");T(b,Element.prototype,{i:ya,append:za});Ja(b)};var W=window.customElements;if(!W||W.forcePolyfill||"function"!=typeof W.define||"function"!=typeof W.get){var S=new v;Ga();Ha();T(S,DocumentFragment.prototype,{i:ka,append:la});Ia();Ka();document.__CE_hasRegistry=!0;var customElements=new G(S);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var X=window.customElements,Y=window.HTMLImports,La=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(X&&X.polyfillWrapFlushCallback){var Z,Ma=function(){if(Z){La.I&&La.I(window.document);var b=Z;Z=null;b();return!0}},Na=Y.whenReady;X.polyfillWrapFlushCallback(function(b){Z=b;Na(Ma)});Y.whenReady=function(b){Na(function(){Ma()?Y.whenReady(b):b()})}}
Y.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Oa=document.createElement("style");Oa.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Pa=document.querySelector("head");Pa.insertBefore(Oa,Pa.firstChild);/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
