(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(){function X(b){function a(f,a){Object.defineProperty(f,"innerHTML",{enumerable:a.enumerable,configurable:!0,get:a.get,set:function(f){var e=this,d=void 0;h(this)&&(d=[],q(this,function(b){b!==e&&d.push(b)}));a.set.call(this,f);if(d)for(var c=0;c<d.length;c++){var k=d[c];1===k.__CE_state&&b.disconnectedCallback(k)}this.ownerDocument.__CE_hasRegistry?b.c(this):b.j(this);return f}})}function d(f,a){m(f,"insertAdjacentElement",function(f,e){var d=h(e);f=a.call(this,f,e);d&&b.a(e);
h(f)&&b.b(e);return f})}G?m(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=G.call(this,b)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(t&&t.get)a(Element.prototype,t);else if(v&&v.get)a(HTMLElement.prototype,v);else{var c=A.call(document,"div");b.o(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return H.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?this.content:this;for(c.innerHTML=b;0<a.childNodes.length;)B.call(a,
a.childNodes[0]);for(;0<c.childNodes.length;)w.call(a,c.childNodes[0])}})})}m(Element.prototype,"setAttribute",function(a,e){if(1!==this.__CE_state)return I.call(this,a,e);var f=C.call(this,a);I.call(this,a,e);e=C.call(this,a);b.attributeChangedCallback(this,a,f,e,null)});m(Element.prototype,"setAttributeNS",function(a,e,d){if(1!==this.__CE_state)return J.call(this,a,e,d);var f=x.call(this,a,e);J.call(this,a,e,d);d=x.call(this,a,e);b.attributeChangedCallback(this,e,f,d,a)});m(Element.prototype,"removeAttribute",
function(a){if(1!==this.__CE_state)return K.call(this,a);var f=C.call(this,a);K.call(this,a);null!==f&&b.attributeChangedCallback(this,a,f,null,null)});m(Element.prototype,"removeAttributeNS",function(a,d){if(1!==this.__CE_state)return L.call(this,a,d);var f=x.call(this,a,d);L.call(this,a,d);var e=x.call(this,a,d);f!==e&&b.attributeChangedCallback(this,d,f,e,a)});M?d(HTMLElement.prototype,M):N?d(Element.prototype,N):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");
O(b,Element.prototype,{B:Y,append:Z});aa(b,{H:ba,G:ca,replaceWith:da,remove:ea})}function aa(b,a){var d=Element.prototype;d.before=function(d){for(var f=[],e=0;e<arguments.length;++e)f[e-0]=arguments[e];e=f.filter(function(b){return b instanceof Node&&h(b)});a.H.apply(this,f);for(var c=0;c<e.length;c++)b.a(e[c]);if(h(this))for(e=0;e<f.length;e++)c=f[e],c instanceof Element&&b.b(c)};d.after=function(d){for(var f=[],e=0;e<arguments.length;++e)f[e-0]=arguments[e];e=f.filter(function(b){return b instanceof
Node&&h(b)});a.G.apply(this,f);for(var c=0;c<e.length;c++)b.a(e[c]);if(h(this))for(e=0;e<f.length;e++)c=f[e],c instanceof Element&&b.b(c)};d.replaceWith=function(d){for(var f=[],c=0;c<arguments.length;++c)f[c-0]=arguments[c];c=f.filter(function(b){return b instanceof Node&&h(b)});var k=h(this);a.replaceWith.apply(this,f);for(var r=0;r<c.length;r++)b.a(c[r]);if(k)for(b.a(this),c=0;c<f.length;c++)k=f[c],k instanceof Element&&b.b(k)};d.remove=function(){var d=h(this);a.remove.call(this);d&&b.a(this)}}
function fa(b){function a(a,c){Object.defineProperty(a,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,a);else{var d=void 0;if(this.firstChild){var f=this.childNodes,r=f.length;if(0<r&&h(this)){d=Array(r);for(var g=0;g<r;g++)d[g]=f[g]}}c.set.call(this,a);if(d)for(a=0;a<d.length;a++)b.a(d[a])}}})}m(Node.prototype,"insertBefore",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);
a=P.call(this,a,c);if(h(this))for(c=0;c<d.length;c++)b.b(d[c]);return a}d=h(a);c=P.call(this,a,c);d&&b.a(a);h(this)&&b.b(a);return c});m(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=w.call(this,a);if(h(this))for(var d=0;d<c.length;d++)b.b(c[d]);return a}c=h(a);d=w.call(this,a);c&&b.a(a);h(this)&&b.b(a);return d});m(Node.prototype,"cloneNode",function(a){a=H.call(this,a);this.ownerDocument.__CE_hasRegistry?b.c(a):b.j(a);
return a});m(Node.prototype,"removeChild",function(a){var c=h(a),d=B.call(this,a);c&&b.a(a);return d});m(Node.prototype,"replaceChild",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);a=Q.call(this,a,c);if(h(this))for(b.a(c),c=0;c<d.length;c++)b.b(d[c]);return a}d=h(a);var e=Q.call(this,a,c),k=h(this);k&&b.a(c);d&&b.a(a);k&&b.b(a);return e});D&&D.get?a(Node.prototype,D):b.o(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=
0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)B.call(this,this.firstChild);w.call(this,document.createTextNode(a))}})})}function ha(b){m(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var d=b.f(a);if(d)return new d.constructor}a=A.call(this,a);b.g(a);return a});m(Document.prototype,"importNode",function(a,d){a=ia.call(this,a,d);this.__CE_hasRegistry?b.c(a):b.j(a);return a});m(Document.prototype,
"createElementNS",function(a,d){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var c=b.f(d);if(c)return new c.constructor}a=ja.call(this,a,d);b.g(a);return a});O(b,Document.prototype,{B:ka,append:la})}function O(b,a,d){a.prepend=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&h(a)});d.B.apply(this,c);for(var k=0;k<e.length;k++)b.a(e[k]);if(h(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&
b.b(k)};a.append=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&h(a)});d.append.apply(this,c);for(var k=0;k<e.length;k++)b.a(e[k]);if(h(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&b.b(k)}}function ma(b){window.HTMLElement=function(){function a(){var a=this.constructor,c=b.J(a);if(!c)throw Error("The custom element being constructed was not registered with `customElements`.");var f=c.constructionStack;if(0===f.length)return f=
A.call(document,c.localName),Object.setPrototypeOf(f,a.prototype),f.__CE_state=1,f.__CE_definition=c,b.g(f),f;c=f.length-1;var e=f[c];if(e===R)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");f[c]=R;Object.setPrototypeOf(e,a.prototype);b.g(e);return e}a.prototype=na.prototype;return a}()}function l(b){this.f=!1;this.a=b;this.h=new Map;this.g=function(a){return a()};this.b=!1;this.c=[];this.i=new E(b,document)}function S(){var b=
this;this.b=this.a=void 0;this.f=new Promise(function(a){b.b=a;b.a&&a(b.a)})}function E(b,a){this.c=b;this.a=a;this.b=void 0;this.c.c(this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.g.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function n(){this.m=new Map;this.l=new Map;this.i=[];this.h=!1}function T(b){var a=oa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function h(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||
b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}function F(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}function q(b,a,d){d=d?d:new Set;for(var c=b;c;){if(c.nodeType===Node.ELEMENT_NODE){var f=c;a(f);var e=f.localName;if("link"===e&&"import"===f.getAttribute("rel")){c=f.import;if(c instanceof Node&&!d.has(c))for(d.add(c),c=c.firstChild;c;c=c.nextSibling)q(c,
a,d);c=F(b,f);continue}else if("template"===e){c=F(b,f);continue}if(f=f.__CE_shadowRoot)for(f=f.firstChild;f;f=f.nextSibling)q(f,a,d)}c=c.firstChild?c.firstChild:F(b,c)}}function m(b,a,d){b[a]=d}(function(b){function a(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function d(a){if(m)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&
a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function c(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),c=b.length;c?l(b,function(b){return k(b,function(){0===--c&&a()})}):a()}function f(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function e(a){f(function(){return c(function(){return a&&
a()})})}function k(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);t&&"style"===a.localName||a.addEventListener("error",c)}}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function g(){var a=this;this.a={};this.b=0;this.f=new MutationObserver(function(b){return a.l(b)});this.f.observe(document.head,
{childList:!0,subtree:!0});this.c(document)}function l(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var m="import"in document.createElement("link"),n=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return n||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var q=/(^\/)|(^#)|(^[\w-\d]*:)/,w=/(url\()([^)]*)(\))/g,x=/(@import[\s]+(?!url\())([^;]*)(;)/g,y=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,
p={I:function(a,b){a.href&&a.setAttribute("href",p.v(a.getAttribute("href"),b));a.src&&a.setAttribute("src",p.v(a.getAttribute("src"),b));if("style"===a.localName){var c=p.C(a.textContent,b,w);a.textContent=p.C(c,b,x)}},C:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=p.D(a,b));return c+"'"+a+"'"+e})},v:function(a,b){return a&&q.test(a)?a:p.D(a,b)},D:function(a,b){if(void 0===p.u){p.u=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";p.u="http://a/c%20d"===
c.href}catch(qa){}}if(p.u)return(new URL(a,b)).href;c=p.F;c||(c=document.implementation.createHTMLDocument("temp"),p.F=c,c.A=c.createElement("base"),c.head.appendChild(c.A),c.w=c.createElement("a"));c.A.href=b;c.w.href=a;return c.w.href||a}},u={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,u.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");
a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},t=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);g.prototype.c=function(a){var b=this;l(a.querySelectorAll("link[rel=import]"),function(a){return b.h(a)})};g.prototype.h=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];
d&&d.__loaded&&(a.import=d,this.g(a))}else this.b++,this.a[c]="pending",u.load(c,function(a,d){a=b.m(a,d||c);b.a[c]=a;b.b--;b.c(a);b.i()},function(){b.a[c]=null;b.b--;b.i()})};g.prototype.m=function(a,b){if(!a)return document.createDocumentFragment();t&&(a=a.replace(y,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);
if(c=a.querySelector("base"))b=p.v(c.getAttribute("href"),b),c.removeAttribute("href");var d=0;l(a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),function(a){k(a);p.I(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+
encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};g.prototype.i=function(){var a=this;if(!this.b){this.f.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.c(document),a.b||(a.f.observe(document.head,{childList:!0,subtree:!0}),a.j()))};this.s(function(){c=!0;d()});this.o(function(){b=!0;d()})}};g.prototype.flatten=function(a){var b=this;l(a.querySelectorAll("link[rel=import]"),function(a){var c=b.a[a.href];(a.import=
c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.import=a,b.flatten(c),a.appendChild(c))})};g.prototype.o=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");l(f.attributes,function(a){return g.setAttribute(a.name,a.value)});n=g;f.parentNode.replaceChild(g,f);k(g,function(){n=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};g.prototype.s=function(a){var b=
document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),c=b.length;if(c){var e=t&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");l(b,function(b){k(b,function(){b.removeAttribute("import-dependency");0===--c&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=d(b);f&&d(f);)f=d(f);f.parentNode!==
document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};g.prototype.j=function(){var a=this;l(document.querySelectorAll("link[rel=import]"),function(b){return a.g(b)},!0)};g.prototype.g=function(b){b.__loaded||(b.__loaded=!0,b.import&&(b.import.readyState="complete"),b.dispatchEvent(a(b.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};g.prototype.l=function(a){var b=this;l(a,function(a){return l(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&
(h(a)?b.h(a):b.c(a))})})};if(m){l(document.querySelectorAll("link[rel=import]"),function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)});var v=function(a){a=a.target;h(a)&&(a.__loaded=!0)};document.addEventListener("load",v,!0);document.addEventListener("error",v,!0)}else{var z=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!z||z.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:d(this);return a?a.href:z&&z.get?z.get.call(this):
(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});f(function(){return new g})}e(function(){return document.dispatchEvent(a("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=m;b.whenReady=e;b.importForElement=d})(window.HTMLImports=window.HTMLImports||{});var oa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));n.prototype.K=function(b,a){this.m.set(b,
a);this.l.set(a.constructor,a)};n.prototype.f=function(b){return this.m.get(b)};n.prototype.J=function(b){return this.l.get(b)};n.prototype.o=function(b){this.h=!0;this.i.push(b)};n.prototype.j=function(b){var a=this;this.h&&q(b,function(b){return a.g(b)})};n.prototype.g=function(b){if(this.h&&!b.__CE_patched){b.__CE_patched=!0;for(var a=0;a<this.i.length;a++)this.i[a](b)}};n.prototype.b=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state?this.connectedCallback(d):
this.s(d)}};n.prototype.a=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state&&this.disconnectedCallback(d)}};n.prototype.c=function(b,a){var d=this;a=a?a:new Set;var c=[];q(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var e=b.import;e instanceof Node&&"complete"===e.readyState?(e.__CE_isImportDocument=!0,e.__CE_hasRegistry=!0):b.addEventListener("load",function(){var c=b.import;c.__CE_documentLoadHandled||(c.__CE_documentLoadHandled=
!0,c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0,a.delete(c),d.c(c,a))})}else c.push(b)},a);if(this.h)for(b=0;b<c.length;b++)this.g(c[b]);for(b=0;b<c.length;b++)this.s(c[b])};n.prototype.s=function(b){if(void 0===b.__CE_state){var a=this.f(b.localName);if(a){a.constructionStack.push(b);var d=a.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{a.constructionStack.pop()}}catch(e){throw b.__CE_state=2,e;}b.__CE_state=
1;b.__CE_definition=a;if(a.attributeChangedCallback)for(a=a.observedAttributes,d=0;d<a.length;d++){var c=a[d],f=b.getAttribute(c);null!==f&&this.attributeChangedCallback(b,c,null,f,null)}h(b)&&this.connectedCallback(b)}}};n.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};n.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};n.prototype.attributeChangedCallback=function(b,
a,d,c,f){var e=b.__CE_definition;e.attributeChangedCallback&&-1<e.observedAttributes.indexOf(a)&&e.attributeChangedCallback.call(b,a,d,c,f)};E.prototype.f=function(){this.b&&this.b.disconnect()};E.prototype.g=function(b){var a=this.a.readyState;"interactive"!==a&&"complete"!==a||this.f();for(a=0;a<b.length;a++)for(var d=b[a].addedNodes,c=0;c<d.length;c++)this.c.c(d[c])};S.prototype.c=function(){if(this.a)throw Error("Already resolved.");this.a=void 0;this.b&&this.b(void 0)};l.prototype.define=function(b,
a){var d=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!T(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.a.f(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.f)throw Error("A custom element is already being defined.");this.f=!0;try{var c=function(a){var b=f[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},f=a.prototype;
if(!(f instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var e=c("connectedCallback");var g=c("disconnectedCallback");var h=c("adoptedCallback");var l=c("attributeChangedCallback");var m=a.observedAttributes||[]}catch(pa){return}finally{this.f=!1}this.a.K(b,{localName:b,constructor:a,connectedCallback:e,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:l,observedAttributes:m,constructionStack:[]});this.c.push(b);this.b||(this.b=
!0,this.g(function(){return d.j()}))};l.prototype.j=function(){if(!1!==this.b)for(this.b=!1,this.a.c(document);0<this.c.length;){var b=this.c.shift();(b=this.h.get(b))&&b.c()}};l.prototype.get=function(b){if(b=this.a.f(b))return b.constructor};l.prototype.whenDefined=function(b){if(!T(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.h.get(b);if(a)return a.f;a=new S;this.h.set(b,a);this.a.f(b)&&-1===this.c.indexOf(b)&&a.c();return a.f};l.prototype.l=
function(b){this.i.f();var a=this.g;this.g=function(d){return b(function(){return a(d)})}};window.CustomElementRegistry=l;l.prototype.define=l.prototype.define;l.prototype.get=l.prototype.get;l.prototype.whenDefined=l.prototype.whenDefined;l.prototype.polyfillWrapFlushCallback=l.prototype.l;var A=window.Document.prototype.createElement,ja=window.Document.prototype.createElementNS,ia=window.Document.prototype.importNode,ka=window.Document.prototype.prepend,la=window.Document.prototype.append,H=window.Node.prototype.cloneNode,
w=window.Node.prototype.appendChild,P=window.Node.prototype.insertBefore,B=window.Node.prototype.removeChild,Q=window.Node.prototype.replaceChild,D=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),G=window.Element.prototype.attachShadow,t=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),C=window.Element.prototype.getAttribute,I=window.Element.prototype.setAttribute,K=window.Element.prototype.removeAttribute,x=window.Element.prototype.getAttributeNS,J=window.Element.prototype.setAttributeNS,
L=window.Element.prototype.removeAttributeNS,N=window.Element.prototype.insertAdjacentElement,Y=window.Element.prototype.prepend,Z=window.Element.prototype.append,ba=window.Element.prototype.before,ca=window.Element.prototype.after,da=window.Element.prototype.replaceWith,ea=window.Element.prototype.remove,na=window.HTMLElement,v=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),M=window.HTMLElement.prototype.insertAdjacentElement,R=new function(){},g=window.customElements;
if(!g||g.forcePolyfill||"function"!=typeof g.define||"function"!=typeof g.get)g=new n,ma(g),ha(g),fa(g),X(g),document.__CE_hasRegistry=!0,g=new l(g),Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:g});g=window.customElements;var y=window.HTMLImports;window.WebComponents=window.WebComponents||{};if(g&&g.polyfillWrapFlushCallback){var u,U=function(){if(u){var b=u;u=null;b();return!0}},V=y.whenReady;g.polyfillWrapFlushCallback(function(b){u=b;V(U)});y.whenReady=function(b){V(function(){U()?
y.whenReady(b):b()})}}y.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});g=document.createElement("style");g.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var W=document.querySelector("head");W.insertBefore(g,W.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
