(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var kb="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
(function(){function k(){var a=this;this.m={};this.g=document.documentElement;var b=new ua;b.rules=[];this.h=r.set(this.g,new r(b));this.i=!1;this.b=this.a=null;lb(function(){a.c()})}function C(){this.customStyles=[];this.enqueued=!1}function mb(){}function ba(a){this.cache={};this.c=void 0===a?100:a}function p(){}function r(a,b,c,d,e){this.D=a||null;this.b=b||null;this.ha=c||[];this.L=null;this.U=e||"";this.a=this.w=this.H=null}function q(){}function ua(){this.end=this.start=0;this.rules=this.parent=
this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Uc(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;n(this)&&(e=[],K(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&a.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?a.f(this):a.l(this);
return b}})}function c(b,c){x(b,"insertAdjacentElement",function(b,d){var e=n(d);b=c.call(this,b,d);e&&a.a(d);n(b)&&a.b(d);return b})}nb?x(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=nb.call(this,a)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(va&&va.get)b(Element.prototype,va);else if(wa&&wa.get)b(HTMLElement.prototype,wa);else{var d=xa.call(document,"div");a.u(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return ob.call(this,
!0).innerHTML},set:function(a){var b="template"===this.localName?this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)ya.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)da.call(b,d.childNodes[0])}})})}x(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return pb.call(this,b,c);var d=za.call(this,b);pb.call(this,b,c);c=za.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});x(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return qb.call(this,
b,c,d);var e=ea.call(this,b,c);qb.call(this,b,c,d);d=ea.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});x(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return rb.call(this,b);var c=za.call(this,b);rb.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});x(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return sb.call(this,b,c);var d=ea.call(this,b,c);sb.call(this,b,c);var e=ea.call(this,b,c);d!==e&&a.attributeChangedCallback(this,
c,d,e,b)});tb?c(HTMLElement.prototype,tb):ub?c(Element.prototype,ub):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");vb(a,Element.prototype,{wa:Vc,append:Wc});Xc(a,{Qa:Yc,Pa:Zc,replaceWith:$c,remove:ad})}function Xc(a,b){var c=Element.prototype;c.before=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});b.Qa.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(n(this))for(f=0;f<d.length;f++)g=
d[f],g instanceof Element&&a.b(g)};c.after=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});b.Pa.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.replaceWith=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});var g=n(this);b.replaceWith.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);
if(g)for(a.a(this),f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.remove=function(){var c=n(this);b.remove.call(this);c&&a.a(this)}}function bd(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&n(this)){c=Array(h);for(var m=0;m<h;m++)c[m]=e[m]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.a(c[b])}}})}
x(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=wb.call(this,b,d);if(n(this))for(d=0;d<c.length;d++)a.b(c[d]);return b}c=n(b);d=wb.call(this,b,d);c&&a.a(b);n(this)&&a.b(b);return d});x(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=da.call(this,b);if(n(this))for(var e=0;e<c.length;e++)a.b(c[e]);return b}c=n(b);e=da.call(this,b);c&&a.a(b);n(this)&&
a.b(b);return e});x(Node.prototype,"cloneNode",function(b){b=ob.call(this,b);this.ownerDocument.__CE_hasRegistry?a.f(b):a.l(b);return b});x(Node.prototype,"removeChild",function(b){var c=n(b),e=ya.call(this,b);c&&a.a(b);return e});x(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=xb.call(this,b,d);if(n(this))for(a.a(d),d=0;d<c.length;d++)a.b(c[d]);return b}c=n(b);var f=xb.call(this,b,d),g=n(this);g&&a.a(d);c&&a.a(b);g&&
a.b(b);return f});Aa&&Aa.get?b(Node.prototype,Aa):a.u(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)ya.call(this,this.firstChild);da.call(this,document.createTextNode(a))}})})}function cd(a){x(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.c(b);if(c)return new c.constructor}b=xa.call(this,b);a.g(b);return b});
x(Document.prototype,"importNode",function(b,c){b=dd.call(this,b,c);this.__CE_hasRegistry?a.f(b):a.l(b);return b});x(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.c(c);if(d)return new d.constructor}b=ed.call(this,b,c);a.g(b);return b});vb(a,Document.prototype,{wa:fd,append:gd})}function vb(a,b,c){b.prepend=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof
Node&&n(a)});c.wa.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};b.append=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&n(a)});c.append.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(n(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)}}function hd(a){window.HTMLElement=function(){function b(){var b=this.constructor,d=a.A(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");
var e=d.constructionStack;if(0===e.length)return e=xa.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.g(e),e;d=e.length-1;var f=e[d];if(f===yb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[d]=yb;Object.setPrototypeOf(f,b.prototype);a.g(f);return f}b.prototype=id.prototype;return b}()}function v(a){this.c=!1;this.a=a;this.h=new Map;this.f=function(a){return a()};this.b=!1;
this.g=[];this.i=new Ba(a,document)}function zb(){var a=this;this.b=this.a=void 0;this.f=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function Ba(a,b){this.b=a;this.a=b;this.K=void 0;this.b.f(this.a);"loading"===this.a.readyState&&(this.K=new MutationObserver(this.f.bind(this)),this.K.observe(this.a,{childList:!0,subtree:!0}))}function y(){this.o=new Map;this.m=new Map;this.j=[];this.h=!1}function l(a,b,c){if(a!==Ab)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=
l.prototype;a.B(b,c);return a}function fa(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=Ca(a);a.__shady.lastChild=Da(a);Bb(a);for(var b=a.__shady.childNodes=O(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,Cb(d)}}function jd(a){var b=a&&a.K;b&&(b.W.delete(a.Ka),b.W.size||(a.La.__shady.S=null))}function kd(a,b){a.__shady=a.__shady||{};a.__shady.S||
(a.__shady.S=new ha);a.__shady.S.W.add(b);var c=a.__shady.S;return{Ka:b,K:c,La:a,takeRecords:function(){return c.takeRecords()}}}function ha(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.W=new Set}function P(a){return a.__shady&&void 0!==a.__shady.firstChild}function E(a){return"ShadyRoot"===a.Ga}function U(a){a=a.getRootNode();if(E(a))return a}function Ea(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&
Object.defineProperty(a,e,f)}}function Fa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)Ea(a,c[d]);return a}function ld(a,b){for(var c in b)a[c]=b[c]}function Db(a){Ga.push(a);Ha.textContent=Eb++}function Fb(a){Ia||(Ia=!0,Db(ia));V.push(a)}function ia(){Ia=!1;for(var a=!!V.length;V.length;)V.shift()();return a}function md(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===
a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})}function Gb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Hb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}function Ja(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=
g;var m=a;var k=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var ca=h.localName,l="<"+ca,n=h.attributes,p=0;m=n[p];p++)l+=" "+m.name+'="'+m.value.replace(nd,Gb)+'"';l+=">";h=od[ca]?l:l+Ja(h,k)+"</"+ca+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&pd[m.localName]?h:h.replace(qd,Gb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),Error("not implemented");}}c+=h}return c}function Q(a){z.currentNode=a;return z.parentNode()}function Ca(a){z.currentNode=
a;return z.firstChild()}function Da(a){z.currentNode=a;return z.lastChild()}function Ib(a){z.currentNode=a;return z.previousSibling()}function Jb(a){z.currentNode=a;return z.nextSibling()}function O(a){var b=[];z.currentNode=a;for(a=z.firstChild();a;)b.push(a),a=z.nextSibling();return b}function Kb(a){A.currentNode=a;return A.parentNode()}function Lb(a){A.currentNode=a;return A.firstChild()}function Mb(a){A.currentNode=a;return A.lastChild()}function Nb(a){A.currentNode=a;return A.previousSibling()}
function Ob(a){A.currentNode=a;return A.nextSibling()}function Pb(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return b}function Qb(a){return Ja(a,function(a){return O(a)})}function Rb(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}}function H(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,
d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function L(a){H(a,Sb);H(a,Ka);H(a,La)}function Tb(a,b,c){Cb(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&
(b.__shady.firstChild=a):(b.__shady.lastChild=a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}function Ma(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&Q(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&
Na(b.parentNode,b);d=U(a);var e;if(e=d)a:{if(!b.__noInsertionPoint){var f;"slot"===b.localName?f=[b]:b.querySelectorAll&&(f=b.querySelectorAll("slot"));if(f&&f.length){e=f;break a}}e=void 0}f=e;d&&("slot"===a.localName||f)&&d.J();if(P(a)){e=c;Bb(a);a.__shady=a.__shady||{};void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){for(var g=b.childNodes,h=0;h<g.length;h++)Tb(g[h],a,e);b.__shady=b.__shady||{};e=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=
b.__shady.lastChild=e;b.__shady.childNodes=e}else Tb(b,a,e);if(Oa(a)){a.__shady.root.J();var m=!0}else a.__shady.root&&(m=!0)}m||(m=E(a)?a.host:a,c?(c=Ub(c),Pa.call(m,b,c)):Vb.call(m,b));Wb(a,b);f&&d.Ja(f);return b}function Na(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=U(b);if(P(a)){b.__shady=b.__shady||{};a.__shady=a.__shady||{};b===a.__shady.firstChild&&(a.__shady.firstChild=b.__shady.nextSibling);b===a.__shady.lastChild&&(a.__shady.lastChild=
b.__shady.previousSibling);var d=b.__shady.previousSibling;var e=b.__shady.nextSibling;d&&(d.__shady=d.__shady||{},d.__shady.nextSibling=e);e&&(e.__shady=e.__shady||{},e.__shady.previousSibling=d);b.__shady.parentNode=b.__shady.previousSibling=b.__shady.nextSibling=void 0;void 0!==a.__shady.childNodes&&(a.__shady.childNodes=null);if(Oa(a)){a.__shady.root.J();var f=!0}}Xb(b);c&&((e=a&&"slot"===a.localName)&&(f=!0),((d=c.Ma(b))||e)&&c.J());f||(f=E(a)?a.host:a,(!a.__shady.root&&"slot"!==b.localName||
f===Q(b))&&W.call(f,b));Wb(a,null,b);return b}function Xb(a){if(a.__shady&&void 0!==a.__shady.ia)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)Xb(e);a.__shady&&(a.__shady.ia=void 0)}function Ub(a){var b=a;a&&"slot"===a.localName&&(b=(b=a.__shady&&a.__shady.P)&&b.length?b[0]:Ub(a.nextSibling));return b}function Oa(a){return(a=a&&a.__shady&&a.__shady.root)&&a.na()}function Yb(a,b){"slot"===b?(a=a.parentNode,Oa(a)&&a.__shady.root.J()):"slot"===a.localName&&"name"===b&&(b=U(a))&&(b.Oa(a),
b.J())}function Wb(a,b,c){if(a=a.__shady&&a.__shady.S)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),a.$a()}function Zb(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.ia;void 0===b&&(E(a)?b=a:b=(b=a.parentNode)?Zb(b):a,document.documentElement.contains(a)&&(a.__shady.ia=b));return b}}function ja(a,b,c){var d=[];$b(a.childNodes,b,c,d);return d}function $b(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var m=b,k=c,l=d,n=m(h);n&&l.push(h);
k&&k(n)?h=n:($b(h.childNodes,m,k,l),h=void 0)}if(h)break}}function ac(a){a=a.getRootNode();E(a)&&a.pa()}function bc(a,b,c){ka||(ka=window.ShadyCSS&&window.ShadyCSS.ScopingShim);ka&&"class"===b?ka.setElementClass(a,c):(cc.call(a,b,c),Yb(a,b))}function dc(a,b){if(a.ownerDocument!==document)return Qa.call(document,a,b);var c=Qa.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=dc(a[b],!0),c.appendChild(d)}return c}function Ra(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),
d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function ec(a,b){if(!E)return a;a=Ra(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!E(f)||-1<g)return d}function Sa(a){function b(b,d){b=new a(b,d);b.ca=d&&!!d.composed;return b}ld(b,a);b.prototype=a.prototype;return b}function fc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&
b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&a.target!==a.relatedTarget&&(e.call(b,a),!a.Ea);d++);}function rd(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];fc(a,d,"capture");if(a.da)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=d.__shady&&d.__shady.root;if(0===c||f&&f===e)if(fc(a,d,"bubble"),d!==window&&(e=
d.getRootNode()),a.da)break}}function gc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],m=h.type,k=h.capture,l=h.once,n=h.passive;if(b===h.node&&c===m&&d===k&&e===l&&f===n)return g}return-1}function hc(a,b,c){if(b){if("object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.ea||this,h=b[X];if(h){if(-1<gc(h,g,a,d,e,f))return}else b[X]=[];h=function(d){e&&this.removeEventListener(a,b,c);d.__target||ic(d);if(g!==this){var f=Object.getOwnPropertyDescriptor(d,
"currentTarget");Object.defineProperty(d,"currentTarget",{get:function(){return g},configurable:!0})}if(d.composed||-1<d.composedPath().indexOf(g))if(d.target===d.relatedTarget)d.eventPhase===Event.BUBBLING_PHASE&&d.stopImmediatePropagation();else if(d.eventPhase===Event.CAPTURING_PHASE||d.bubbles||d.target===g){var h="object"===typeof b&&b.handleEvent?b.handleEvent(d):b.call(g,d);g!==this&&(f?(Object.defineProperty(d,"currentTarget",f),f=null):delete d.currentTarget);return h}};b[X].push({node:this,
type:a,capture:d,once:e,passive:f,eb:h});Ta[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][d?"capture":"bubble"].push(h)):(this instanceof Window?jc:kc).call(this,a,h,c)}}function lc(a,b,c){if(b){if("object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.ea||this,h=void 0;var m=null;try{m=b[X]}catch(ae){}m&&(e=gc(m,g,a,d,e,f),-1<e&&(h=m.splice(e,1)[0].eb,m.length||(b[X]=void 0)));
(this instanceof Window?mc:nc).call(this,a,h||b,c);h&&Ta[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}function sd(){for(var a in Ta)window.addEventListener(a,function(a){a.__target||(ic(a),rd(a))},!0)}function ic(a){a.__target=a.target;a.la=a.relatedTarget;if(B.R){var b=oc,c=Object.getPrototypeOf(a);if(!c.hasOwnProperty("__patchProto")){var d=Object.create(c);d.gb=c;Ea(d,b);c.__patchProto=d}a.__proto__=c.__patchProto}else Ea(a,
oc)}function Y(a,b){return{index:a,T:[],V:b}}function td(a,b,c,d){var e=0,f=0,g=0,h=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){h=a.length;for(var k=c.length,l=0;l<m-g&&ud(a[--h],c[--k]);)l++;h=l}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Y(e,0);f<d;)b.T.push(c[f++]);return[b]}if(f==d)return[Y(e,b-e)];m=e;g=f;d=d-g+1;h=b-m+1;b=Array(d);for(k=0;k<d;k++)b[k]=Array(h),b[k][0]=k;for(k=0;k<h;k++)b[0][k]=k;for(k=1;k<d;k++)for(l=
1;l<h;l++)if(a[m+l-1]===c[g+k-1])b[k][l]=b[k-1][l-1];else{var n=b[k-1][l]+1,p=b[k][l-1]+1;b[k][l]=n<p?n:p}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)0==m?(a.push(2),g--):0==g?(a.push(3),m--):(h=b[m-1][g-1],k=b[m-1][g],l=b[m][g-1],n=k<l?k<h?k:h:l<h?l:h,n==h?(h==d?a.push(0):(a.push(1),d=h),m--,g--):n==k?(a.push(3),m--,d=k):(a.push(2),g--,d=l));a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Y(e,0));b.V++;e++;b.T.push(c[f]);
f++;break;case 2:b||(b=Y(e,0));b.V++;e++;break;case 3:b||(b=Y(e,0)),b.T.push(c[f]),f++}b&&m.push(b);return m}function ud(a,b){return a===b}function pc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}function qc(a){ac(a);return a.__shady&&a.__shady.assignedSlot||null}function I(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}}function vd(){var a=window.customElements&&window.customElements.nativeHTMLElement||
HTMLElement;I(window.Node.prototype,wd);I(window.Window.prototype,xd);I(window.Text.prototype,yd);I(window.DocumentFragment.prototype,Ua);I(window.Element.prototype,rc);I(window.Document.prototype,sc);window.HTMLSlotElement&&I(window.HTMLSlotElement.prototype,tc);I(a.prototype,zd);B.R&&(L(window.Node.prototype),L(window.Text.prototype),L(window.DocumentFragment.prototype),L(window.Element.prototype),L(a.prototype),L(window.Document.prototype),window.HTMLSlotElement&&L(window.HTMLSlotElement.prototype))}
function uc(a){var b=Ad.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function n(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}function Va(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function K(a,b,c){c=c?c:new Set;for(var d=a;d;){if(d.nodeType===
Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)K(d,b,c);d=Va(a,e);continue}else if("template"===f){d=Va(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)K(e,b,c)}d=d.firstChild?d.firstChild:Va(a,d)}}function x(a,b,c){a[b]=c}function Wa(a){a=a.replace(D.Sa,"").replace(D.port,"");var b=vc,c=a,d=new ua;d.start=0;d.end=c.length;for(var e=
d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new ua;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}function vc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Bd(c),c=c.replace(D.va," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===
c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=G.MEDIA_RULE:c.match(D.Wa)&&(a.type=G.ba,a.keyframesName=a.selector.split(D.va).pop()):a.type=0===c.indexOf("--")?G.ja:G.STYLE_RULE);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)vc(f,b);return a}function Bd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}function wc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===
f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=wc(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(D.qa,"").replace(D.ua,""),b=b.replace(D.Xa,"").replace(D.bb,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}function xc(a){w=a&&a.shimcssproperties?!1:u||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}function R(a,b){if(!a)return"";
"string"===typeof a&&(a=Wa(a));b&&S(a,b);return wc(a,w)}function la(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Wa(a.textContent));return a.__cssRules||null}function yc(a){return!!a.parent&&a.parent.type===G.ba}function S(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===G.MEDIA_RULE){var g=a.selector.match(Cd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===G.STYLE_RULE?b(a):c&&f===G.ba?c(a):f===G.ja&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)S(h,b,c,d)}}}function Xa(a,b,
c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;zc(e,c,d);return e}function zc(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);M?a.compareDocumentPosition(M)===Node.DOCUMENT_POSITION_PRECEDING&&(M=a):M=a}function Ac(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=Ac(a.substring(e+
1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function ma(a,b){u?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function N(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,U:c}}function Bc(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=
c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(t.c);(g=-1<h?g[h+1]:"")&&f===e.ownerDocument?t.a(e,g,!0):f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=f.host)&&(f=N(f).is,g!==f&&(g&&t.a(e,g,!0),t.a(e,f)))}}}}function Dd(a){if(a=na[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=
a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Cc(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ed(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,Fd.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))}function lb(a){requestAnimationFrame(function(){Dc?Dc(a):(Ya||(Ya=new Promise(function(a){Za=a}),"complete"===document.readyState?Za():document.addEventListener("readystatechange",
function(){"complete"===document.readyState&&Za()})),Ya.then(function(){a&&a()}))})}function Ec(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function Fc(){Ec();$a.removeEventListener("readystatechange",Fc)}var B=window.ShadyDOM||{};B.Ta=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ab=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");B.R=!!(ab&&ab.configurable&&
ab.get);B.ta=B.force||!B.Ta;var T=Element.prototype,Gc=T.matches||T.matchesSelector||T.mozMatchesSelector||T.msMatchesSelector||T.oMatchesSelector||T.webkitMatchesSelector,Ha=document.createTextNode(""),Eb=0,Ga=[];(new MutationObserver(function(){for(;Ga.length;)try{Ga.shift()()}catch(a){throw Ha.textContent=Eb++,a;}})).observe(Ha,{characterData:!0});var V=[],Ia;ia.list=V;ha.prototype.$a=function(){var a=this;this.a||(this.a=!0,Db(function(){a.b()}))};ha.prototype.b=function(){if(this.a){this.a=!1;
var a=this.takeRecords();a.length&&this.W.forEach(function(b){b(a)})}};ha.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};var Vb=Element.prototype.appendChild,Pa=Element.prototype.insertBefore,W=Element.prototype.removeChild,cc=Element.prototype.setAttribute,Hc=Element.prototype.removeAttribute,bb=Element.prototype.cloneNode,Qa=Document.prototype.importNode,
kc=Element.prototype.addEventListener,nc=Element.prototype.removeEventListener,jc=Window.prototype.addEventListener,mc=Window.prototype.removeEventListener,cb=Element.prototype.dispatchEvent,Gd=Object.freeze({appendChild:Vb,insertBefore:Pa,removeChild:W,setAttribute:cc,removeAttribute:Hc,cloneNode:bb,importNode:Qa,addEventListener:kc,removeEventListener:nc,kb:jc,lb:mc,dispatchEvent:cb,querySelector:Element.prototype.querySelector,querySelectorAll:Element.prototype.querySelectorAll}),nd=/[&\u00A0"]/g,
qd=/[&\u00A0<>]/g,od=Hb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),pd=Hb("style script xmp iframe noembed noframes plaintext noscript".split(" ")),z=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),A=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Hd=Object.freeze({parentNode:Q,firstChild:Ca,lastChild:Da,previousSibling:Ib,nextSibling:Jb,childNodes:O,parentElement:Kb,firstElementChild:Lb,lastElementChild:Mb,
previousElementSibling:Nb,nextElementSibling:Ob,children:Pb,innerHTML:Qb,textContent:Rb}),db=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),oa=document.implementation.createHTMLDocument("inert").createElement("div"),eb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),Sb={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==
a?a:Kb(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;return void 0!==a?a:Q(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:Jb(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:Ib(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",
a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Ob(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return Nb(this)},configurable:!0}},Ka={childNodes:{get:function(){if(P(this)){if(!this.__shady.childNodes){this.__shady.childNodes=
[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}var b=this.__shady.childNodes}else b=O(this);b.item=function(a){return b[a]};return b},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:Ca(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:Da(this)},configurable:!0},textContent:{get:function(){if(P(this)){for(var a=
[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return Rb(this)},set:function(a){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(;this.firstChild;)this.removeChild(this.firstChild);(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=
this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Lb(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return Mb(this)},configurable:!0},children:{get:function(){var a;P(this)?a=Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):a=Pb(this);a.item=function(b){return a[b]};return a},
configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return P(this)?Ja(a):Qb(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);for(db&&db.set?db.set.call(oa,a):oa.innerHTML=a;oa.firstChild;)b.appendChild(oa.firstChild)},configurable:!0}},Ic={shadowRoot:{get:function(){return this.__shady&&this.__shady.Ya||null},configurable:!0}},La={activeElement:{get:function(){var a=eb&&eb.get?eb.get.call(document):
B.R?void 0:document.activeElement;if(a&&a.nodeType){var b=!!E(this);if(this===document||b&&this.host!==a&&this.host.contains(a)){for(b=U(a);b&&b!==this;)a=b.host,b=U(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}},Cb=B.R?function(){}:function(a){a.__shady&&a.__shady.Ha||(a.__shady=a.__shady||{},a.__shady.Ha=!0,H(a,Sb,!0))},Bb=B.R?function(){}:function(a){a.__shady&&a.__shady.Fa||(a.__shady=a.__shady||{},a.__shady.Fa=!0,H(a,Ka,!0),
H(a,Ic,!0))},ka=null,X="__eventWrappers"+Date.now(),Id={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,
lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},oc={get composed(){!1!==this.isTrusted&&void 0===this.ca&&(this.ca=Id[this.type]);return this.ca||!1},composedPath:function(){this.ka||(this.ka=Ra(this.__target,this.composed));return this.ka},get target(){return ec(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.la)return null;this.ma||(this.ma=Ra(this.la,!0));return ec(this.currentTarget,
this.ma)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.da=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.da=this.Ea=!0}},Ta={focus:!0,blur:!0},Jd=Sa(window.Event),Kd=Sa(window.CustomEvent),Ld=Sa(window.MouseEvent),Ab={};l.prototype=Object.create(DocumentFragment.prototype);l.prototype.B=function(a,b){this.Ga="ShadyRoot";fa(a);fa(this);this.host=a;this.I=b&&b.mode;a.__shady=a.__shady||{};a.__shady.root=this;a.__shady.Ya=
"closed"!==this.I?this:null;this.O=!1;this.b=[];this.a=null;b=O(a);for(var c=0,d=b.length;c<d;c++)W.call(a,b[c])};l.prototype.J=function(){var a=this;this.O||(this.O=!0,Fb(function(){return a.pa()}))};l.prototype.A=function(){for(var a=this,b=this;b;)b.O&&(a=b),b=b.Na();return a};l.prototype.Na=function(){var a=this.host.getRootNode();if(E(a))for(var b=this.host.childNodes,c=0,d;c<b.length;c++)if(d=b[c],this.h(d))return a};l.prototype.pa=function(){this.O&&this.A()._renderRoot()};l.prototype._renderRoot=
function(){this.O=!1;this.u();this.m()};l.prototype.u=function(){for(var a=0,b;a<this.b.length;a++)b=this.b[a],this.l(b);for(b=this.host.firstChild;b;b=b.nextSibling)this.f(b);for(a=0;a<this.b.length;a++){b=this.b[a];if(!b.__shady.assignedNodes.length)for(var c=b.firstChild;c;c=c.nextSibling)this.f(c,b);c=b.parentNode;(c=c.__shady&&c.__shady.root)&&c.na()&&c._renderRoot();this.c(b.__shady.P,b.__shady.assignedNodes);if(c=b.__shady.oa){for(var d=0;d<c.length;d++)c[d].__shady.fa=null;b.__shady.oa=null;
c.length>b.__shady.assignedNodes.length&&(b.__shady.ga=!0)}b.__shady.ga&&(b.__shady.ga=!1,this.g(b))}};l.prototype.f=function(a,b){a.__shady=a.__shady||{};var c=a.__shady.fa;a.__shady.fa=null;b||(b=(b=this.a[a.slot||"__catchall"])&&b[0]);b?(b.__shady.assignedNodes.push(a),a.__shady.assignedSlot=b):a.__shady.assignedSlot=void 0;c!==a.__shady.assignedSlot&&a.__shady.assignedSlot&&(a.__shady.assignedSlot.__shady.ga=!0)};l.prototype.l=function(a){var b=a.__shady.assignedNodes;a.__shady.assignedNodes=
[];a.__shady.P=[];if(a.__shady.oa=b)for(var c=0;c<b.length;c++){var d=b[c];d.__shady.fa=d.__shady.assignedSlot;d.__shady.assignedSlot===a&&(d.__shady.assignedSlot=null)}};l.prototype.c=function(a,b){for(var c=0,d;c<b.length&&(d=b[c]);c++)"slot"==d.localName?this.c(a,d.__shady.assignedNodes):a.push(b[c])};l.prototype.g=function(a){cb.call(a,new Event("slotchange"));a.__shady.assignedSlot&&this.g(a.__shady.assignedSlot)};l.prototype.m=function(){for(var a=this.b,b=[],c=0;c<a.length;c++){var d=a[c].parentNode;
d.__shady&&d.__shady.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.G(c===this?this.host:c,this.o(c))};l.prototype.o=function(a){var b=[];a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(this.h(d)){d=d.__shady.P;for(var e=0;e<d.length;e++)b.push(d[e])}else b.push(d)}return b};l.prototype.h=function(a){return"slot"==a.localName};l.prototype.G=function(a,b){for(var c=O(a),d=td(b,b.length,c,c.length),e=0,f=0,g;e<d.length&&(g=d[e]);e++){for(var h=0,k;h<g.T.length&&(k=g.T[h]);h++)Q(k)===
a&&W.call(a,k),c.splice(g.index+f,1);f-=g.V}for(e=0;e<d.length&&(g=d[e]);e++)for(f=c[g.index],h=g.index;h<g.index+g.V;h++)k=b[h],Pa.call(a,k,f),c.splice(h,0,k)};l.prototype.Ja=function(a){this.a=this.a||{};this.b=this.b||[];for(var b=0;b<a.length;b++){var c=a[b];c.__shady=c.__shady||{};fa(c);fa(c.parentNode);var d=this.i(c);if(this.a[d]){var e=e||{};e[d]=!0;this.a[d].push(c)}else this.a[d]=[c];this.b.push(c)}if(e)for(var f in e)this.a[f]=this.j(this.a[f])};l.prototype.i=function(a){var b=a.name||
a.getAttribute("name")||"__catchall";return a.Ia=b};l.prototype.j=function(a){return a.sort(function(a,c){a=pc(a);for(var b=pc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})};l.prototype.Ma=function(a){this.a=this.a||{};this.b=this.b||[];var b=this.a,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e],g;a:{for(g=f;g;){if(g==a){g=!0;break a}g=g.parentNode}g=void 0}if(g){d.splice(e,1);var h=this.b.indexOf(f);0<=h&&this.b.splice(h,
1);e--;this.F(f);h=!0}}return h};l.prototype.Oa=function(a){var b=a.Ia,c=this.i(a);if(c!==b){b=this.a[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.a[c]||(this.a[c]=[]);b.push(a);1<b.length&&(this.a[c]=this.j(b))}};l.prototype.F=function(a){if(a=a.__shady.P)for(var b=0;b<a.length;b++){var c=a[b],d=Q(c);d&&W.call(d,c)}};l.prototype.na=function(){return!!this.b.length};l.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.ea=this;this.host.addEventListener(a,b,c)};
l.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.ea=this;this.host.removeEventListener(a,b,c)};l.prototype.getElementById=function(a){return ja(this,function(b){return b.id==a},function(a){return!!a})[0]||null};(function(a){H(a,Ka,!0);H(a,La,!0)})(l.prototype);var xd={addEventListener:hc.bind(window),removeEventListener:lc.bind(window)},wd={addEventListener:hc,removeEventListener:lc,appendChild:function(a){return Ma(this,a)},insertBefore:function(a,b){return Ma(this,
a,b)},removeChild:function(a){return Na(this,a)},replaceChild:function(a,b){Ma(this,a,b);Na(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=bb.call(this,a);else if(b=bb.call(this,!1),a){a=this.childNodes;for(var c=0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Zb(this)},get isConnected(){var a=this.ownerDocument;if(a&&a.contains&&a.contains(this)||(a=a.documentElement)&&a.contains&&a.contains(this))return!0;for(a=this;a&&
!(a instanceof Document);)a=a.parentNode||(a instanceof l?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){ia();return cb.call(this,a)}},yd={get assignedSlot(){return qc(this)}},Ua={querySelector:function(a){return ja(this,function(b){return Gc.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return ja(this,function(b){return Gc.call(b,a)})}},tc={assignedNodes:function(a){if("slot"===this.localName)return ac(this),this.__shady?(a&&a.flatten?this.__shady.P:
this.__shady.assignedNodes)||[]:[]}},rc=Fa({setAttribute:function(a,b){bc(this,a,b)},removeAttribute:function(a){Hc.call(this,a);Yb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new l(Ab,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){bc(this,"slot",a)},get assignedSlot(){return qc(this)}},Ua,tc);Object.defineProperties(rc,Ic);var sc=Fa({importNode:function(a,b){return dc(a,b)},getElementById:function(a){return ja(this,
function(b){return b.id==a},function(a){return!!a})[0]||null}},Ua);Object.defineProperties(sc,{_activeElement:La.activeElement});var Md=HTMLElement.prototype.blur,zd=Fa({blur:function(){var a=this.__shady&&this.__shady.root;(a=a&&a.activeElement)?a.blur():Md.call(this)}});B.ta&&(window.ShadyDOM={inUse:B.ta,patch:function(a){return a},isShadyRoot:E,enqueue:Fb,flush:ia,settings:B,filterMutations:md,observeChildren:kd,unobserveChildren:jd,nativeMethods:Gd,nativeTree:Hd},window.Event=Jd,window.CustomEvent=
Kd,window.MouseEvent=Ld,sd(),vd(),window.ShadowRoot=l);var Ad=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));y.prototype.B=function(a,b){this.o.set(a,b);this.m.set(b.constructor,b)};y.prototype.c=function(a){return this.o.get(a)};y.prototype.A=function(a){return this.m.get(a)};y.prototype.u=function(a){this.h=!0;this.j.push(a)};y.prototype.l=function(a){var b=this;this.h&&K(a,function(a){return b.g(a)})};y.prototype.g=
function(a){if(this.h&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.j.length;b++)this.j[b](a)}};y.prototype.b=function(a){var b=[];K(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state?this.connectedCallback(c):this.i(c)}};y.prototype.a=function(a){var b=[];K(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};y.prototype.f=function(a,b){var c=this;b=b?b:{};var d=b.cb||new Set,e=b.xa||function(a){return c.i(a)},
f=[];K(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var b=a.import;b instanceof Node&&"complete"===b.readyState?(b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0):a.addEventListener("load",function(){var b=a.import;b.__CE_documentLoadHandled||(b.__CE_documentLoadHandled=!0,b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0,d.delete(b),c.f(b,{cb:d,xa:e}))})}else f.push(a)},d);if(this.h)for(a=0;a<f.length;a++)this.g(f[a]);for(a=0;a<f.length;a++)e(f[a])};y.prototype.i=function(a){if(void 0===
a.__CE_state){var b=this.c(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}n(a)&&this.connectedCallback(a)}}};
y.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};y.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};y.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};Ba.prototype.c=function(){this.K&&this.K.disconnect()};Ba.prototype.f=function(a){var b=
this.a.readyState;"interactive"!==b&&"complete"!==b||this.c();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this.b.f(c[d])};zb.prototype.c=function(){if(this.a)throw Error("Already resolved.");this.a=void 0;this.b&&this.b(void 0)};v.prototype.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!uc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.c(a))throw Error("A custom element with name '"+
a+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=
b.observedAttributes||[]}catch(ca){return}finally{this.c=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};this.a.B(a,b);this.g.push(b);this.b||(this.b=!0,this.f(function(){return c.j()}))};v.prototype.j=function(){var a=this;if(!1!==this.b){this.b=!1;for(var b=this.g,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);this.a.f(document,{xa:function(b){if(void 0===b.__CE_state){var e=
b.localName,f=d.get(e);f?f.push(b):a.a.c(e)&&c.push(b)}}});for(e=0;e<c.length;e++)this.a.i(c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)this.a.i(f[g]);(e=this.h.get(e))&&e.c()}}};v.prototype.get=function(a){if(a=this.a.c(a))return a.constructor};v.prototype.whenDefined=function(a){if(!uc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.h.get(a);if(b)return b.f;b=new zb;this.h.set(a,b);this.a.c(a)&&
!this.g.some(function(b){return b.localName===a})&&b.c();return b.f};v.prototype.l=function(a){this.i.c();var b=this.f;this.f=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=v;v.prototype.define=v.prototype.define;v.prototype.get=v.prototype.get;v.prototype.whenDefined=v.prototype.whenDefined;v.prototype.polyfillWrapFlushCallback=v.prototype.l;var xa=window.Document.prototype.createElement,ed=window.Document.prototype.createElementNS,dd=window.Document.prototype.importNode,
fd=window.Document.prototype.prepend,gd=window.Document.prototype.append,ob=window.Node.prototype.cloneNode,da=window.Node.prototype.appendChild,wb=window.Node.prototype.insertBefore,ya=window.Node.prototype.removeChild,xb=window.Node.prototype.replaceChild,Aa=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),nb=window.Element.prototype.attachShadow,va=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),za=window.Element.prototype.getAttribute,pb=window.Element.prototype.setAttribute,
rb=window.Element.prototype.removeAttribute,ea=window.Element.prototype.getAttributeNS,qb=window.Element.prototype.setAttributeNS,sb=window.Element.prototype.removeAttributeNS,ub=window.Element.prototype.insertAdjacentElement,Vc=window.Element.prototype.prepend,Wc=window.Element.prototype.append,Yc=window.Element.prototype.before,Zc=window.Element.prototype.after,$c=window.Element.prototype.replaceWith,ad=window.Element.prototype.remove,id=window.HTMLElement,wa=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,
"innerHTML"),tb=window.HTMLElement.prototype.insertAdjacentElement,yb=new function(){},pa=window.customElements;if(!pa||pa.forcePolyfill||"function"!=typeof pa.define||"function"!=typeof pa.get){var Z=new y;hd(Z);cd(Z);bd(Z);Uc(Z);document.__CE_hasRegistry=!0;var Nd=new v(Z);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:Nd})}var G={STYLE_RULE:1,ba:7,MEDIA_RULE:4,ja:1E3},D={Sa:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,qa:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,
ua:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Xa:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,bb:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Wa:/^@[^\s]*keyframes/,va:/\s+/g},u=!(window.ShadyDOM&&window.ShadyDOM.inUse);if(window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss)var w=window.ShadyCSS.nativeCss;else window.ShadyCSS?(xc(window.ShadyCSS),window.ShadyCSS=void 0):xc(window.WebComponents&&window.WebComponents.flags);var qa=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,
ra=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Od=/(--[\w-]+)\s*([:,;)]|$)/gi,Pd=/(animation\s*:)|(animation-name\s*:)/,Cd=/@media\s(.*)/,Qd=/\{[^}]*\}/g,M=null;q.prototype.a=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this.i(a,b||"",c)};q.prototype.i=function(a,b,c){a.nodeType===Node.ELEMENT_NODE&&this.A(a,b,c);if(a="template"===a.localName?(a.content||a.hb).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this.i(a[d],b,c)};q.prototype.A=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),
a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Rd);c?d&&(b=d.replace("style-scope","").replace(b,""),ma(a,b)):ma(a,(d?d+" ":"")+"style-scope "+b)}};q.prototype.b=function(a,b,c){var d=a.__cssBuild;u||"shady"===d?b=R(b,c):(a=N(a),b=this.G(b,a.is,a.U,c)+"\n\n");return b.trim()};q.prototype.G=function(a,b,c,d){var e=this.f(b,c);b=this.h(b);var f=this;return R(a,function(a){a.c||(f.N(a,b,e),a.c=!0);d&&d(a,b,e)})};q.prototype.h=function(a){return a?
Sd+a:""};q.prototype.f=function(a,b){return b?"[is="+a+"]":a};q.prototype.N=function(a,b,c){this.j(a,this.g,b,c)};q.prototype.j=function(a,b,c,d){a.selector=a.v=this.l(a,b,c,d)};q.prototype.l=function(a,b,c,d){var e=a.selector.split(Jc);if(!yc(a)){a=0;for(var f=e.length,g;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.join(Jc)};q.prototype.o=function(a){return a.replace(fb,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+
d+")"})};q.prototype.g=function(a,b,c){var d=this,e=!1;a=a.trim();var f=fb.test(a);f&&(a=a.replace(fb,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=this.o(a));a=a.replace(Td,gb+" $1");a=a.replace(Ud,function(a,f,k){e||(a=d.B(k,f,b,c),e=e||a.stop,f=a.Ra,k=a.value);return f+k});f&&(a=this.o(a));return a};q.prototype.B=function(a,b,c,d){var e=a.indexOf(hb);0<=a.indexOf(gb)?a=this.F(a,d):0!==e&&(a=c?this.m(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Vd,function(a,b){return" > "+
b}))}a=a.replace(Wd,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,Ra:b,stop:f}};q.prototype.m=function(a,b){a=a.split(Kc);a[0]+=b;return a.join(Kc)};q.prototype.F=function(a,b){var c=a.match(Lc);return(c=c&&c[2].trim()||"")?c[0].match(Mc)?a.replace(Lc,function(a,c,f){return b+f}):c.split(Mc)[0]===b?c:Xd:a.replace(gb,b)};q.prototype.M=function(a){a.selector=a.parsedSelector;this.u(a);this.j(a,this.I)};q.prototype.u=function(a){a.selector===Yd&&(a.selector="html")};
q.prototype.I=function(a){return a.match(hb)?this.g(a,Nc):this.m(a.trim(),Nc)};kb.Object.defineProperties(q.prototype,{c:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var fb=/:(nth[-\w]+)\(([^)]+)\)/,Nc=":not(.style-scope)",Jc=",",Ud=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Mc=/[[.:#*]/,gb=":host",Yd=":root",hb="::slotted",Td=new RegExp("^("+hb+")"),Lc=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Vd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Wd=/(.*):dir\((?:(ltr|rtl))\)/,
Sd=".",Kc=":",Rd="class",Xd="should_not_match",t=new q;r.get=function(a){return a?a.__styleInfo:null};r.set=function(a,b){return a.__styleInfo=b};r.prototype.c=function(){return this.D};r.prototype._getStyleRules=r.prototype.c;var Oc=function(a){return a.matches||a.matchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),Zd=navigator.userAgent.match("Trident");p.prototype.M=function(a){var b=this,c={},d=[],e=0;S(a,function(a){b.c(a);
a.index=e++;b.G(a.s.cssText,c)},function(a){d.push(a)});a.b=d;a=[];for(var f in c)a.push(f);return a};p.prototype.c=function(a){if(!a.s){var b={},c={};this.b(a,c)&&(b.C=c,a.rules=null);b.cssText=this.F(a);a.s=b}};p.prototype.b=function(a,b){var c=a.s;if(c){if(c.C)return Object.assign(b,c.C),!0}else{c=a.parsedCssText;for(var d;a=qa.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};p.prototype.F=function(a){return this.I(a.parsedCssText)};p.prototype.I=function(a){return a.replace(Qd,
"").replace(qa,"")};p.prototype.G=function(a,b){for(var c;c=Od.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};p.prototype.Z=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.a(a[d],a)};p.prototype.a=function(a,b){if(a)if(0<=a.indexOf(";"))a=this.f(a,b);else{var c=this;a=Ac(a,function(a,e,f,g){if(!e)return a+g;(e=c.a(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.a(b[f]||f,b)||f;return a+(e||"")+g})}return a&&a.trim()||""};p.prototype.f=function(a,
b){a=a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){ra.lastIndex=0;if(e=ra.exec(d))d=this.a(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e);f=f.trim();f=this.a(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return a.join(";")};p.prototype.B=function(a,b){var c="";a.s||this.c(a);a.s.cssText&&(c=this.f(a.s.cssText,b));a.cssText=c};p.prototype.A=function(a,b){var c=a.cssText,d=a.cssText;null==a.sa&&(a.sa=Pd.test(c));if(a.sa)if(null==
a.X){a.X=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.X.push(e))}else{for(e=0;e<a.X.length;++e)d=b[a.X[e]],c=d(c);d=c}a.cssText=d};p.prototype.Y=function(a,b){var c={},d=this,e=[];S(a,function(a){a.s||d.c(a);var f=a.v||a.parsedSelector;b&&a.s.C&&f&&Oc.call(b,f)&&(d.b(a,c),a=a.index,f=parseInt(a/32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{C:c,key:e}};p.prototype.aa=function(a,b,c,d){b.s||this.c(b);if(b.s.C){var e=N(a);a=e.is;e=e.U;e=a?t.f(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||
"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(u&&!b.v&&(b.v=t.l(b,t.g,t.h(a),e)),c=b.v||e),d({ab:c,Va:h,jb:g})}};p.prototype.N=function(a,b){var c={},d={},e=this,f=b&&b.__cssBuild;S(b,function(b){e.aa(a,b,f,function(f){Oc.call(a.ib||a,f.ab)&&(f.Va?e.b(b,c):e.b(b,d))})},null,!0);return{Za:d,Ua:c}};p.prototype.$=function(a,b,c){var d=this,e=N(a),f=t.f(e.is,
e.U),g=new RegExp("(?:^|[^.#[:])"+(a.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=r.get(a).D;var h=this.h(e,c);return t.b(a,e,function(a){d.B(a,b);u||yc(a)||!a.cssText||(d.A(a,h),d.l(a,g,f,c))})};p.prototype.h=function(a,b){a=a.b;var c={};if(!u&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.j(e,b),c[e.keyframesName]=this.i(e);return c};p.prototype.i=function(a){return function(b){return b.replace(a.f,a.a)}};p.prototype.j=function(a,b){a.f=new RegExp(a.keyframesName,"g");a.a=a.keyframesName+
"-"+b;a.v=a.v||a.selector;a.selector=a.v.replace(a.keyframesName,a.a)};p.prototype.l=function(a,b,c,d){a.v=a.v||a.selector;d="."+d;for(var e=a.v.split(","),f=0,g=e.length,h;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};p.prototype.o=function(a,b,c){var d=a.getAttribute("class")||"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":"")+"x-scope "+b;d!==e&&ma(a,e)};p.prototype.u=function(a,b,c,d){b=d?d.textContent||"":this.$(a,b,c);var e=
r.get(a),f=e.a;f&&!u&&f!==d&&(f._useCount--,0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));u?e.a?(e.a.textContent=b,d=e.a):b&&(d=Xa(b,c,a.shadowRoot,e.b)):d?d.parentNode||(Zd&&-1<b.indexOf("@media")&&(d.textContent=b),zc(d,null,e.b)):b&&(d=Xa(b,c,null,e.b));d&&(d._useCount=d._useCount||0,e.a!=d&&d._useCount++,e.a=d);return d};p.prototype.m=function(a,b){var c=la(a),d=this;a.textContent=R(c,function(a){var c=a.cssText=a.parsedCssText;a.s&&a.s.cssText&&(c=c.replace(D.qa,"").replace(D.ua,
""),a.cssText=d.f(c,b))})};kb.Object.defineProperties(p.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var J=new p,ib={},sa=window.customElements;if(sa&&!u){var $d=sa.define;sa.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(M?M.nextSibling:null)||e.firstChild);M=d;ib[a]=d;return $d.call(sa,a,b,c)}}ba.prototype.a=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.C[e]!==b[e])return!1}return!0};
ba.prototype.b=function(a,b,c,d){var e=this.cache[a]||[];e.push({C:b,styleElement:c,w:d});e.length>this.c&&e.shift();this.cache[a]=e};ba.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.a(e,b,c))return e}};if(!u){var Pc=new MutationObserver(Bc),Qc=function(a){Pc.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Qc(document);else{var jb=function(){Qc(document.body)};window.HTMLImports?
window.HTMLImports.whenReady(jb):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){jb();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else jb()})}mb=function(){Bc(Pc.takeRecords())}}var na={},Fd=Promise.resolve(),Ya=null,Dc=window.HTMLImports&&window.HTMLImports.whenReady||null,Za,ta=null,aa=null;C.prototype.ra=function(){!this.enqueued&&aa&&(this.enqueued=!0,lb(aa))};C.prototype.b=function(a){a.__seenByShadyCSS||
(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.ra())};C.prototype.a=function(a){return a.__shadyCSSCachedStyle?a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():a};C.prototype.c=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.a(c);d&&(d=d.__appliedElement||d,ta&&ta(d),c.__shadyCSSCachedStyle=d)}}return a};C.prototype.addCustomStyle=C.prototype.b;C.prototype.getStyleForCustomStyle=C.prototype.a;C.prototype.processStyles=C.prototype.c;
Object.defineProperties(C.prototype,{transformCallback:{get:function(){return ta},set:function(a){ta=a}},validateCallback:{get:function(){return aa},set:function(a){var b=!1;aa||(b=!0);aa=a;b&&this.ra()}}});var Rc=new ba;k.prototype.A=function(){mb()};k.prototype.N=function(a){var b=this.m[a]=(this.m[a]||0)+1;return a+"-"+b};k.prototype.Ba=function(a){return la(a)};k.prototype.Da=function(a){return R(a)};k.prototype.M=function(a){a=a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=
a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};k.prototype.Z=function(a){return(a=a.content.querySelector("style"))?a.getAttribute("css-build")||"":""};k.prototype.prepareTemplate=function(a,b,c){if(!a.f){a.f=!0;a.name=b;a.extends=c;na[b]=a;var d=this.Z(a),e=this.M(a);c={is:b,extends:c,fb:d};u||t.a(a.content,b);this.c();var f=ra.test(e)||qa.test(e);ra.lastIndex=0;qa.lastIndex=0;e=Wa(e);f&&w&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.g=d;d=[];w||(d=J.M(a._styleAst));
if(!d.length||w)b=this.Y(c,a._styleAst,u?a.content:null,ib[b]),a.a=b;a.c=d}};k.prototype.Y=function(a,b,c,d){b=t.b(a,b);if(b.length)return Xa(b,a.is,c,d)};k.prototype.aa=function(a){var b=N(a),c=b.is;b=b.U;var d=ib[c];c=na[c];if(c){var e=c._styleAst;var f=c.c}return r.set(a,new r(e,d,f,0,b))};k.prototype.F=function(){!this.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.a=window.ShadyCSS.ApplyShim,this.a.invalidCallback=Dd)};k.prototype.G=function(){var a=this;!this.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&
(this.b=window.ShadyCSS.CustomStyleInterface,this.b.transformCallback=function(b){a.u(b)},this.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.i)&&a.f()})})};k.prototype.c=function(){this.F();this.G()};k.prototype.f=function(){this.c();if(this.b){var a=this.b.processStyles();this.b.enqueued&&(w?this.za(a):(this.o(this.g,this.h),this.B(a)),this.b.enqueued=!1,this.i&&!w&&this.styleDocument())}};k.prototype.styleElement=function(a,b){var c=N(a).is,d=r.get(a);d||(d=this.aa(a));
this.j(a)||(this.i=!0);b&&(d.L=d.L||{},Object.assign(d.L,b));if(w){if(d.L){b=d.L;for(var e in b)null===e?a.style.removeProperty(e):a.style.setProperty(e,b[e])}if(((e=na[c])||this.j(a))&&e&&e.a&&!Cc(e)){if(Cc(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this.c(),this.a&&this.a.transformRules(e._styleAst,c),e.a.textContent=t.b(a,d.D),Ed(e);u&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=t.b(a,d.D));d.D=e._styleAst}}else this.o(a,d),d.ha&&d.ha.length&&this.I(a,d)};k.prototype.l=
function(a){return(a=a.getRootNode().host)?r.get(a)?a:this.l(a):this.g};k.prototype.j=function(a){return a===this.g};k.prototype.I=function(a,b){var c=N(a).is,d=Rc.fetch(c,b.H,b.ha),e=d?d.styleElement:null,f=b.w;b.w=d&&d.w||this.N(c);e=J.u(a,b.H,b.w,e);u||J.o(a,b.w,f);d||Rc.b(c,b.H,e,b.w)};k.prototype.o=function(a,b){var c=this.l(a),d=r.get(c);c=Object.create(d.H||null);var e=J.N(a,b.D);a=J.Y(d.D,a).C;Object.assign(c,e.Ua,a,e.Za);this.$(c,b.L);J.Z(c);b.H=c};k.prototype.$=function(a,b){for(var c in b){var d=
b[c];if(d||0===d)a[c]=d}};k.prototype.styleDocument=function(a){this.styleSubtree(this.g,a)};k.prototype.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this.j(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};k.prototype.za=function(a){for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&this.ya(c)}};k.prototype.B=function(a){for(var b=
0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);c&&J.m(c,this.h.H)}};k.prototype.u=function(a){var b=this,c=la(a);S(c,function(a){u?t.u(a):t.M(a);w&&(b.c(),b.a&&b.a.transformRule(a))});w?a.textContent=R(c):this.h.D.rules.push(c)};k.prototype.ya=function(a){if(w&&this.a){var b=la(a);this.c();this.a.transformRules(b);a.textContent=R(b)}};k.prototype.getComputedStyleValue=function(a,b){var c;w||(c=(r.get(a)||r.get(this.l(a))).H[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?
c.trim():""};k.prototype.Ca=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===t.c){c=d[e+1];break}}}c&&b.push(t.c,c);w||(c=r.get(a))&&c.w&&b.push(J.g,c.w);ma(a,b.join(" "))};k.prototype.Aa=function(a){return r.get(a)};k.prototype.flush=k.prototype.A;k.prototype.prepareTemplate=k.prototype.prepareTemplate;k.prototype.styleElement=k.prototype.styleElement;k.prototype.styleDocument=
k.prototype.styleDocument;k.prototype.styleSubtree=k.prototype.styleSubtree;k.prototype.getComputedStyleValue=k.prototype.getComputedStyleValue;k.prototype.setElementClass=k.prototype.Ca;k.prototype._styleInfoForNode=k.prototype.Aa;k.prototype.transformCustomStyleForDocument=k.prototype.u;k.prototype.getStyleAst=k.prototype.Ba;k.prototype.styleAstToString=k.prototype.Da;k.prototype.flushCustomStyles=k.prototype.f;Object.defineProperties(k.prototype,{nativeShadow:{get:function(){return u}},nativeCss:{get:function(){return w}}});
var F=new k;if(window.ShadyCSS){var Sc=window.ShadyCSS.ApplyShim;var Tc=window.ShadyCSS.CustomStyleInterface}window.ShadyCSS={ScopingShim:F,prepareTemplate:function(a,b,c){F.f();F.prepareTemplate(a,b,c)},styleSubtree:function(a,b){F.f();F.styleSubtree(a,b)},styleElement:function(a){F.f();F.styleElement(a)},styleDocument:function(a){F.f();F.styleDocument(a)},getComputedStyleValue:function(a,b){return F.getComputedStyleValue(a,b)},nativeCss:w,nativeShadow:u};Sc&&(window.ShadyCSS.ApplyShim=Sc);Tc&&(window.ShadyCSS.CustomStyleInterface=
Tc);var $a=window.document;window.WebComponents=window.WebComponents||{};"loading"!==$a.readyState?Ec():$a.addEventListener("readystatechange",Fc)})();}).call(this);

//# sourceMappingURL=webcomponents-sd-ce.js.map
