(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(){function Y(b){function a(f,a){Object.defineProperty(f,"innerHTML",{enumerable:a.enumerable,configurable:!0,get:a.get,set:function(f){var e=this,d=void 0;g(this)&&(d=[],r(this,function(b){b!==e&&d.push(b)}));a.set.call(this,f);if(d)for(var c=0;c<d.length;c++){var k=d[c];1===k.__CE_state&&b.disconnectedCallback(k)}this.ownerDocument.__CE_hasRegistry?b.f(this):b.l(this);return f}})}function d(f,a){n(f,"insertAdjacentElement",function(f,e){var d=g(e);f=a.call(this,f,e);d&&b.a(e);
g(f)&&b.b(e);return f})}H?n(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=H.call(this,b)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(w&&w.get)a(Element.prototype,w);else if(A&&A.get)a(HTMLElement.prototype,A);else{var c=B.call(document,"div");b.s(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return I.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?this.content:this;for(c.innerHTML=b;0<a.childNodes.length;)C.call(a,
a.childNodes[0]);for(;0<c.childNodes.length;)x.call(a,c.childNodes[0])}})})}n(Element.prototype,"setAttribute",function(a,e){if(1!==this.__CE_state)return J.call(this,a,e);var f=D.call(this,a);J.call(this,a,e);e=D.call(this,a);b.attributeChangedCallback(this,a,f,e,null)});n(Element.prototype,"setAttributeNS",function(a,e,d){if(1!==this.__CE_state)return K.call(this,a,e,d);var f=y.call(this,a,e);K.call(this,a,e,d);d=y.call(this,a,e);b.attributeChangedCallback(this,e,f,d,a)});n(Element.prototype,"removeAttribute",
function(a){if(1!==this.__CE_state)return L.call(this,a);var f=D.call(this,a);L.call(this,a);null!==f&&b.attributeChangedCallback(this,a,f,null,null)});n(Element.prototype,"removeAttributeNS",function(a,d){if(1!==this.__CE_state)return M.call(this,a,d);var f=y.call(this,a,d);M.call(this,a,d);var e=y.call(this,a,d);f!==e&&b.attributeChangedCallback(this,d,f,e,a)});N?d(HTMLElement.prototype,N):O?d(Element.prototype,O):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");
P(b,Element.prototype,{B:Z,append:aa});ba(b,{I:ca,H:da,replaceWith:ea,remove:fa})}function ba(b,a){var d=Element.prototype;d.before=function(d){for(var f=[],e=0;e<arguments.length;++e)f[e-0]=arguments[e];e=f.filter(function(b){return b instanceof Node&&g(b)});a.I.apply(this,f);for(var c=0;c<e.length;c++)b.a(e[c]);if(g(this))for(e=0;e<f.length;e++)c=f[e],c instanceof Element&&b.b(c)};d.after=function(d){for(var f=[],e=0;e<arguments.length;++e)f[e-0]=arguments[e];e=f.filter(function(b){return b instanceof
Node&&g(b)});a.H.apply(this,f);for(var c=0;c<e.length;c++)b.a(e[c]);if(g(this))for(e=0;e<f.length;e++)c=f[e],c instanceof Element&&b.b(c)};d.replaceWith=function(d){for(var f=[],c=0;c<arguments.length;++c)f[c-0]=arguments[c];c=f.filter(function(b){return b instanceof Node&&g(b)});var k=g(this);a.replaceWith.apply(this,f);for(var u=0;u<c.length;u++)b.a(c[u]);if(k)for(b.a(this),c=0;c<f.length;c++)k=f[c],k instanceof Element&&b.b(k)};d.remove=function(){var d=g(this);a.remove.call(this);d&&b.a(this)}}
function ha(b){function a(a,c){Object.defineProperty(a,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,a);else{var d=void 0;if(this.firstChild){var f=this.childNodes,u=f.length;if(0<u&&g(this)){d=Array(u);for(var m=0;m<u;m++)d[m]=f[m]}}c.set.call(this,a);if(d)for(a=0;a<d.length;a++)b.a(d[a])}}})}n(Node.prototype,"insertBefore",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);
a=Q.call(this,a,c);if(g(this))for(c=0;c<d.length;c++)b.b(d[c]);return a}d=g(a);c=Q.call(this,a,c);d&&b.a(a);g(this)&&b.b(a);return c});n(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=x.call(this,a);if(g(this))for(var d=0;d<c.length;d++)b.b(c[d]);return a}c=g(a);d=x.call(this,a);c&&b.a(a);g(this)&&b.b(a);return d});n(Node.prototype,"cloneNode",function(a){a=I.call(this,a);this.ownerDocument.__CE_hasRegistry?b.f(a):b.l(a);
return a});n(Node.prototype,"removeChild",function(a){var c=g(a),d=C.call(this,a);c&&b.a(a);return d});n(Node.prototype,"replaceChild",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);a=R.call(this,a,c);if(g(this))for(b.a(c),c=0;c<d.length;c++)b.b(d[c]);return a}d=g(a);var e=R.call(this,a,c),k=g(this);k&&b.a(c);d&&b.a(a);k&&b.b(a);return e});E&&E.get?a(Node.prototype,E):b.s(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=
0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)C.call(this,this.firstChild);x.call(this,document.createTextNode(a))}})})}function ia(b){n(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var d=b.c(a);if(d)return new d.constructor}a=B.call(this,a);b.g(a);return a});n(Document.prototype,"importNode",function(a,d){a=ja.call(this,a,d);this.__CE_hasRegistry?b.f(a):b.l(a);return a});n(Document.prototype,
"createElementNS",function(a,d){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var c=b.c(d);if(c)return new c.constructor}a=ka.call(this,a,d);b.g(a);return a});P(b,Document.prototype,{B:la,append:ma})}function P(b,a,d){a.prepend=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&g(a)});d.B.apply(this,c);for(var k=0;k<e.length;k++)b.a(e[k]);if(g(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&
b.b(k)};a.append=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&g(a)});d.append.apply(this,c);for(var k=0;k<e.length;k++)b.a(e[k]);if(g(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&b.b(k)}}function na(b){window.HTMLElement=function(){function a(){var a=this.constructor,c=b.K(a);if(!c)throw Error("The custom element being constructed was not registered with `customElements`.");var f=c.constructionStack;if(0===f.length)return f=
B.call(document,c.localName),Object.setPrototypeOf(f,a.prototype),f.__CE_state=1,f.__CE_definition=c,b.g(f),f;c=f.length-1;var e=f[c];if(e===S)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");f[c]=S;Object.setPrototypeOf(e,a.prototype);b.g(e);return e}a.prototype=oa.prototype;return a}()}function l(b){this.c=!1;this.a=b;this.h=new Map;this.f=function(a){return a()};this.b=!1;this.g=[];this.i=new F(b,document)}function T(){var b=
this;this.b=this.a=void 0;this.f=new Promise(function(a){b.b=a;b.a&&a(b.a)})}function F(b,a){this.c=b;this.a=a;this.b=void 0;this.c.f(this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.g.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function p(){this.o=new Map;this.m=new Map;this.j=[];this.h=!1}function U(b){var a=pa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function g(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||
b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}function G(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}function r(b,a,d){d=d?d:new Set;for(var c=b;c;){if(c.nodeType===Node.ELEMENT_NODE){var f=c;a(f);var e=f.localName;if("link"===e&&"import"===f.getAttribute("rel")){c=f.import;if(c instanceof Node&&!d.has(c))for(d.add(c),c=c.firstChild;c;c=c.nextSibling)r(c,
a,d);c=G(b,f);continue}else if("template"===e){c=G(b,f);continue}if(f=f.__CE_shadowRoot)for(f=f.firstChild;f;f=f.nextSibling)r(f,a,d)}c=c.firstChild?c.firstChild:G(b,c)}}function n(b,a,d){b[a]=d}(function(b){function a(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function d(a){if(l)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&
a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!g(b)&&(b=b.parentNode););a.__importDoc=b}return b}function c(a){var b=document.querySelectorAll("link[rel=import]:not(import-dependency)"),c=b.length;c?h(b,function(b){return k(b,function(){0===--c&&a()})}):a()}function f(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function e(a){f(function(){return c(function(){return a&&
a()})})}function k(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);t&&"style"===a.localName||a.addEventListener("error",c)}}function g(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function m(){var a=this;this.a={};this.b=0;this.f=new MutationObserver(function(b){return a.l(b)});this.f.observe(document.head,
{childList:!0,subtree:!0});this.c(document)}function h(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var l="import"in document.createElement("link"),n=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return n||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var p=/(^\/)|(^#)|(^[\w-\d]*:)/,r=/(url\()([^)]*)(\))/g,x=/(@import[\s]+(?!url\())([^;]*)(;)/g,y=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,
q={J:function(a,b){a.href&&a.setAttribute("href",q.v(a.getAttribute("href"),b));a.src&&a.setAttribute("src",q.v(a.getAttribute("src"),b));if("style"===a.localName){var c=q.C(a.textContent,b,r);a.textContent=q.C(c,b,x)}},C:function(a,b,c){return a.replace(c,function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=q.D(a,b));return c+"'"+a+"'"+e})},v:function(a,b){return a&&p.test(a)?a:q.D(a,b)},D:function(a,b){if(void 0===q.u){q.u=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";q.u="http://a/c%20d"===
c.href}catch(ra){}}if(q.u)return(new URL(a,b)).href;c=q.G;c||(c=document.implementation.createHTMLDocument("temp"),q.G=c,c.A=c.createElement("base"),c.head.appendChild(c.A),c.w=c.createElement("a"));c.A.href=b;c.w.href=a;return c.w.href||a}},v={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,v.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");
a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},t=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);m.prototype.c=function(a){var b=this;h(a.querySelectorAll("link[rel=import]"),function(a){return b.h(a)})};m.prototype.h=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];
d&&d.__loaded&&(a.import=d,this.g(a))}else this.b++,this.a[c]="pending",v.load(c,function(a,d){a=b.m(a,d||c);b.a[c]=a;b.b--;b.c(a);b.i()},function(){b.a[c]=null;b.b--;b.i()})};m.prototype.m=function(a,b){if(!a)return document.createDocumentFragment();t&&(a=a.replace(y,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content;else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);
if(c=a.querySelector("base"))b=q.v(c.getAttribute("href"),b),c.removeAttribute("href");var d=0;h(a.querySelectorAll('link[rel=import], link[rel=stylesheet][href][type=import-disable],\n    style:not([type]), link[rel=stylesheet][href]:not([type]),\n    script:not([type]), script[type="application/javascript"],\n    script[type="text/javascript"]'),function(a){k(a);q.J(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+
encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};m.prototype.i=function(){var a=this;if(!this.b){this.f.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.c(document),a.b||(a.f.observe(document.head,{childList:!0,subtree:!0}),a.j()))};this.s(function(){c=!0;d()});this.o(function(){b=!0;d()})}};m.prototype.flatten=function(a){var b=this;h(a.querySelectorAll("link[rel=import]"),function(a){var c=b.a[a.href];(a.import=
c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.import=a,b.flatten(c),a.appendChild(c))})};m.prototype.o=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");h(f.attributes,function(a){return g.setAttribute(a.name,a.value)});n=g;f.parentNode.replaceChild(g,f);k(g,function(){n=null;b(e+1)})}else a()}var c=document.querySelectorAll("script[import-dependency]"),d=c.length;b(0)};m.prototype.s=function(a){var b=
document.querySelectorAll("style[import-dependency],\n    link[rel=stylesheet][import-dependency]"),c=b.length;if(c){var e=t&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");h(b,function(b){k(b,function(){b.removeAttribute("import-dependency");0===--c&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=d(b);f&&d(f);)f=d(f);f.parentNode!==
document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};m.prototype.j=function(){var a=this;h(document.querySelectorAll("link[rel=import]"),function(b){return a.g(b)},!0)};m.prototype.g=function(b){b.__loaded||(b.__loaded=!0,b.import&&(b.import.readyState="complete"),b.dispatchEvent(a(b.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};m.prototype.l=function(a){var b=this;h(a,function(a){return h(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&
(g(a)?b.h(a):b.c(a))})})};if(l){h(document.querySelectorAll("link[rel=import]"),function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)});var w=function(a){a=a.target;g(a)&&(a.__loaded=!0)};document.addEventListener("load",w,!0);document.addEventListener("error",w,!0)}else{var z=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!z||z.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=g(this)?this:d(this);return a?a.href:z&&z.get?z.get.call(this):
(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});f(function(){return new m})}e(function(){return document.dispatchEvent(a("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=l;b.whenReady=e;b.importForElement=d})(window.HTMLImports=window.HTMLImports||{});var pa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));p.prototype.L=function(b,a){this.o.set(b,
a);this.m.set(a.constructor,a)};p.prototype.c=function(b){return this.o.get(b)};p.prototype.K=function(b){return this.m.get(b)};p.prototype.s=function(b){this.h=!0;this.j.push(b)};p.prototype.l=function(b){var a=this;this.h&&r(b,function(b){return a.g(b)})};p.prototype.g=function(b){if(this.h&&!b.__CE_patched){b.__CE_patched=!0;for(var a=0;a<this.j.length;a++)this.j[a](b)}};p.prototype.b=function(b){var a=[];r(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state?this.connectedCallback(d):
this.i(d)}};p.prototype.a=function(b){var a=[];r(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var d=a[b];1===d.__CE_state&&this.disconnectedCallback(d)}};p.prototype.f=function(b,a){var d=this;a=a?a:{};var c=a.M||new Set,f=a.F||function(a){return d.i(a)},e=[];r(b,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var b=a.import;b instanceof Node&&"complete"===b.readyState?(b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0):a.addEventListener("load",function(){var b=
a.import;b.__CE_documentLoadHandled||(b.__CE_documentLoadHandled=!0,b.__CE_isImportDocument=!0,b.__CE_hasRegistry=!0,c.delete(b),d.f(b,{M:c,F:f}))})}else e.push(a)},c);if(this.h)for(b=0;b<e.length;b++)this.g(e[b]);for(b=0;b<e.length;b++)f(e[b])};p.prototype.i=function(b){if(void 0===b.__CE_state){var a=this.c(b.localName);if(a){a.constructionStack.push(b);var d=a.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{a.constructionStack.pop()}}catch(e){throw b.__CE_state=
2,e;}b.__CE_state=1;b.__CE_definition=a;if(a.attributeChangedCallback)for(a=a.observedAttributes,d=0;d<a.length;d++){var c=a[d],f=b.getAttribute(c);null!==f&&this.attributeChangedCallback(b,c,null,f,null)}g(b)&&this.connectedCallback(b)}}};p.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};p.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};p.prototype.attributeChangedCallback=
function(b,a,d,c,f){var e=b.__CE_definition;e.attributeChangedCallback&&-1<e.observedAttributes.indexOf(a)&&e.attributeChangedCallback.call(b,a,d,c,f)};F.prototype.f=function(){this.b&&this.b.disconnect()};F.prototype.g=function(b){var a=this.a.readyState;"interactive"!==a&&"complete"!==a||this.f();for(a=0;a<b.length;a++)for(var d=b[a].addedNodes,c=0;c<d.length;c++)this.c.f(d[c])};T.prototype.c=function(){if(this.a)throw Error("Already resolved.");this.a=void 0;this.b&&this.b(void 0)};l.prototype.define=
function(b,a){var d=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!U(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.a.c(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var c=function(a){var b=f[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},
f=a.prototype;if(!(f instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var e=c("connectedCallback");var g=c("disconnectedCallback");var h=c("adoptedCallback");var m=c("attributeChangedCallback");var l=a.observedAttributes||[]}catch(qa){return}finally{this.c=!1}a={localName:b,constructor:a,connectedCallback:e,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:m,observedAttributes:l,constructionStack:[]};this.a.L(b,a);this.g.push(a);
this.b||(this.b=!0,this.f(function(){return d.j()}))};l.prototype.j=function(){var b=this;if(!1!==this.b){this.b=!1;for(var a=this.g,d=[],c=new Map,f=0;f<a.length;f++)c.set(a[f].localName,[]);this.a.f(document,{F:function(a){if(void 0===a.__CE_state){var e=a.localName,f=c.get(e);f?f.push(a):b.a.c(e)&&d.push(a)}}});for(f=0;f<d.length;f++)this.a.i(d[f]);for(;0<a.length;){var e=a.shift();f=e.localName;e=c.get(e.localName);for(var g=0;g<e.length;g++)this.a.i(e[g]);(f=this.h.get(f))&&f.c()}}};l.prototype.get=
function(b){if(b=this.a.c(b))return b.constructor};l.prototype.whenDefined=function(b){if(!U(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.h.get(b);if(a)return a.f;a=new T;this.h.set(b,a);this.a.c(b)&&!this.g.some(function(a){return a.localName===b})&&a.c();return a.f};l.prototype.l=function(b){this.i.f();var a=this.f;this.f=function(d){return b(function(){return a(d)})}};window.CustomElementRegistry=l;l.prototype.define=l.prototype.define;l.prototype.get=
l.prototype.get;l.prototype.whenDefined=l.prototype.whenDefined;l.prototype.polyfillWrapFlushCallback=l.prototype.l;var B=window.Document.prototype.createElement,ka=window.Document.prototype.createElementNS,ja=window.Document.prototype.importNode,la=window.Document.prototype.prepend,ma=window.Document.prototype.append,I=window.Node.prototype.cloneNode,x=window.Node.prototype.appendChild,Q=window.Node.prototype.insertBefore,C=window.Node.prototype.removeChild,R=window.Node.prototype.replaceChild,E=
Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),H=window.Element.prototype.attachShadow,w=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),D=window.Element.prototype.getAttribute,J=window.Element.prototype.setAttribute,L=window.Element.prototype.removeAttribute,y=window.Element.prototype.getAttributeNS,K=window.Element.prototype.setAttributeNS,M=window.Element.prototype.removeAttributeNS,O=window.Element.prototype.insertAdjacentElement,Z=window.Element.prototype.prepend,
aa=window.Element.prototype.append,ca=window.Element.prototype.before,da=window.Element.prototype.after,ea=window.Element.prototype.replaceWith,fa=window.Element.prototype.remove,oa=window.HTMLElement,A=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),N=window.HTMLElement.prototype.insertAdjacentElement,S=new function(){},h=window.customElements;if(!h||h.forcePolyfill||"function"!=typeof h.define||"function"!=typeof h.get)h=new p,na(h),ia(h),ha(h),Y(h),document.__CE_hasRegistry=
!0,h=new l(h),Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:h});h=window.customElements;var v=window.HTMLImports;window.WebComponents=window.WebComponents||{};if(h&&h.polyfillWrapFlushCallback){var t,V=function(){if(t){var b=t;t=null;b();return!0}},W=v.whenReady;h.polyfillWrapFlushCallback(function(b){t=b;W(V)});v.whenReady=function(b){W(function(){V()?v.whenReady(b):b()})}}v.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",
{bubbles:!0}))})});h=document.createElement("style");h.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var X=document.querySelector("head");X.insertBefore(h,X.firstChild)})();}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
