(function(){var a={};var d=/[^\s\u00a0]/;var b=CodeMirror.Pos;function c(f){var e=f.search(d);return e==-1?0:e;}CodeMirror.commands.toggleComment=function(e){var g=e.getCursor("start"),f=e.getCursor("end");
e.uncomment(g,f)||e.lineComment(g,f);};CodeMirror.defineExtension("lineComment",function(j,k,n){if(!n){n=a;}var l=this,g=l.getModeAt(j);var m=n.lineComment||g.lineComment;
if(!m){if(n.blockCommentStart||g.blockCommentStart){n.fullLines=true;l.blockComment(j,k,n);}return;}var i=l.getLine(j.line);if(i==null){return;}var f=Math.min(k.ch!=0||k.line==j.line?k.line+1:k.line,l.lastLine()+1);
var e=n.padding==null?" ":n.padding;var h=n.commentBlankLines||j.line==k.line;l.operation(function(){if(n.indent){var q=i.slice(0,c(i));for(var p=j.line;
p<f;++p){var o=l.getLine(p),r=q.length;if(!h&&!d.test(o)){continue;}if(o.slice(0,r)!=q){r=c(o);}l.replaceRange(q+m+e,b(p,0),b(p,r));}}else{for(var p=j.line;
p<f;++p){if(h||d.test(l.getLine(p))){l.replaceRange(m+e,b(p,0));}}}});});CodeMirror.defineExtension("blockComment",function(i,j,m){if(!m){m=a;}var l=this,g=l.getModeAt(i);
var h=m.blockCommentStart||g.blockCommentStart;var k=m.blockCommentEnd||g.blockCommentEnd;if(!h||!k){if((m.lineComment||g.lineComment)&&m.fullLines!=false){l.lineComment(i,j,m);
}return;}var f=Math.min(j.line,l.lastLine());if(f!=i.line&&j.ch==0&&d.test(l.getLine(f))){--f;}var e=m.padding==null?" ":m.padding;if(i.line>f){return;
}l.operation(function(){if(m.fullLines!=false){var p=d.test(l.getLine(f));l.replaceRange(e+k,b(f));l.replaceRange(h+e,b(i.line,0));var n=m.blockCommentLead||g.blockCommentLead;
if(n!=null){for(var o=i.line+1;o<=f;++o){if(o!=f||p){l.replaceRange(n+e,b(o,0));}}}}else{l.replaceRange(k,j);l.replaceRange(h,i);}});});CodeMirror.defineExtension("uncomment",function(w,g,h){if(!h){h=a;
}var u=this,r=u.getModeAt(w);var j=Math.min(g.line,u.lastLine()),k=Math.min(w.line,j);var t=h.lineComment||r.lineComment,f=[];var z=h.padding==null?" ":h.padding,m;
lineComment:{if(!t){break lineComment;}for(var x=k;x<=j;++x){var n=u.getLine(x);var o=n.indexOf(t);if(o==-1&&(x!=j||x==k)&&d.test(n)){break lineComment;
}if(x!=k&&o>-1&&d.test(n.slice(0,o))){break lineComment;}f.push(n);}u.operation(function(){for(var C=k;C<=j;++C){var A=f[C-k];var D=A.indexOf(t),B=D+t.length;
if(D<0){continue;}if(A.slice(B,B+z.length)==z){B+=z.length;}m=true;u.replaceRange("",b(C,D),b(C,B));}});if(m){return true;}}var p=h.blockCommentStart||r.blockCommentStart;
var e=h.blockCommentEnd||r.blockCommentEnd;if(!p||!e){return false;}var y=h.blockCommentLead||r.blockCommentLead;var v=u.getLine(k),l=j==k?v:u.getLine(j);
var q=v.indexOf(p),s=l.lastIndexOf(e);if(s==-1&&k!=j){l=u.getLine(--j);s=l.lastIndexOf(e);}if(q==-1||s==-1){return false;}u.operation(function(){u.replaceRange("",b(j,s-(z&&l.slice(s-z.length,s)==z?z.length:0)),b(j,s+e.length));
var D=q+p.length;if(z&&v.slice(D,D+z.length)==z){D+=z.length;}u.replaceRange("",b(k,q),b(k,D));if(y){for(var C=k+1;C<=j;++C){var B=u.getLine(C),E=B.indexOf(y);
if(E==-1||d.test(B.slice(0,E))){continue;}var A=E+y.length;if(z&&B.slice(A,A+z.length)==z){A+=z.length;}u.replaceRange("",b(C,E),b(C,A));}}});return true;
});})();