ALTER TABLE `#__banners` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__banners` MODIFY `cid` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__banner_clients` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__categories` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__contact_details` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__contact_details` MODIFY `user_id` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__contact_details` MODIFY `catid` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__contact_details` MODIFY `access` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__content_frontpage` MODIFY `content_id` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__content_rating` MODIFY `content_id` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__contentitem_tag_map` MODIFY `content_item_id` bigint(10) UNSIGNED NOT NULL COMMENT 'PK from the content type table';
ALTER TABLE `#__extensions` MODIFY `extension_id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__finder_links` MODIFY `access` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__finder_taxonomy` MODIFY `access` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__menu` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__modules` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__modules_menu` MODIFY `moduleid` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__modules_menu` MODIFY `menuid` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__newsfeeds` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__newsfeeds` MODIFY `catid` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__newsfeeds` MODIFY `access` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__overrider` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key';
ALTER TABLE `#__postinstall_messages` MODIFY `extension_id` bigint(20) UNSIGNED NOT NULL DEFAULT '700' COMMENT 'FK to #__extensions';
ALTER TABLE `#__schemas` MODIFY `extension_id` bigint(10) UNSIGNED NOT NULL;
ALTER TABLE `#__session` MODIFY `userid` bigint(10) UNSIGNED DEFAULT '0';
ALTER TABLE `#__ucm_base` MODIFY `ucm_item_id` bigint(10) UNSIGNED NOT NULL;
ALTER TABLE `#__ucm_base` MODIFY `ucm_type_id` bigint(10) UNSIGNED NOT NULL;
ALTER TABLE `#__updates` MODIFY `update_id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__updates` MODIFY `update_site_id` bigint(10) UNSIGNED DEFAULT '0';
ALTER TABLE `#__updates` MODIFY `extension_id` bigint(10) UNSIGNED DEFAULT '0';
ALTER TABLE `#__update_sites` MODIFY `update_site_id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__update_sites_extensions` MODIFY `update_site_id` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__update_sites_extensions` MODIFY `extension_id` bigint(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `#__users` MODIFY `id` bigint(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `#__user_profiles` MODIFY `user_id` bigint(10) UNSIGNED NOT NULL;
