-- WARNING: Do not rename this file with a different date. It MUST run before any other table updates when upgrading to Joomla! 3.5.0

-- Index and field changes to cater for UTF-8 Multibyte (utf8mb4)
ALTER TABLE `#__menu` DROP KEY `idx_client_id_parent_id_alias_language`, ADD UNIQUE KEY `idx_client_id_parent_id_alias_language` (`client_id`,`parent_id`,`alias`(191),`language`);

ALTER TABLE `#__redirect_links` DROP KEY `idx_link_old`, ADD UNIQUE KEY `idx_link_old` (`old_url`(191));

ALTER TABLE `#__session` MODIFY `session_id` varchar(191) NOT NULL DEFAULT '';

ALTER TABLE `#__user_keys` MODIFY `series` varchar(191) NOT NULL;

-- Convert all tables to UTF-8 Multibyte (utf8mb4)
ALTER TABLE `#__assets` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__associations` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__banners` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__banner_clients` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__banner_tracks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__contact_details` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__content` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__content_frontpage` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__content_rating` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__content_types` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__contentitem_tag_map` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__core_log_searches` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__extensions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_filters` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms0` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms1` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms2` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms3` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms4` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms5` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms6` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms7` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms8` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_terms9` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termsa` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termsb` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termsc` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termsd` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termse` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_links_termsf` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_taxonomy` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_taxonomy_map` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_terms` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_terms_common` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_tokens` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_tokens_aggregate` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__finder_types` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__languages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__menu` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__menu_types` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__messages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__messages_cfg` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__modules` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__modules_menu` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__newsfeeds` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__overrider` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__postinstall_messages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__redirect_links` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__schemas` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__session` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__tags` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__template_styles` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__ucm_base` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__ucm_content` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__ucm_history` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__updates` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__update_sites` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__update_sites_extensions` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__usergroups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__user_keys` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__user_notes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__user_profiles` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__user_usergroup_map` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE `#__viewlevels` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Convert utf8_bin collated columns to utf8mb4_bin collation
ALTER TABLE `#__banners` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__categories` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__contact_details` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__content` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__menu` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'The SEF alias of the menu item.';
ALTER TABLE `#__newsfeeds` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tags` MODIFY `alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__ucm_content` MODIFY `core_alias` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';

-- Convert columns back to their original size
ALTER TABLE `#__banners` CHANGE COLUMN `description` `description` TEXT NOT NULL;
ALTER TABLE `#__banners` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__banners` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__banner_clients` CHANGE COLUMN `extrainfo` `extrainfo` TEXT NOT NULL;
ALTER TABLE `#__banner_clients` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__categories` CHANGE COLUMN `description` `description` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__categories` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `address` `address` TEXT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `misc` `misc` MEDIUMTEXT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `metadesc` `metadesc` TEXT NOT NULL;
ALTER TABLE `#__contact_details` CHANGE COLUMN `metadata` `metadata` TEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `introtext` `introtext` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `fulltext` `fulltext` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `images` `images` TEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `urls` `urls` TEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `metadesc` `metadesc` TEXT NOT NULL;
ALTER TABLE `#__content` CHANGE COLUMN `metadata` `metadata` TEXT NOT NULL;
ALTER TABLE `#__content_types` CHANGE COLUMN `rules` `rules` TEXT NOT NULL;
ALTER TABLE `#__content_types` CHANGE COLUMN `field_mappings` `field_mappings` TEXT NOT NULL;
ALTER TABLE `#__extensions` CHANGE COLUMN `manifest_cache` `manifest_cache` TEXT NOT NULL;
ALTER TABLE `#__extensions` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__extensions` CHANGE COLUMN `custom_data` `custom_data` TEXT NOT NULL;
ALTER TABLE `#__extensions` CHANGE COLUMN `system_data` `system_data` TEXT NOT NULL;
ALTER TABLE `#__finder_filters` CHANGE COLUMN `data` `data` TEXT NOT NULL;
ALTER TABLE `#__finder_filters` CHANGE COLUMN `params` `params` MEDIUMTEXT;
ALTER TABLE `#__languages` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__languages` CHANGE COLUMN `metadesc` `metadesc` TEXT NOT NULL;
ALTER TABLE `#__menu` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__messages` CHANGE COLUMN `message` `message` TEXT NOT NULL;
ALTER TABLE `#__modules` CHANGE COLUMN `content` `content` TEXT NOT NULL;
ALTER TABLE `#__modules` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `metakey` `metakey` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `metadesc` `metadesc` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `metadata` `metadata` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `description` `description` TEXT NOT NULL;
ALTER TABLE `#__newsfeeds` CHANGE COLUMN `images` `images` TEXT NOT NULL;
ALTER TABLE `#__overrider` CHANGE COLUMN `string` `string` TEXT NOT NULL;
ALTER TABLE `#__session` CHANGE COLUMN `data` `data` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__tags` CHANGE COLUMN `description` `description` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__tags` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__tags` CHANGE COLUMN `images` `images` TEXT NOT NULL;
ALTER TABLE `#__tags` CHANGE COLUMN `urls` `urls` TEXT NOT NULL;
ALTER TABLE `#__template_styles` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_body` `core_body` MEDIUMTEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_params` `core_params` TEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_images` `core_images` TEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_urls` `core_urls` TEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_metakey` `core_metakey` TEXT NOT NULL;
ALTER TABLE `#__ucm_content` CHANGE COLUMN `core_metadesc` `core_metadesc` TEXT NOT NULL;
ALTER TABLE `#__ucm_history` CHANGE COLUMN `version_data` `version_data` MEDIUMTEXT NOT NULL COMMENT 'json-encoded string of version data';
ALTER TABLE `#__updates` CHANGE COLUMN `description` `description` TEXT NOT NULL;
ALTER TABLE `#__updates` CHANGE COLUMN `data` `data` TEXT NOT NULL;
ALTER TABLE `#__updates` CHANGE COLUMN `detailsurl` `detailsurl` TEXT NOT NULL;
ALTER TABLE `#__updates` CHANGE COLUMN `infourl` `infourl` TEXT NOT NULL;
ALTER TABLE `#__update_sites` CHANGE COLUMN `location` `location` TEXT NOT NULL;
ALTER TABLE `#__users` CHANGE COLUMN `params` `params` TEXT NOT NULL;
ALTER TABLE `#__user_notes` CHANGE COLUMN `body` `body` TEXT NOT NULL;
ALTER TABLE `#__user_profiles` CHANGE COLUMN `profile_value` `profile_value` TEXT NOT NULL;
ALTER TABLE `#__contentitem_tag_map` DROP INDEX `idx_tag`;
ALTER TABLE `#__contentitem_tag_map` DROP INDEX `idx_type`;