<?php
/**
 * @package     Joomla.UnitTest
 * @subpackage  HTML
 *
 * @copyright   Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM.'/joomla/html/toolbar/button.php';
require_once JPATH_PLATFORM.'/joomla/html/toolbar/button/standard.php';

/**
 * Test class for JButtonStandard.
 * Generated by PHPUnit on 2009-10-27 at 17:04:42.
 */
class JButtonStandardTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @todo Implement testFetchButton().
	 */
	public function testFetchButton()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFetchId().
	 */
	public function testFetchId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}