ALTER TABLE "#__banner_clients" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__banner_clients" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__categories" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__categories" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__content" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__content" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__extensions" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__extensions" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__fields" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__fields" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__fields_groups" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__fields_groups" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__finder_filters" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__finder_filters" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__menu" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__menu" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__tags" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__tags" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__ucm_content" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__ucm_content" ALTER COLUMN "checked_out_time" DROP NOT NULL;
ALTER TABLE "#__user_notes" ALTER COLUMN "checked_out_time" DROP DEFAULT;
ALTER TABLE "#__user_notes" ALTER COLUMN "checked_out_time" DROP NOT NULL;

UPDATE "#__banner_clients" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__categories" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__content" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__extensions" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__fields" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__fields_groups" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__finder_filters" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__menu" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__tags" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__ucm_content" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
UPDATE "#__user_notes" SET "checked_out_time" = null WHERE "checked_out_time" = '1970-01-01 00:00:00';
