<?php
/**
 * @package    Joomla.UnitTest
 *
 * @copyright  Copyright (C) 2005 - 2013 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

include_once JPATH_PLATFORM . '/joomla/document/html/renderer/module.php';

/**
 * Test class for JDocumentRendererModule.
 * Generated by PHPUnit on 2011-10-26 at 19:45:00.
 *
 * @package     Joomla.UnitTest
 * @subpackage  Document
 * @since       11.1
 */
class JDocumentRendererModuleTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var JDocumentRendererModule
	 */
	protected $object;

	/**
	 * Test Render
	 *
	 * @todo Implement testRender().
	 *
	 * @return void
	 */
	public function testRender()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
