<?php
/**
 * @package     Joomla.UnitTest
 *
 * @copyright   Copyright (C) 2005 - 2012 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE
 */

require_once JPATH_PLATFORM . '/joomla/language/language.php';
require_once __DIR__ . '/JLanguageInspector.php';

/**
 * Test class for JLanguage.
 * Generated by PHPUnit on 2012-03-21 at 21:29:28.
 */
class JLanguageTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var JLanguage
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->oldBase = JPATH_BASE;
		$this->object = new JLanguage;
		$this->inspector = new JLanguageInspector('', true);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers JLanguage::getInstance
	 */
	public function testGetInstance()
	{
		$instance = JLanguage::getInstance(null);
		$this->assertInstanceOf('JLanguage', $instance);

		$instance = JLanguage::getInstance(null, true);
		$this->assertInstanceOf('JLanguage', $instance);
		$this->assertTrue($instance->getDebug());
	}

	/**
	 * @covers JLanguage::_
	 */
	public function test_()
	{
		$string1	= 'delete';
		$string2	= "delete's";

		$this->assertEquals(
			'delete',
			$this->object->_($string1,false),
			'Line: '.__LINE__.' Exact case should match when javascript safe is false '
		);

		$this->assertNotEquals(
			'Delete',
			$this->object->_($string1,false),
			'Line: '.__LINE__.' Should be case sensitive when javascript safe is false'
		);

		$this->assertEquals(
			'delete',
			$this->object->_($string1,true),
			'Line: '.__LINE__.' Exact case match should work when javascript safe is true'
		);

		$this->assertNotEquals(
			'Delete',
			$this->object->_($string1,true),
			'Line: '.__LINE__.' Should be case sensitive when javascript safe is true'
		);

		$this->assertEquals(
			'delete\'s',
			$this->object->_($string2,false),
			'Line: '.__LINE__.' Exact case should match when javascript safe is false '
		);

		$this->assertNotEquals(
			'Delete\'s',
			$this->object->_($string2,false),
			'Line: '.__LINE__.' Should be case sensitive when javascript safe is false'
		);

		$this->assertEquals(
			"delete\'s",
			$this->object->_($string2,true),
			'Line: '.__LINE__.' Exact case should match when javascript safe is true, also it calls addslashes (\' => \\\') '
		);

		$this->assertNotEquals(
			"Delete\'s",
			$this->object->_($string2,true),
			'Line: '.__LINE__.' Should be case sensitive when javascript safe is true,, also it calls addslashes (\' => \\\') '
		);
	}

	/**
	 * @covers JLanguage::transliterate
	 */
	public function testTransliterate()
	{
		$string1	= 'Así';
		$string2	= 'EÑE';

		$this->assertEquals(
			'asi',
			$this->object->transliterate($string1),
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			'Asi',
			$this->object->transliterate($string1),
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			'Así',
			$this->object->transliterate($string1),
			'Line: '.__LINE__
		);

		$this->assertEquals(
			'ene',
			$this->object->transliterate($string2),
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			'ENE',
			$this->object->transliterate($string2),
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			'EÑE',
			$this->object->transliterate($string2),
			'Line: '.__LINE__
		);
	}

	/**
	 * @covers JLanguage::getTransliterator
	 */
	public function testGetTransliterator()
	{
		$lang = new JLanguage('');

		// The first time you run the method returns NULL
		// Only if there is an setTransliterator, this test is wrong
		$this->assertNull(
			$lang->getTransliterator()
		);
	}

	/**
	 * @covers JLanguage::setTransliterator
	 * @todo Implement testSetTransliterator().
	 */
	public function testSetTransliterator()
	{
		$function1	= 'phpinfo';
		$function2	= 'print';
		$lang		= new JLanguage('');

		// set -> $funtion1: set returns NULL and get returns $function1
		$this->assertNull(
			$lang->setTransliterator($function1)
		);

		$get = $lang->getTransliterator();
		$this->assertEquals(
			$function1,
			$get,
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			$function2,
			$get,
			'Line: '.__LINE__
		);

		// set -> $function2: set returns $function1 and get retuns $function2
		$set = $lang->setTransliterator($function2);
		$this->assertEquals(
			$function1,
			$set,
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			$function2,
			$set,
			'Line: '.__LINE__
		);

		$this->assertEquals(
			$function2,
			$lang->getTransliterator(),
			'Line: '.__LINE__
		);

		$this->assertNotEquals(
			$function1,
			$lang->getTransliterator(),
			'Line: '.__LINE__
		);
	}

	/**
	 * @covers JLanguage::getPluralSuffixes
	 */
	public function testGetPluralSuffixes()
	{
		$this->assertEquals(
			array('0'),
			$this->object->getPluralSuffixes(0),
			'Line: '.__LINE__
		);

		$this->assertEquals(
			array('1'),
			$this->object->getPluralSuffixes(1),
			'Line: '.__LINE__
		);
	}

	/**
	 * @covers JLanguage::getPluralSuffixesCallback
	 * @todo Implement testGetPluralSuffixesCallback().
	 */
	public function testGetPluralSuffixesCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setPluralSuffixesCallback
	 * @todo Implement testSetPluralSuffixesCallback().
	 */
	public function testSetPluralSuffixesCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getIgnoredSearchWords
	 * @todo Implement testGetIgnoredSearchWords().
	 */
	public function testGetIgnoredSearchWords()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getIgnoredSearchWordsCallback
	 * @todo Implement testGetIgnoredSearchWordsCallback().
	 */
	public function testGetIgnoredSearchWordsCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setIgnoredSearchWordsCallback
	 * @todo Implement testSetIgnoredSearchWordsCallback().
	 */
	public function testSetIgnoredSearchWordsCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getLowerLimitSearchWord
	 * @todo Implement testGetLowerLimitSearchWord().
	 */
	public function testGetLowerLimitSearchWord()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getLowerLimitSearchWordCallback
	 * @todo Implement testGetLowerLimitSearchWordCallback().
	 */
	public function testGetLowerLimitSearchWordCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setLowerLimitSearchWordCallback
	 * @todo Implement testSetLowerLimitSearchWordCallback().
	 */
	public function testSetLowerLimitSearchWordCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getUpperLimitSearchWord
	 * @todo Implement testGetUpperLimitSearchWord().
	 */
	public function testGetUpperLimitSearchWord()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getUpperLimitSearchWordCallback
	 * @todo Implement testGetUpperLimitSearchWordCallback().
	 */
	public function testGetUpperLimitSearchWordCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setUpperLimitSearchWordCallback
	 * @todo Implement testSetUpperLimitSearchWordCallback().
	 */
	public function testSetUpperLimitSearchWordCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getSearchDisplayedCharactersNumber
	 * @todo Implement testGetSearchDisplayedCharactersNumber().
	 */
	public function testGetSearchDisplayedCharactersNumber()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getSearchDisplayedCharactersNumberCallback
	 * @todo Implement testGetSearchDisplayedCharactersNumberCallback().
	 */
	public function testGetSearchDisplayedCharactersNumberCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setSearchDisplayedCharactersNumberCallback
	 * @todo Implement testSetSearchDisplayedCharactersNumberCallback().
	 */
	public function testSetSearchDisplayedCharactersNumberCallback()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::exists
	 * @todo Implement testExists().
	 */
	public function testExists()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::load
	 * @todo Implement testLoad().
	 */
	public function testLoad()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::parse
	 */
	public function testParse()
	{
		$strings = $this->inspector->parse(__DIR__ . '/data/good.ini');

		$this->assertThat(
			$strings,
			$this->logicalNot($this->equalTo(array())),
			'Line: '.__LINE__.' good ini file should load properly.'
		);

		$this->assertEquals(
			$strings,
			array('FOO' => 'Bar'),
			'Line: '.__LINE__.' test that the strings were parsed correctly.'
		);

		$strings = $this->inspector->parse(__DIR__ . '/data/bad.ini');

		$this->assertEquals(
			$strings,
			array(),
			'Line: '.__LINE__.' bad ini file should not load properly.'
		);
	}

	/**
	 * @covers JLanguage::get
	 * @todo Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getName
	 * @todo Implement testGetName().
	 */
	public function testGetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getPaths
	 * @todo Implement testGetPaths().
	 */
	public function testGetPaths()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getErrorFiles
	 * @todo Implement testGetErrorFiles().
	 */
	public function testGetErrorFiles()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getTag
	 * @todo Implement testGetTag().
	 */
	public function testGetTag()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::isRTL
	 * @todo Implement testIsRTL().
	 */
	public function testIsRTL()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setDebug
	 * @covers JLanguage::getDebug
	 */
	public function testGetSetDebug()
	{
		$current = $this->object->getDebug();
		$this->assertEquals(
			$current,
			$this->object->setDebug(true),
			'Line: '.__LINE__
		);

		$this->object->setDebug(false);
		$this->assertFalse(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug(true);
		$this->assertTrue(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug(0);
		$this->assertFalse(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug(1);
		$this->assertTrue(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug('');
		$this->assertFalse(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug('test');
		$this->assertTrue(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);

		$this->object->setDebug('0');
		$this->assertFalse(
			$this->object->getDebug(),
			'Line: '.__LINE__
		);
	}

	/**
	 * @covers JLanguage::getDefault
	 */
	public function testGetDefault()
	{
		$this->assertEquals(
			'en-GB',
			$this->object->getDefault(),
			'Line: '.__LINE__
		);
	}

	/**
	 * @covers JLanguage::setDefault
	 */
	public function testSetDefault()
	{
		$this->object->setDefault('de-DE');
		$this->assertEquals(
			'de-DE',
			$this->object->getDefault(),
			'Line: '.__LINE__
		);
		$this->object->setDefault('en-GB');
	}

	/**
	 * @covers JLanguage::getOrphans
	 * @todo Implement testGetOrphans().
	 */
	public function testGetOrphans()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getUsed
	 * @todo Implement testGetUsed().
	 */
	public function testGetUsed()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::hasKey
	 * @todo Implement testHasKey().
	 */
	public function testHasKey()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getMetadata
	 * @todo Implement testGetMetadata().
	 */
	public function testGetMetadata()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getKnownLanguages
	 * @todo Implement testGetKnownLanguages().
	 */
	public function testGetKnownLanguages()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getLanguagePath
	 * @todo Implement testGetLanguagePath().
	 */
	public function testGetLanguagePath()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::setLanguage
	 * @todo Implement testSetLanguage().
	 */
	public function testSetLanguage()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getLocale
	 * @todo Implement testGetLocale().
	 */
	public function testGetLocale()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::getFirstDay
	 * @todo Implement testGetFirstDay().
	 */
	public function testGetFirstDay()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::parseLanguageFiles
	 * @todo Implement testParseLanguageFiles().
	 */
	public function testParseLanguageFiles()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::parseXMLLanguageFiles
	 * @todo Implement testParseXMLLanguageFiles().
	 */
	public function testParseXMLLanguageFiles()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers JLanguage::parseXMLLanguageFile
	 * @todo Implement testParseXMLLanguageFile().
	 */
	public function testParseXMLLanguageFile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}
